### ISSUE TITLE
datepicker returns the wrong default date when adding activities

### ISSUE THREAD

**Issue by opencats** [opencats/OpenCATS#1]
The default date returned is in 2018!
![capture](https://cloud.githubusercontent.com/assets/106173/4403864/afd06cda-44a9-11e4-8deb-8a921c68318c.PNG). Note - this is for a installation in GMT (so default is DD-MM-YY format).

I believe this code in the datepicker is causing the problem 
DateInput('dateAdd', true, 'MM-DD-YY', '', -1)

Need to test.

**Comment by manilal** [comment]
This issue was moved to opencats/OpenCATS#1

**Comment by RussH** [comment]
Tested 0.9.3 Inferno on demo site - works as expected

**Comment by olenchenko** [comment]
Hi.
I have installed OpenCATS 0.9.4 few days ago (clean install, apache24-2.4.27, php56-5.6.31, mysql55-server-5.5.57 using own server) and I still have this issue (not for all users and not all activities):
![screenshot](https://user-images.githubusercontent.com/176176/29810701-861b211e-8ca9-11e7-8326-f3ccdd0fa457.jpg)
 Any help would be appreciated.

**Comment by skrchnavy** [comment]
#318 created as this is another issue then this reported
