### ISSUE TITLE
Notice: Undefined variable: commandResult

### ISSUE THREAD

**Issue by BentCoder** [opencats/OpenCATS#105]
Hi,

I got this message when uploading a RTF file as a CV.

```
Notice: Undefined variable: commandResult in /var/www/html/opencats/lib/DocumentToText.php on line 161
Notice: Undefined variable: commandResult in /var/www/html/opencats/lib/DocumentToText.php on line 165
```

The file has been successfully attached.

**Comment by skrchnavy** [comment]
There were also further issues, even when file was not processed correctly it could be added into DB.
