### ISSUE TITLE
Troubleshoot MySQL

### ISSUE THREAD

**Issue by rahulsao1987** [opencats/OpenCATS#111]
Hello,
I have been facing a issue with accessing Opencats since last couple of days...
Error msg shown is :-
MySQL Query Failed: Table '.\opencats\mru' is marked as crashed and last (automatic?) repair failed

please help us resolve the issue.
Thanks in advance

Rahul

**Comment by RussH** [comment]
Hi, 

you have a MySQL issue - probably your PC/server lost power. Just use the commandline to repair your MySQL databases;

https://dev.mysql.com/doc/refman/5.7/en/myisam-repair.html

**Comment by rahulsao1987** [comment]
Thanks for your reply Russh,

Is that still helpful, If I completely lost MRU file. I was browsing in localhost/myphpadmin in browser window. Because I new there was some problem in mru file so I was trying to play around with some options, but deleted file accidentally. 
Please suggest

**Comment by RussH** [comment]
I think that's just the most recently used file.. but it's been a while
since I had to fix MySQL..

Can't hurt to log on at a commandline and run myisamchk

Russ



----
Russ

**Comment by rahulsao1987** [comment]
Really appreciate your help.
Its all good now...
I think MRU file was My recent call section because that is the only section I can see which lost some data.
But its not so important so I am all good to go again.
Thanks once again
