### ISSUE TITLE
[Question] Activity log feature

### ISSUE THREAD

**Issue by BentCoder** [opencats/OpenCATS#116]
Hi,

Is there a plan to introduce a feature which allows us to record activities against `Jobs` and `Companies` such as recording email messages and phone calls. I think this feature only exists for people who are looking for jobs (I cannot remember the name of the tab).

Thanks

**Comment by skrchnavy** [comment]
Hi @BentCoder , this is high level list of features https://groups.google.com/forum/#!topic/opencats-dev/ZPyUTRjvxy0
If you need any feature, please describe it there or create issue here with description what is expected.

**Comment by RussH** [comment]
+1 to be able to view emails sent to candidates in the candidate record.

**Comment by BentCoder** [comment]
May I ask if this request will go ahead anytime in future? Thanks

**Comment by RussH** [comment]
Hi.

Your '**log activities and phonecalls**' against companies. This is already implemented - you can log activities against contacts (within companies). You can manually record either.  We cannot log comments against vacancies.

If you were minded, and you also has an IPT system such as asterisk, you could parse the outbound call number against the database of candidates/contacts and automatically add a 'extension xxx(recruiter J Bloggs) called A.Nonymous FutureSystems for 5 minutes.' .. if you're paranoid, you can record the outbound call and insert a link :-)  

This would all be coding in Asterisk though - not in opencats. 

Finally - **record emails sent to candidates** - this is not yet working although the separate script to support it is here; https://github.com/opencats/Opencats-email2activity

..feel free to test/rewrite/fix etc!
