### ISSUE TITLE
No actions work against list members in 0.9.3

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#121]
reproducable on 0.9.3 at http://demo.opencats.org;

when a list of candidates is created, all actions fail, including 'send email' and 'add to pipeline'. 

all 'Actions' fail on candidates to - seems to be the Actions feature that's failing everywhere.

**Comment by RussH** [comment]
@mlespiau @skrchnavy not sure if this failure is due to the access-level checks or the changes to support fluid width? can you check please?

**Comment by skrchnavy** [comment]
for sending email probably this is cause: https://github.com/opencats/OpenCATS/blob/bfce537a8e8516f37ffc62f60c7f3439bbb916dd/modules/candidates/CandidatesUI.php#L3244

**Comment by skrchnavy** [comment]
for add to pipeline probable cause is https://github.com/opencats/OpenCATS/blob/6524560f0e170e315cad0802e9b2d017c5fb7ec5/modules/candidates/CandidatesUI.php#L3290
