### ISSUE TITLE
Resume Upload error

### ISSUE THREAD

**Issue by randhirpanacea** [opencats/OpenCATS#126]
Dear All,

We have Opencats0.9.3 installation in our environment. 
 We are facing below error while uploading the resume.

Resume upload error:
 Notice: Undefined variable: command Result in E:\xampp\htdocs\Opencats9.3\lib\DocumentToText.php on line 194

Please help to resolve this issue ASAP.
 Regards
 Randhir Kumar

**Comment by RussH** [comment]
Sorry - tested 0.9.3 with sample CV at http://demo.opencats.org and do not see this issue. 
Not reproducable - probably related to your installation. 
You can request support at forums.opencats.org but it's not an issue in the codebase.
