### ISSUE TITLE
Error while creating http://localhost/opencats

### ISSUE THREAD

**Issue by sparkest** [opencats/OpenCATS#129]
Please help me with this Error

Fatal error: Uncaught Error: Call to undefined function ereg_replace() in C:\xampp\htdocs\opencats\ajax.php:86 Stack trace: #0 {main} thrown in C:\xampp\htdocs\opencats\ajax.php on line 86

**Comment by RussH** [comment]
Hi sparkest, this appears to be a local installation error rather than an issue with the codebase. Can you raise this in the user support forums please? I suspect it's an issue with your level of PHP or MySQL
