### ISSUE TITLE
Add in updated and enhanced Sphinx Search from Allan Jones

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#13]
RussH to upload package and instructions

**Comment by RussH** [comment]
Note that Sphinx can be auto-enabled within opencats during installation.

**Comment by mwdmwd1** [comment]
What version of Sphinx is tied in, into OpenCATS?

**Comment by RussH** [comment]
the updated Sphinx version is sphinx-2.1.3. Please see https://github.com/opencats/OpenCATS/tree/master/optional-updates/latest-sphinx-search

Closing this issue.
