### ISSUE TITLE
Including Candidates name while sending emails from ATS

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#133]
Hi Russ,
While sending emails to multiple candidates from the ATS, is there any way to personalize it to all the candidates that it is being sent to... 
Do we have the provision of referring them by their 'First Name', 'Last Name' or 'Full Name' as we do in the Templates for status alerts... I tried copying from the templates the name field but it did not work and appeared like this only in the email received...
Dear %CANDFULLNAME%,

**Comment by RussH** [comment]
This isn't currently available within the app and isn't currently on the feature roadmap. However it's certainly technically feasible and if it was developed we would accept it into the repository.

**Comment by amaisonneuve** [comment]
Hi, 

If you look at the email tempates in the Administration section there is a provision to capture the %CANDFULLNAME% in all the templates. Are you not seeing this being reflected in the emails that are sent out? what is being sent out? can you paste an example?

**Comment by KamalJoshiDelhi** [comment]
Hi Alain,
If you see my issue opening comment, I did try applying the same to the emails sent out to candidates from the candidates section directly. It did not work on the emails that are composed using CKEDITOR...
Enclosing 2 screenshots...
1 The email composed...
![image](https://cloud.githubusercontent.com/assets/22269742/19483811/4382b200-9573-11e6-8411-48393c1f3800.png)


2 The email received...

## The mail did not arrive only... let me check the settings again... I remember I used to get the email from ATS....

**Comment by KamalJoshiDelhi** [comment]
here is the screenshot of email received in candidates account

![image](https://cloud.githubusercontent.com/assets/22269742/19485021/5189dd7a-9577-11e6-83d5-fa2aaddf8251.png)

**Comment by amaisonneuve** [comment]
Ok this is definititly a configuration issue, this as PHPMailer would of taken care of all of this, i have done a test on my site and it works properly.

**Comment by RussH** [comment]
Closing as User config issue - please return and reopen if needed.
