### ISSUE TITLE
500 Error after install

### ISSUE THREAD

**Issue by Brando753** [opencats/OpenCATS#138]
After successfully running the installer I get a 500 server error when accessing the main page for first login. Looking at my PHP logs I find this.

NOTICE: PHP message: PHP Fatal error:  Can't inherit abstract function awComponent::drawEnvelope() (previously declared abstract in awPlotAxis) in /var/www/html/cats/lib/artichow/Component.class.php on line 19

**Comment by RussH** [comment]
Hi there, 
sounds like a version issue. Can you confirm your PHP, MySQL versions please? 

Currently the (working) demo site is on Version: 5.5.9+dfsg-1ubuntu4.17
We certainly don't have PHP v7 working yet..

**Comment by Brando753** [comment]
I was using PHP Verson: 5.6.24-0+deb8u1
Mysql Version:  mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by RussH** [comment]
oops, can you also confirm which version of opencats you have installed? If it's 0.9.1 or 0.9.1-a, you will need the following;


Edit line around 38-40 in the config.php depending on your version.

Set /* Resfly.com Resume Import Services Enabled */ to "false"

/* Resfly.com Resume Import Services Enabled */
define('PARSING_ENABLED', false);
