### ISSUE TITLE
Powered by CATS pic on Careers Page does not appear correctly

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#139]
Hi This one is a simpler one for you guys I guess...

The 'Powered by CATS' pic that is supposed to appear on Careers page at the footer seems to me missing from the link and is thus appearing in poor way on the page. Not being a Techie I am not able to figure out where to change that link picture...

Can you please let me know the file and the link I am supposed to put in there so that it appears correctly in the Page footer...???/

**Comment by KamalJoshiDelhi** [comment]
Just thought would leave a screen shot for you to understand and provide me a solution for this as my Job posts are live on the web and applicants accessing the same... Please see the area circled red in the pic below...

![image](https://cloud.githubusercontent.com/assets/22269742/19037247/dd61ee32-8992-11e6-8f3c-6a07d68ae1b9.png)

**Comment by RussH** [comment]
Hmm, thanks  for this - thought I'd caught all instances of 'powered by
cats'. i'll find and replace them with the minimal text link.

**Comment by KamalJoshiDelhi** [comment]
Thanks and do let me know the files to update

**Comment by KamalJoshiDelhi** [comment]
Apart from the Powered by CATS the favicon also seems to be missing from the career portal page... Please see the RED markings on the page... Also I have a suggestion marked in Green and a BUG in the existing functionality which mentioned in RED text in the pics below

![image](https://cloud.githubusercontent.com/assets/22269742/19071513/20ac6742-8a4e-11e6-9b78-998db2b960eb.png)

**## For the Bug mentioned IN RED TEXT above I am enclosing another screenshot below**

![image](https://cloud.githubusercontent.com/assets/22269742/19071595/8496fc90-8a4e-11e6-82d1-6817194ffc25.png)

**Comment by KamalJoshiDelhi** [comment]
I think on your DEMO Site the careers page is not enabled as I could see a blank page on trying to reach "http://demo.opencats.org/careers/index.php".

I could not check if these things are working fine within your DEMO site

**Comment by KamalJoshiDelhi** [comment]
Any Comments on this one??? 
I am sorry for bothering you guys again and again :(

**Comment by RussH** [comment]
Hey Kamal, sorry don't mean to be unresponsive but am completely snowed at
work! I will check in on it this evening



----
Russ

**Comment by amaisonneuve** [comment]
Can you send a screenshot of what your seeing?

**Comment by KamalJoshiDelhi** [comment]
Please take your time RussH... and thanks for your response... :)

**Comment by KamalJoshiDelhi** [comment]
Hey Alain, are you looking for a screenshot from me?

**Comment by amaisonneuve** [comment]
Yes please.

**Comment by KamalJoshiDelhi** [comment]
Screenshot on which action of mine the careers section of your Demo site (the one I am getting a blank)?

I already attached screenshots of my live site...

**Comment by amaisonneuve** [comment]
I see it now.

**Comment by KamalJoshiDelhi** [comment]
Could any of you look into this?

**Comment by KamalJoshiDelhi** [comment]
One more screenshot for letting me register without applying for any jobs... I guess if it is taken care of then I will be able to register through the careers portal...

On the career index page I am not getting to choose this option that says "I have not registered on this website" (circled in the error message box prompted)... BTW this error message box appeared after I pressed on Login button after entering a new email id that is not registered on CATS system yet...

Please see the screenshot attached...

![image](https://cloud.githubusercontent.com/assets/22269742/19141463/47d11dfc-8bb3-11e6-8853-42ffcaf76d90.png)

**Comment by KamalJoshiDelhi** [comment]
Hi Guys anyone got some time to look into this???

**Comment by amaisonneuve** [comment]
So the logo looks fine on my side.

Can you send me the "view source" output from the browser. 

Also please confirm the name and path of the logo on your file system

**Comment by KamalJoshiDelhi** [comment]
Sure here it is...

[view-source file.docx](https://github.com/opencats/OpenCATS/files/516106/view-source.file.docx)

**Comment by KamalJoshiDelhi** [comment]
The path of which logo are you asking about Alain? If you are asking about Powered by CATS logo, I guess it is coming from www.catsone.com and not from any internal logo files... I have all the files as it is in the directory structure as is provided in OPENCATS

**Comment by KamalJoshiDelhi** [comment]
The logo at the top is still the same /images/careers_cats.gif (I just changed this gif file with the one customised for my company)... Other logo files are same as in downloaded OPENCATS version

**Comment by amaisonneuve** [comment]
Ok almost in the office will take a look

**Comment by KamalJoshiDelhi** [comment]
oh sure

**Comment by amaisonneuve** [comment]
Give me an SQL Dump of your 'career_portal_template' table? the link to 'http://www.catsone.com/images/CATS-powered.gif' should be updated to '/images/CATS-powered.gif' in the the 'setting' = 'Footer'

**Comment by KamalJoshiDelhi** [comment]
Here is the screenshot of my DB... I can't see anything next to 'Footer'... 

![image](https://cloud.githubusercontent.com/assets/22269742/19193394/82ff8c00-8cc7-11e6-95c8-2df3d52bac4f.png)

**Comment by amaisonneuve** [comment]
Interesting, then it must be directly in the carreers/index.php?

**Comment by KamalJoshiDelhi** [comment]
No there also I don't have anything to link to 'http://www.catsone.com/images/CATS-powered.gif'

**Comment by KamalJoshiDelhi** [comment]
![image](https://cloud.githubusercontent.com/assets/22269742/19193754/f20922f4-8cc8-11e6-9561-88580f9153a5.png)

**Comment by amaisonneuve** [comment]
Ah ok, got it.. then the solution for you is as follows:

edit /modules/careers/Blank.tpl

replace

<div id="poweredCATS">
		<a href="http://www.catsone.com" target="_blank"><img src="http://www.catsone.com/images/CATS-powered.gif" alt="Powered by: CATS - Applicant Tracking System" title="Powered by: CATS - Applicant Tracking System" /></a>
		</div>

with 

<div id="poweredCATS">
		<a href="http://www.catsone.com" target="_blank"><img src="/images/CATS-powered.gif" alt="Powered by: CATS - Applicant Tracking System" title="Powered by: CATS - Applicant Tracking System" /></a>
		</div>

**Comment by KamalJoshiDelhi** [comment]
Did the changes and got the footer right now and added the text Powered by after changing the path for the image... here is the screenshot...
![image](https://cloud.githubusercontent.com/assets/22269742/19195138/d0507fae-8ccd-11e6-91bd-4ec840ad7cb1.png)

**Comment by KamalJoshiDelhi** [comment]
Still waiting to hear about Favicon as well as the registration link for new candidates
Thanks a lot Alain :)
 Styling with Markdown is supported
Comment Close and comment

**Comment by amaisonneuve** [comment]
So your good?

**Comment by amaisonneuve** [comment]
For the fav

Update: /lib/TemplateUtility.php

change 

        echo '<link rel="icon" href="images/favicon.ico" type="image/x-icon" />', "\n";
        echo '<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />', "\n";

to 

        echo '<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />', "\n";
        echo '<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />', "\n";

**Comment by KamalJoshiDelhi** [comment]
With this change also the favicon started appearing in the login page which it was not earlier but still not on career portal pages... Please look at the following screenshot...

![image](https://cloud.githubusercontent.com/assets/22269742/19196413/14e4811a-8cd3-11e6-9aa0-0b78ec50428e.png)

**Comment by amaisonneuve** [comment]
That must be due to some sort of caching on your side, that is the only instance where we specify favicon.ico for those page.

**Comment by KamalJoshiDelhi** [comment]
oh i see... That is what I was also hoping but it still did not appear after clearing the cache from the browser... I hope when is shutdown and restart may be then it will appear...

BTW there is another important issue/BUG in the functionality on the career portal which I reported earlier in this issue... This is for the candidates who are already registered with ATS if they try to modify their profile after logging in, the button "save profile" becomes deactive and does not do anything afterwards...

![image](https://cloud.githubusercontent.com/assets/22269742/19197152/fde4253a-8cd5-11e6-893d-6550766dd8cd.png)

**Comment by amaisonneuve** [comment]
Both Favicon and Powered By have been fixed

**Comment by filippo-basso** [comment]
Hi, I've tried on a newly installed OpenCATS-0.9.3-3, seen in my browser as a folder, and favicon cannot work, as the position is considered as absolute:

```
<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
```

one question: is OpenCATS thought to be working from the root folder? are there other things that can work less well because of that?

(I really hope that OpenCATS can work inside a folder structure, and not just on the root folder)
thank you!

**Comment by skrchnavy** [comment]
https://github.com/opencats/OpenCATS/pull/143/files there was changed the code to absolute.
and also this https://github.com/opencats/OpenCATS/pull/142/files added absolute link.
