### ISSUE TITLE
Content area turns blue when something is added

### ISSUE THREAD

**Issue by ufrc** [opencats/OpenCATS#140]
Hello,

Testing OpenCats for use, installation was pretty straight forward and got logged in. Once I tried to add anything, the screen returns blue and from that point on, nothing can be done. Removed the INSTALL_BLOCK and then reconfigured with the test database and upon login for the first time, still the same blue screen. I am attaching a screenshot.

![opencats_screenshot](https://cloud.githubusercontent.com/assets/1671414/19116872/f451213c-8ae4-11e6-976d-4501492b0cb0.jpg)

**Comment by RussH** [comment]
Hi, can you confirm version of opencats, and your versions of mysql, php?

**Comment by ufrc** [comment]
Cats 0.9.3 but also did it with 0.9.3-1. 
php 5.1.16
MariaDB 5.5.50

**Comment by ufrc** [comment]
sorry php 5.4.16

**Comment by salisburybs** [comment]
This is something I can reproduce as well.

Ubuntu 16.04
Opencats 0.9.3-1

PHP 5.6.28-1+deb.sury.org~xenial+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

mysql  Ver 15.1 Distrib 10.0.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by salisburybs** [comment]
I've resolved this issue by installing php5.6-mbstring

**Comment by RussH** [comment]
Closed - user installed dependencies!
