### ISSUE TITLE
Forgot Password link in the login screen missing

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#141]
I am sure there is a provision for the users of OPENCATS to ask for their password in case they happen to forget it... I think I saw some configurations to that affect in Config file... However there in no provision for someone to seek the forgotten password from the login link... Screen shot below

![image](https://cloud.githubusercontent.com/assets/22269742/19182159/6e34419a-8c8f-11e6-8563-97ba46019f92.png)

**Comment by amaisonneuve** [comment]
This has to be enabled in the Administration section

Settings->Administration->Passwords

Check off the box "Allow retrieval of forgotten passwords through email:"

**Comment by KamalJoshiDelhi** [comment]
This check box was disabled and was not allowing me to click on it...
however I could get to the code of Passwords.tpl and removed the words disabled from line no 28
<input type="checkbox" name="ForgottenPasswords" disabled>

It however did not save the option even though I could enable the option and check off the box "Allow retrieval of forgotten passwords through email:"... It will again show it unchecked if I go to the save page again...

![image](https://cloud.githubusercontent.com/assets/22269742/19202088/552a7ee4-8cee-11e6-9fa4-ee36da3241de.png)

**Comment by KamalJoshiDelhi** [comment]
Hi All,

In the Administration section
Settings->Administration->Passwords
Check off the box "Allow retrieval of forgotten passwords through email:

# this check box is disabled... It does not allow me to check the box unless I open passwords.tpl file from "modules/settings" folder and remove the words disabled from line no 28

Even after checking it does noting and I still do not get the option of retrieving password at the login screen"

**Comment by amaisonneuve** [comment]
Right, there is no code behind this feature. I will fix that today for you.

**Comment by KamalJoshiDelhi** [comment]
Hi Alain, could u have a look at this?

**Comment by amaisonneuve** [comment]
I am, almost done. Just was booked up last night.

**Comment by KamalJoshiDelhi** [comment]
Hi Alain, Any updates for me please? 
Sorry to be bothering you people again and again... :(

**Comment by Admincycloides** [comment]
Any update in this settings? How can we enable this feature?

**Comment by sooraj2589** [comment]
Any update on this? How can we enable the feature?

@KamalJoshiDelhi ,Have you got the solution? please help

**Comment by sooraj2589** [comment]
@RussH ,Could you please support on this

**Comment by RussH** [comment]
Hi @sooraj2589 sorry but I don't believe @amaisonneuve ever completed this feature. I will have a check through the codebase though

**Comment by RussH** [comment]
@sooraj2589 you can of course manually reset someones password  if you have e.g. phpmyadmin installed

**Comment by sooraj2589** [comment]
@RussH Yes. Manually is possible. I am just wondering about automatic email generation for forgot password. Is the feature disabled in this version?

**Comment by RussH** [comment]
sorry @sooraj2589 this remains unimplemented for now

**Comment by amaisonneuve** [comment]
I can implement .. let me take a look
