### ISSUE TITLE
How can I access to my opencats web in the vps from another pc

### ISSUE THREAD

**Issue by RobertoAEC** [opencats/OpenCATS#146]
Well, i've have a windows server with Xampp, apache, mariadb... 
My question is.. How can I access to my opencats from another machine, the cell of localhost i've changed to my server IP but I cant reach my web, can some one help me?

**Comment by RussH** [comment]
Hi, this is really a user support query for the forums at forums.opencats.org - so please report there. However if you have a VPN with an IP of 1.2.3.4, or a public DNS name of mymachine.com then assuming it's all on the internet and any firewalls are open, then you should be able to reach it from your local internet-connnected PC by opening a browser and typing http://mymachine.org or http://1.2.3.4
