### ISSUE TITLE
Pluggin or toolbar for firefox or chrome browser???

### ISSUE THREAD

**Issue by RobertoAEC** [opencats/OpenCATS#147]
Hello, I'm an IT from a enterprise, now we are changing from cats to opencats, and we need a pluggin or toolbar for chrome or firefox which can insert linkedin profiles, somebody knows of any??

**Comment by RussH** [comment]
Hi Roberto, @amaisonneuve should be committing a chrome plugin imminently..

**Comment by RobertoAEC** [comment]
Thank u so much RussH!

**Comment by RussH** [comment]
@amaisonneuve any news?

**Comment by mlespiau** [comment]
+1 to this request!

**Comment by RussH** [comment]
Hi @amaisonneuve are you still working on this one?

**Comment by wjcheers** [comment]
+1 to this request.
And could the plugin show a link to opencats or show some field of candidate in opencats if the candidate is already in opencats?

**Comment by karthikjoe** [comment]
+1 to this request.
i need it firefox also...

**Comment by RussH** [comment]
I believe dveos (in the forums) has completed this now
