### ISSUE TITLE
Composer needs to be manually run even on a normal install

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#154]
We have an issue in that a few users (one verified instance below) find that they need to install and run composer even for a non-docker installation. https://github.com/opencats/OpenCATS/issues/130#issuecomment-254228495

Looks like composer was introduced in a June/July commit by yourself.. so does it need to be checked so that;
- it's not a requirement for non-docker installations, or;
- it's included in the installation script for non-docker installations.

**Comment by mlespiau** [comment]
It's a requirement for non-docker installations. There is now production code relying on PSR namespaces that are managed once composer is ran. 

We probably have two options:
 - include as part of installation steps (probably the better but with an extra installation step if not using docker)
 - package the application with all dependencies (will lead in bigger zip/tar file)

@RussH, @skrchnavy what are your thoughts?

**Comment by RussH** [comment]
I'd prefer to have it as part of the installation steps - if that's
feasible.



----
Russ

**Comment by skrchnavy** [comment]
My vote for same, later improvement could be writing a script for main platforms.

**Comment by mlespiau** [comment]
I've updated the following guide https://github.com/opencats/OpenCATS/wiki/OpenCATS_Installation but we have many, should we consolidate into one?

**Comment by skrchnavy** [comment]
For many docs: #97 (for the record and interlink the issues)

**Comment by mlespiau** [comment]
Ok, @skrchnavy and @RussH, I've done some automation and release packages contain a full version. Check on my fork: [https://github.com/mlespiau/OpenCATS/releases](https://github.com/mlespiau/OpenCATS/releases)

![image](https://cloud.githubusercontent.com/assets/34041/20400890/5d47b202-acd5-11e6-987f-580bf7db43c8.png)

**Comment by skrchnavy** [comment]
I like the idea to publish release version build from particular tag on github. I don't expect we will publish other snapshots.
Regarding docs, it is fine to have developers and production installation steps, but we shall reuse as much doc. code as possible to avoid duplicate writing and mainly errors in different docs.

**Comment by cptr13** [comment]
I'll work on consolidating documentation this weekend. And possibly some updating.  Where would be the best place to discuss changes or ask opinions on changes?

**Comment by cptr13** [comment]
@mlespiau I agree about reducing steps.  I'm not very technical, and I try to do the documentation in such a way that non-technical people will be able to get through it.  The less steps the better.  However, I don't think the OpenCATS steps are the tough part, it's mostly intuitive and easy to get through.  The challenge from my perspective is how to get a non-technical user through the lamp installation :)

**Comment by cptr13** [comment]
@skrchnavy 

> Regarding docs, it is fine to have developers and production installation steps, but we shall reuse as much doc. code as possible to avoid duplicate writing and mainly errors in different docs.

> 

I can break up the docs in different ways.  I was planning on breaking the lamp/wamp installation out into a separate section, and the the OpenCATS installation piece also.  Anything to eliminate redundancy is a good thing.

However, I'm not entirely sure what you mean by developer and end-user documentation.  What would be an example of something in the developer documentation, that would not need to be in the end user documentation?

**Comment by skrchnavy** [comment]
@cptr13 for example in developers documentation there shall be step how to setup and run tests, how to init database with development/testing data, etc.
When the main source of doc is in repo, developers can contribute with pull requests to improve it.

**Comment by RussH** [comment]
@mlespiau can you include a release with all the dependencies in the opencats project?

**Comment by mlespiau** [comment]
Done! https://github.com/opencats/OpenCATS/releases

**Comment by RussH** [comment]
Thank you!!!



----
Russ
