### ISSUE TITLE
datagrid.php has strict errors (solved) and Deprecated errors on some tabs

### ISSUE THREAD

**Issue by dvirilan** [opencats/OpenCATS#155]
1. around line 1698 pull out to a variable the array_keys($this->_currentColumns) and you are set
use it twice in the code 
generated 2 errors on my machine (I am sorry but I just installed the software and do not feel comfortable to contribute yet)

2. I get deprecation messages on activities and Calendar tabs, for example:
`Deprecated: Non-static method DateUtility::addDaysToDate() should not be called statically, assuming $this from incompatible context in D:\wamp64\www\Candidates\lib\DateUtility.php on line 282`

**Comment by RussH** [comment]
Hi there - welcome! If you don't want to contribute just yet, can you callout the lines you need to change from/to and what it corrects?
