### ISSUE TITLE
500 error while creating a company or job order

### ISSUE THREAD

**Issue by skoneru** [opencats/OpenCATS#160]
I have tried to install the new version on Cpanel. The installation went good and was able to login as well. Upon creating a company and save it  gets a message saying the page isnt working. Same is the case with Job order creation aswell. How to fix this issue?

**Comment by amaisonneuve** [comment]
You need to run composer. 

There's another thread that talks about this issue

**Comment by mlespiau** [comment]
Hi @skoneru which installation guide did you follow? I'll update it with the right steps!

In the meantime, in order to fix this is issue you need to [install composer](https://getcomposer.org/) and then got to your OpenCATS root directory and run: `composer install`

**Comment by skoneru** [comment]
I am on a shared hosting which doesn't support composer install. Any other options? or can you point me to an older release that doesn't need composer install.

**Comment by amaisonneuve** [comment]
What provider? Shared hosting should support composer?

**Comment by mlespiau** [comment]
Ok, I have an idea, I think I can make Travis deploy two release files to github, one with just the code and another one with all dependencies as a bundle!

**Comment by skoneru** [comment]
Great. Thanks!

**Comment by skoneru** [comment]
Just checked with the provider and confirmed that composer is installed and functional on the server, but I still get the same error. Help needed.

**Comment by amaisonneuve** [comment]
Did you run composer from the document root?

**Comment by skoneru** [comment]
Just got the SSH access. Can you guide me to the location of document root to run composer. Is it like Domain/opencats/ or something else?

**Comment by mlespiau** [comment]
It should be, it's the root directory (where index.php it's located).

**Comment by skoneru** [comment]
I have it at domain/opencats/index.php.  I have been there and run the command run: composer install and it says 
-bash: run:: command not found

**Comment by skoneru** [comment]
At last manged to run composer but my PHP version 5.4.4 i snot compatible. Can you please point out to an older release that doesn't need composer install.
 - phpunit/phpunit 5.4.8 requires php ^5.6 || ^7.0 -> your PHP version (5.4.4                                                                                        5) does not satisfy that requirement.

**Comment by skrchnavy** [comment]
phpunit is important for development, for production it shall be skipped. Based on this post: http://stackoverflow.com/questions/21721495/how-to-deploy-correctly-when-using-composers-develop-production-switch it shall be possible to run composer to skip dev. dependencies ```omposer.phar install --no-dev```

**Comment by mlespiau** [comment]
hi @skoneru register to our slack channel here: https://opencats-slack-register.herokuapp.com/ and I'll support you. 

Thanks

**Comment by RussH** [comment]
I assume this is resolved with the latest installation instructions? 
http://opencats-documentation.readthedocs.io/en/latest

Please re-open if not

**Comment by skoneru** [comment]
Yes it was. Thanks!
