### ISSUE TITLE
Travis build / test error

### ISSUE THREAD

**Issue by skrchnavy** [opencats/OpenCATS#176]
Currently all builds on [travis-ci](https://travis-ci.org/opencats/OpenCATS) fails due to problem in docker DB container.

```
Creating opencats_test_data
Creating docker_integrationtestdb_1
Creating opencats_test_mariadb
Creating selenium_test
Creating opencats_test_web
Creating opencats_test_php

ERROR: for opencatsdb  driver failed programming external connectivity on endpoint opencats_test_mariadb (c81839d8e9c00c2a5f7c94559067fb5a15a767b24ccf6c9cdc71bc9355d47318): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

Tested a change in port mapping in docker caused another error:
```
Creating opencats_test_data
Creating selenium_test
Creating docker_integrationtestdb_1
Creating opencats_test_mariadb
Creating opencats_test_web
Creating opencats_test_php


The command "cd docker/; docker-compose -f docker-compose-test.yml up -d" exited with 0.
$ docker-compose -f docker-compose-test.yml exec php /var/www/public/test/runAllTests.sh
2016/12/05 16:18:00 Waiting for host: tcp://opencats_test_mariadb:3308
2016/12/05 16:18:00 Waiting for host: http://opencats_test_web:80
2016/12/05 16:18:00 Received 200 from http://opencats_test_web:80
2016/12/05 16:18:30 Timeout after 30s waiting on dependencies to become available: [tcp://opencats_test_mariadb:3308 http://opencats_test_web:80]
Timeout while waiting for the DB and database.
```

so also in second case DB not started in 30 secs but there is no conflict in ports.

**Comment by RussH** [comment]
build logs seems to show this is because the php service is reused. Can we force this to be destroyed and recreated?

```
WARNING: Image for service php was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.

Creating selenium_test

Creating opencats_test_mariadb

Creating docker_integrationtestdb_1

Creating opencats_test_data

Creating opencats_test_web

Creating opencats_test_php

ERROR: for opencatsdb  driver failed programming external connectivity on endpoint opencats_test_mariadb (365eff9cf2f2f2f8a55f1afd57e4a0853cf0fb65a85a9410e8fb936821ee8be1): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
```

**Comment by RussH** [comment]
may be related to 
https://github.com/docker/docker/issues/8714

**Comment by RussH** [comment]
I'll let Matias agree this one.. as you two are the experts!

**Comment by skrchnavy** [comment]
The only drawback of this approach is in visibility of DB. So when someone creates docker image to manage database (ex. phpmyadmin) it have to be added into links. But for development we shall have extra docker-compose file and this one shall be used only on travis (or black-box internal testing).
Also other services shall be exposed only and linked between container, there could be similar issue with port 80/443 later.

References:
- https://docs.docker.com/docker-cloud/apps/ports/
- https://docs.docker.com/compose/compose-file/#/expose
- https://docs.docker.com/compose/compose-file/#/ports
- https://docs.docker.com/compose/compose-file/#/links

**Comment by mlespiau** [comment]
Hi I think not all these code is actually required. The use of links and adding the port to the hostname in opencats db should not be required. 

Links: there is no use of links since we're using compose and service can discover each other
Port in hostname: not required because it's the default.

**Comment by skrchnavy** [comment]
fixed
