### ISSUE TITLE
Docker image for php container in repository

### ISSUE THREAD

**Issue by skrchnavy** [opencats/OpenCATS#178]
Building docker image each time it runs build/tests on travis is time consuming and same image is used anyway.
It would be nice to publish it into docker hub, similar to the image for standalone-chrome, that is already used: https://hub.docker.com/r/mlespiau/standalone-chrome/

**Comment by skrchnavy** [comment]
There is already image opencats/php created: https://hub.docker.com/r/opencats/php/ , not clear who is author and where are source codes.

**Comment by mlespiau** [comment]
Done in https://github.com/opencats/OpenCATS/pull/187

**Comment by skrchnavy** [comment]
#190 resolved this issue
