### ISSUE TITLE
Travis Builds are failing

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#184]
Builds e.g. #183 are failing with the following error

> ERROR: Service 'php' failed to build: The command '/bin/sh -c docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && docker-php-ext-install -j5 mysql gd ldap soap zip' returned a non-zero code: 1
> 
> The command "cd docker/; docker-compose -f docker-compose-test.yml up -d" exited with 1.
> 
> 0.30s$ docker-compose -f docker-compose-test.yml exec php /var/www/public/test/runAllTests.sh
> 
> ERROR: No container found for php_1

**Comment by skrchnavy** [comment]
It is strange why builds started to fail without any change in docker files. Solution for now is to use 5.6.26-fpm-alpine

**Comment by skrchnavy** [comment]
Strange is that working build is from image named same as not working, digests differs

Working build used:
```Step 1 : FROM php:5.6.28-fpm-alpine
5.6.28-fpm-alpine: Pulling from library/php
Digest: sha256:90d72cd651bac42b165d3572b8dd086be3cb8e0ebbe5958ccf4d5f23d9ce1f9b
Status: Downloaded newer image for php:5.6.28-fpm-alpine
```

Failed build used:
```Step 1 : FROM php:5.6.28-fpm-alpine
5.6.28-fpm-alpine: Pulling from library/php
Digest: sha256:d305eca4c63bcefa39bfda81b863372c53855a42b05a1d6dc73c0cdcdd267037
Status: Downloaded newer image for php:5.6.28-fpm-alpine
```

It looks the image was replaced on docker hub under same name. I checked also older builds with same image name and again different digest.
My observation is that image is replaced every day for php.

I checked changes in https://github.com/docker-library/php and there are few commits 3 days back that could affect the build.

We shall publish our stable php, see #178

**Comment by mlespiau** [comment]
Hi @skrchnavy, agree. Please review the PR.
