### ISSUE TITLE
Missing composer.json file

### ISSUE THREAD

**Issue by svetladm** [opencats/OpenCATS#188]
I started installing OpenCats for Windows. I was following the instructions here: http://opencats-documentation.readthedocs.io/en/latest/install-windows.html . I downloaded OpenCATS.9.1a and there was no composer.json file in opencats-0.9.1a.tar.gz

**Comment by RussH** [comment]
Hi,

The current version is at github.com/opencats/opencats/releases

The version 0.9.1a is quite old and no longer maintained
