### ISSUE TITLE
Incompatibility with Explorer 11 in the editor

### ISSUE THREAD

**Issue by ManuelNL** [opencats/OpenCATS#2]
If you ad or are editing a joborder you will use the build in editor but ..... nothing happens.
You need to click the "cleanup" button first and the cursor appears.

**Comment by manilal** [comment]
This issue was moved to opencats/OpenCATS#2

**Comment by RussH** [comment]
Probably an old version of ckeditor.

**Comment by RussH** [comment]
Tested and works as expected using version 0.9.3 'Inferno' at http://demo.opencats.org and IE 11
