### ISSUE TITLE
different HTML WYSIWYG editors used

### ISSUE THREAD

**Issue by skrchnavy** [opencats/OpenCATS#202]
In the code there are used
*  [tinyMCE](https://www.tinymce.com/) as primary editor for job orders
* [CKEditor](http://ckeditor.com/) as eitor for HTML emails

this shall be unified to use only one.
What is preferred choice?

We have one requirement to have possibility to setup fonts including size.

**Comment by RussH** [comment]
I've had formatting issues reported with tinymce but not with CKEditor. So I'd vote to retain CKEditor

**Comment by mlespiau** [comment]
I've read a little bit online and **I prefer CKEditor** over TinyMCE as well. 

Takeaways:
- CKEditor bigger developer community than TinyMCE
- CKEditor copy and paste works better
- Feature rich, tables and image upload features (but UI harder to use)

Reading:
- Pro CKEditor: https://publish.illinois.edu/a11yfirst/project-progress/research/comparison-of-two-text-edtiors
- Pro TinyMCE: https://www.bersling.com/2016/05/12/best-wysiwyg-for-web-content/
- Pro CKEditor: http://www.krizalys.com/article/ckeditor-vs-tinymce

Also, seems like TinyMCE might take more work to update as we're using an ancient unsupported version. 
We should at least go from [TinyMCE 2.x to 3.x](http://archive.tinymce.com/wiki.php/TinyMCE3x:How-to_migrate_from_TinyMCE_2.x_to_3.x) and then to [4.x](https://www.tinymce.com/download/older-releases/)

**Comment by skrchnavy** [comment]
We also prefer CKEditor so we are aligned.
