### ISSUE TITLE
Integration with a jobboard ??

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#214]
Hi Team OpenCATS,
This is Kamal again and this time I am interested in knowing if we can extract data like applicant info / employer registration and job postings from the jobboard to the OpenCATS from my own jobboard 
(jobportal.tecruiting.com) that I have implemented in a recent past. Also wanted to check out if it could be reverse integrated to show up the questionnaire on the jobboard from the OpenCATS.

Does this require some long-drawn coding etc?

**Comment by skrchnavy** [comment]
example of integration is here: https://github.com/opencats/opencats-wordpress-module - extracts jobs via db selects into wordpress. so this can be inspiration how to create objects in DB.
Other way is to implement http client that calls openCATS 'api' via GET/POST requests. 
for example this is URL for add candidate POST request: http://demo.opencats.org/index.php?m=candidates&a=add but you have to add there form data (see this: https://github.com/opencats/OpenCATS/blob/master/modules/candidates/CandidatesUI.php#L2453). Prior to call you have to be logged in (to have session in cookies).

(missing is implemeted API similar to https://docs.catsone.com/api/v3/)

**Comment by skrchnavy** [comment]
Example of sending post request form in python: http://stackoverflow.com/questions/20759981/python-trying-to-post-form-using-requests but you can find clients in any other language.

**Comment by KamalJoshiDelhi** [comment]
Hi Team,
Just curious.... Are you guys looking to let your users use OpenCATS as a job-board as well... 
When I say this... I mean that you already have the 'Careers' module ready where the applicants can register while applying.... However if we introduce a register/sign in page for the candidates to the career portal, it will complete the applicants/candidates side of the jobboard from where applicants/candidates can track their applications... 
Similarly a module is required for Companies to register/sign in and get to a page from where they can have the facility to post jobs / create questionnaires / manage the candidates that apply to their jobs / and have database access (as allowed by the admin of OpenCATS)... This one is not there at all currently like the 'careers' module for candidates...

**Comment by RussH** [comment]
Query asked and answered
