### ISSUE TITLE
Windows career portal not showing 0.9.3-3

### ISSUE THREAD

**Issue by cptr13** [opencats/OpenCATS#216]
A few users reported this on the forums.  I can confirm.  0.9.3-3.  The career portal doesn't seem to work at all once it's activated

**Comment by cptr13** [comment]
I'm not sure if this is an actual issue.  I just tried it on a different install and it's working fine.  I'm closing this for now and will reopen if I can duplicate.

**Comment by luthviar** [comment]
i still have a same issue, still blank page, i re-install until five times. please tell me how to solve it.

**Comment by mlespiau** [comment]
Hi, could you point out the steps to reproduce the issue? How do I active the portal? What URL should I access and what do you expect to see there?

**Comment by bromine355** [comment]
I had a similar issue. Windows 8 running on xampp.

/careers/index.php   [BLANK PAGE]
/index.php?m=careers&p=showAll [WORKS]

I was able to fix this by modifying /careers/index.php to 

![careers](https://user-images.githubusercontent.com/22333977/40445467-049eb628-5e81-11e8-9a96-829f986aec7a.PNG)

Is the chdir function not working?? I really didn't look into this any further. Hope this helps someone.
