### ISSUE TITLE
MySQL Query Failed

### ISSUE THREAD

**Issue by mindy053** [opencats/OpenCATS#217]
"MySQL Query Failed: Expression #6 of SELECT List is not in GROUP BY clause and contains nonaggregated column "opencats.attachment.attachment_id..."

I am receiving a very similar error for "Job Orders, Candidates, and Companies" tabs. Everything else seems to be fine. 

Ubuntu (16.04), PHP (5.6), OpenCATS (0.9.3-3)

**Comment by cptr13** [comment]
Hi Mindy.  I just want to double check a couple things.  Have you posted on the forums about this?  If so, you may have already answered these questions.

First thing, have you used the documentation and/or walkthrough videos.  Most of the MySQL errors in my experience come from installing OpenCATS without using composer in the installation process.  Did you use composer?

**Comment by cptr13** [comment]
Closing this.  Mindy, please post on the forums first so we can try to trouble shoot this.

**Comment by arunwebber** [comment]
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`
Excecute this code after loging in as root user
