### ISSUE TITLE
issues on UI application

### ISSUE THREAD

**Issue by obarac** [opencats/OpenCATS#22]
Hi,

I'm not developper but a new user of opencats. I set up opencats version cats-0.9.1 on wamp ( Windows 7 ; Apache/2.4.9 (Win64); php 5.5.12 ; Mysql 5.6.17).

The application seems to run but with some issues on the display like this:

![image](https://cloud.githubusercontent.com/assets/11231533/6415583/41011bda-bea0-11e4-9d94-d2443653658e.png)

have you an idea who i can  solve this issues.

Many thanks for your help.

**Comment by RussH** [comment]
Hi, you are using WAMP with error reporting enabled. If you disable this -
normally you disable it in php.ini, but there may be some checkbox to
toggle for WAMP. These 'deprecated errors' are investigated and largely
resolved in the 'top be released' version 0.9.2

Thanks
Russ

**Comment by obarac** [comment]
Hi russh manu thanks for your answer. Did you  where i can get version
0.9.2?

Thanks

**Comment by obarac** [comment]
HI RussH many thanks for your Help. 
When you say disable error reporting enabled in php.ini. If i do this action, are reporting sheets available or not ?

thanks for your  help

obarac
