### ISSUE TITLE
OpenCATS installation error windows

### ISSUE THREAD

**Issue by soohraz** [opencats/OpenCATS#221]
I am getting following error while installing the app:

PHP MySQL extension (mysql) is not loaded.
Check your settings in php.ini.

**Comment by skrchnavy** [comment]
What version is used?
Please check this issues for possible solutions: #154,  #217 , #188.

**Comment by cptr13** [comment]
soohraz, it would be better to start on the forums.  A lot of the simpler issues I can help you resolve there.  I'm closing this out, would you mind posting at forums.opencats.org?
