### ISSUE TITLE
500 Error after submission Company or job order in Win/IIS

### ISSUE THREAD

**Issue by nagintensify** [opencats/OpenCATS#234]
I am using Windows 10, IIS 10, PHP 5.6 PHP 5.6. I installed composer also. Installation of OpenCats went well. But when I submit new company or new job it is throwing 500. What could be the problem.

**Comment by RussH** [comment]
Hi @nagintensify please can you check the same reported issue (and resolution) in https://github.com/opencats/OpenCATS/issues/130#issuecomment-254228495

**Comment by nagintensify** [comment]
That is with apche but mine is IIS. I don't know how to fix in IIS this issue.

**Comment by nagintensify** [comment]
Able to fix this in IIS
