### ISSUE TITLE
 Job order description field not able to take large html text..

### ISSUE THREAD

**Issue by nagintensify** [opencats/OpenCATS#235]
Demo site or my site not able to take large html text in job order description text box. I check description field text size it is "Text" and I changed "Medium Text" still it is the same. It is not allowing me add HTML text in it. 

It just spins after submit. 

Any clue how to fix this?

**Comment by skrchnavy** [comment]
#202 / #203 replaced tinyMCE editor in job order with CKEditor. CKEditor has source mode to paste html text there.
This is planed in v0.9.5.
You can check in demo.opencats.org how it works in email sending (Candidates, select candidate, Actions->Send Email-selected)

Is it solution for you?

**Comment by RussH** [comment]
@nagintensify I just created a fairly large sample job
http://demo.opencats.org/careers/index.php?m=careers&p=showJob&ID=252

Do you need more than in this sample job?

**Comment by skrchnavy** [comment]
Hi @RussH, are you able to paste there html source or did you formatted there using format buttons?
CKEditor has source mode and it is able to render from it formatting / styles.

**Comment by RussH** [comment]
I just cut and pasted it a few time from a monster.com webpage

**Comment by nagintensify** [comment]
Sorry guys, after your comments I checked in different machine its working. something blocking in office laptop to send large data. we can close this.
