### ISSUE TITLE
Email to candidate not available in modal in 0.9.4(testing)

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#248]
![image](https://cloud.githubusercontent.com/assets/282748/25347545/3262f078-2913-11e7-9521-4acc56a47209.png)
when did the 'send email' option disappear?

**Comment by RussH** [comment]
unless this is due to the demo site not having email configured..

**Comment by skrchnavy** [comment]
demo site has checke here: https://github.com/opencats/OpenCATS/blob/0f9c2ebc2416385e4b318539fe325c330ec93959/modules/companies/CompaniesUI.php#L647

**Comment by skrchnavy** [comment]
Requires ACCESS_LEVEL_SA, see PR #192.

**Comment by skrchnavy** [comment]
Access level can be changed using configuration of ACL in config.php (not tested):

```code:php
require_once('./constants.php');
const ACCESS_LEVEL_MAP = array(
        '' => array(
            'candidates.emailCandidates' => ACCESS_LEVEL_READ
        )
    );
```
Explanation - for any user category / role (`''`), object `candidates.emailCandidates` requres minimum level `ACCESS_LEVEL_READ`.

**Comment by mlespiau** [comment]
Thanks @skrchnavy it's clear now. @RussH I'm closing this issue but please reopen if you still need more information / help about this.

**Comment by skrchnavy** [comment]
@RussH I tested configuration and this works:
```
const ACCESS_LEVEL_MAP = array(
        '' => array(
            'candidates.emailCandidates' => ACCESS_LEVEL_SA,
            'candidates.canEmail' => ACCESS_LEVEL_SA
        )
    );
```
Corrected explanation:
any user category / role (`''`) has `ACCESS_LEVEL_SA` to objects `candidates.emailCandidates` and `candidates.canEmail` instead of default access level (_for example read only user has by default ACCESS_LEVEL READ for these objects_)
