### ISSUE TITLE
Disable Modules

### ISSUE THREAD

**Issue by bnvivek** [opencats/OpenCATS#26]
Hi!
I was looking the at following possibilities:
1. disabling some of the unnecessary core modules?
2. disabling / hiding few questions from the careers application page / candidate profiles?

Would it be possible with the present script?

**Comment by RussH** [comment]
Hi @bnvivek yes the modules displayed are defined in constants.php. Remove them from there and you'll stop them showing up. 

There are minimal questions on application pages. However you can setup custom questionnaires per vacancy which may achieve what you want. 

Can you follow up this in the developer mailing list - or in the user support forum? thx.
