### ISSUE TITLE
job order - cannot edit or delete, lost everything below description

### ISSUE THREAD

**Issue by DSPSI** [opencats/OpenCATS#262]
![opencats pngfghjghj](https://cloud.githubusercontent.com/assets/28306362/25626907/369391dc-2f1e-11e7-929e-062b6daf4361.PNG)

http://forums.opencats.org/viewtopic.php?f=4&t=841

**Comment by skrchnavy** [comment]
How long was the text? Was it formatted as html?
Jokorder description in DB is 'text' type which has max size 64kB, so when html format used and truncated, this could be the cause.

**Comment by DSPSI** [comment]
Copied from a word document, 860 words, three pages, 22.7 kB.

**Comment by cptr13** [comment]
This was solved.  Issue opened for tracking.
