### ISSUE TITLE
Email notification coding 

### ISSUE THREAD

**Issue by prasathmscss** [opencats/OpenCATS#276]
Hi OpenCATS Team,
Anyone help me i need  Email notification coding.. could anyone send me to my mail id is prasathmscss@gmail.com.
Please help me guys..

**Comment by skrchnavy** [comment]
Hi @prasathmscss 
Please use forum http://forums.opencats.org/ for support question.
It would be better to describe the issue you have, so whoever knows answer can support you.

**Comment by prasathmscss** [comment]
okay thanks Skrchnavy
