### ISSUE TITLE
I need separate coding for php email notification

### ISSUE THREAD

**Issue by prasathmscss** [opencats/OpenCATS#279]
Hi OpenCATS Team,
Anyone help me i need Email notification coding.. could anyone send me to my mail id is prasathmscss@gmail.com.
Please help me guys..

**Comment by RussH** [comment]
Hi. Can you ask in the user forum - http://forums.opencats.org ? We try to maintain Github issues for issues & feature requests.  Closing the issue and will talk to you on the forum!
