### ISSUE TITLE
blank screen on initial install of 0.9.4

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#284]
navigating to the new install shows a blank screen, the apache error.log has this;
[Fri Jun 23 17:06:40.354743 2017] [:error] [pid 4173] [client 127.0.0.1:54470] PHP Warning:  include(LEGACY_ROOT/modules/install/notinstalled.php): failed to open stream: No such file or directory in /var/www/html/PR/review-github-PRs-here/index.php on line 43, referer: http://127.0.0.1/PR/
[Fri Jun 23 17:06:40.354758 2017] [:error] [pid 4173] [client 127.0.0.1:54470] PHP Warning:  include(): Failed opening 'LEGACY_ROOT/modules/install/notinstalled.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/PR/review-github-PRs-here/index.php on line 43, referer: http://127.0.0.1/PR/
[Fri Jun 23 17:06:45.283647 2017] [:error] [pid 4173] [client 127.0.0.1:54470] script '/var/www/html/PR/review-github-PRs-here/install.php' not found or unable to stat
[Fri Jun 23 17:07:09.405463 2017] [:error] [pid 4177] [client 127.0.0.1:54556] PHP Notice:  Use of undefined constant LEGACY_ROOT - assumed 'LEGACY_ROOT' in /var/www/html/PR/review-github-PRs-here/index.php on line 43

**Comment by skrchnavy** [comment]
@RussH you are probably using version from develop branch or some other that has develop merged.
could you please check if your config.php has this content: https://github.com/opencats/OpenCATS/blob/develop/config.php ?
Also there is one commit in develop that fixed (hope so) this error: 632f8f97cb344e6b652ddb0c3bae805a2f5181aa
