### ISSUE TITLE
Job order page showing incorrect contact details? Possible Bug

### ISSUE THREAD

**Issue by dveos** [opencats/OpenCATS#289]
I am running 0.9.4 and have recently added a new job order linked to a company, which has contacts on the database. However, it seems the contact details displayed on the job order overview is incorrect. 
![untitled](https://user-images.githubusercontent.com/13255967/27586100-c018e968-5b36-11e7-9429-a4335e7697e7.png)

EDIT: Although image shows location as incorrect, it is in fact correct. 
EDIT 2: This seems to be a local issue, if on the Job order there is no contact selected on add job order form, I can't seem to replicate in demo.

**Comment by visitor01** [comment]
bug in JobOrder::create :  $instance->setContactId($companyId);
\src\OpenCATS\Entity\JobOrder.php

**Comment by RussH** [comment]
hi @visitor01 if you have identified an issue, we're always happy to accept corrective patches

**Comment by skrchnavy** [comment]
@visitor01 thanks for analysis, PR #334 created with the fix

**Comment by skrchnavy** [comment]
#334 merged, closing
