### ISSUE TITLE
Windows career portal not showing 0.9.4

### ISSUE THREAD

**Issue by luthviar** [opencats/OpenCATS#292]
Windows career portal not showing 
i still have a same issue like this issue : https://github.com/opencats/OpenCATS/issues/216, still blank page, i re-install until five times. please tell me how to solve it.

thank you

**Comment by karthikjoe** [comment]
+1 request..i am also facing this problem..i am using 0.9.4 opencats in windows server 2008 R2...

**Comment by RussH** [comment]
Hi, 

can you review or paste your apache access and error logs to identify any errors created when this occurs

**Comment by karthikjoe** [comment]
Hi @RussH ...No more errors are in apache error logs...

" 192.168.1.5 - - [13/Jul/2017:18:38:07 +0530] "GET /ats/index.php?m=careers&amp;templateName=CATS+2.0 HTTP/1.1" 200 8181 "http://192.168.1.5/ats/index.php?m=settings&a=careerPortalSettings" "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0"

Just i am getting only empty page only...

![image](https://user-images.githubusercontent.com/29999315/28168067-7352bcb8-67fb-11e7-98cb-fd6d0cab6cf1.png)

**Comment by RussH** [comment]
Other report is also a windows installation - confirmed as working on Linux. Must be some Windows security restriction. can you update #304 with any error logs you see in Windows?

**Comment by RussH** [comment]
Closing - IIS / Windows issue with restrictions on external access locally hosted website
