### ISSUE TITLE
Bulk Imort

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#293]
hello @RussH  & everyone i am new user of openCATS.I need to change bulk resume import folder to my local network computer...is that any way for doing this..?

**Comment by dveos** [comment]
You can use a program called GoodSync, it allows you to connect a folder on your desktop to your server (bulk import folder), whenever there is a new file / modified file it automagically updates server folder.

**Comment by karthikjoe** [comment]
Thanks @dveos i'll check it...and thanks for give this super ATS for us @RussH 
And another one question i am unable to set indian standard timezone openCATS but i did enabled in constants.php and set default timezone in php.ini...when i set "GMT+05:30 Chennai, Kolkata, Mumbai, New Delhi " it's automatically set with this one " GMT+05:00 Ekaterinburg "....what can i do..?

**Comment by RussH** [comment]
@karthikjoe thanks but I'm just the co-ordinator - @matiaslespiau and @skrchnavy are doing all the heavy lifting!
