### ISSUE TITLE
india timezone solved 

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#294]
In my Point...India time zone solved and but unable to set GMT 5:30 timezone in opencats localization.
And i get perfect time in my opencats Ats report.

**Edit php.in file**

[Date]
date_default_timezone_set('Asia/Kolkata');

**Edit Config.php in Opencats folder**

/* Offset to GMT Time. */
define('OFFSET_GMT', 5);

**Comment by RussH** [comment]
Closing as solved - as per reporter
