### ISSUE TITLE
Undefined index: H in C:\xampp\htdocs\ats\lib\JobOrders.php on line 814

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#295]
I am having this error when i open job orders home and clicked at entered job details

**Comment by skrchnavy** [comment]
Please provide also version of OpenCATS.

Please check your config.php, there is JOB_TYPES_LIST array. Is it in comments or used?

The code in latest version: https://github.com/opencats/OpenCATS/blob/3e6c6d94251055a266dc066c321e151e88ef0ee7/lib/JobOrders.php#L814
```php
public static function typeCodeToString($typeCode)
{
 $jobTypes = (new JobOrderTypes())->getAll();
 if($jobTypes[$typeCode] == null)
...
```
indicates that job order type code is not available in list of JobTypes.

It is  some form of misconfiguration, anyway check on L814 shall be fixed to avoid app crash.

**Comment by karthikjoe** [comment]
thanks @skrchnavy for your immediate reply. now i am solved this issue bcz i am enable JOB_TYPES_LIST array in config.php.now i am disabled that and now its working perfectly...
