### ISSUE TITLE
Cannot filter by tags in Candidate Tab.

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#297]
Hello every one....when i click filter by tag in candidates tab i got this error..pls help me overcome this..
thanks in advance...

Notice: Undefined index: filter in C:\xampp\htdocs\ats\lib\DataGrid.php on line 1111

i am using 9.4 opencats in windows server 2008 r2...

**Comment by RussH** [comment]
This is strange - seems to work fine in the demo site.Possibly a Windows issue again? Does this screenshot show what you're trying to do?
![image](https://user-images.githubusercontent.com/282748/28461282-cb706446-6e0d-11e7-9b66-400cf33ba515.png)

**Comment by karthikjoe** [comment]
Yes.. in windows not working @RussH  but in my hosted sites it's working..

**Comment by RussH** [comment]
cannot reproduce
