### ISSUE TITLE
Third party Hosting Problem SSH

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#298]
i am hosting opencats 0.9.4 master in 000.wehost.com . this is a free hosting and main problem is this hosting site not provide SSH for free user.so How can i install composer into this site...?
Any Idea..?
Thanks in advance

**Comment by skrchnavy** [comment]
you can find 'full' versions of opencats on release pages, for example see [release 0.9.4](../releases/tag/0.9.4 ) where are zip and tgz files available for download

**Comment by karthikjoe** [comment]
thanks @skrchnavy  but how can i install this package..?...is this normal installation like installing composer  or its working without installing...!!!..i think this chilly question...bcz i am totally new for opencats..

**Comment by skrchnavy** [comment]
If I am correct, it shall be enough to unpack the files without further commands

**Comment by karthikjoe** [comment]
Ok @skrchnavy thanks i'll check...and thank you so much for immediate help..

**Comment by karthikjoe** [comment]
thanks @skrchnavy its working without composer installation....

**Comment by skrchnavy** [comment]
thanks @mlespiau for the changes in travis build producing these files.
