### ISSUE TITLE
Menu add

### ISSUE THREAD

**Issue by prasathmscss** [opencats/OpenCATS#299]
how to add menu in opencats..

could anyone help me step by step process please

**Comment by RussH** [comment]
Hi, not sure what you're asking here?
You need to add a new tab or rename one of the tabs or you want to change the functionality under one of the tabs? 

If you just want to rename the tabs see here;
http://forums.opencats.org/viewtopic.php?f=4&t=414&hilit=rename+tab#p1586

**Comment by prasathmscss** [comment]
Actually, it not working Russh.. could you please Send step by step process to Add TAB or Menu in Opencats

**Comment by skrchnavy** [comment]
Menu item covers module, so a module is necessary to write. You can look at a simple module, for exampel [Contacts](../blob/master/modules/contacts).
ContactsUI.php implements user interface and it adds 3 subtabs into menu. tpl files handles rendering of GUI, Contacts.tpl is main file displayed when entering main contacts menu.

hello module from examples shall be good starting point, add this module into modules dir and change what is necessary and add proper functionality you need.
There could be some obsolete parameters so you can check contacts module if there is not a change in initialization or add missing includes.

**Comment by prasathmscss** [comment]
Thanks you
