### ISSUE TITLE
Cats freezes/stops working when creating candidate

### ISSUE THREAD

**Issue by scott1981** [opencats/OpenCATS#30]
I posted this in the forums but then I noticed that bugs were being reported here as well.

As of April 10th creating a candidate using Firefox or Chrome (have not tried the other browsers) causes the app to lock up, on both 0.9.1 and 0.9.2.  I tested it on demosite and was able to reproduce it there too.

Steps to reproduce:

1) Go to http://www.opencats.org/test/cats/
2) Click Login to Demo Account
3) Click on Candidates Tab
4) Click on "Add Candidate"
5) The app freezes and you can't even click on any other tab.
6) Close the tab
7) Try to access http://www.opencats.org/test/cats/ on a new tab. It will not load.

**Comment by RussH** [comment]
Thanks, will be able to check this is reproducible. I assume from the report that IE is unaffected?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the O2 network.                                                                                                                                                                                                                From: scott1981Sent: Friday, 10 April 2015 22:07To: opencats/OpenCATSReply To: opencats/OpenCATSSubject: [OpenCATS] Cats freezes/stops working when creating candidate (#30)I posted this in the forums but then I noticed that bugs were being reported here as well.

As of April 10th creating a candidate using Firefox or Chrome (have not tried the other browsers) causes the app to lock up, on both 0.9.1 and 0.9.2.  I tested it on demosite and was able to reproduce it there too.

Steps to reproduce:

1) Go to http://www.opencats.org/test/cats/
2) Click Login to Demo Account
3) Click on Candidates Tab
4) Click on "Add Candidate"
5) The app freezes and you can't even click on any other tab.

—Reply to this email directly or view it on GitHub.

**Comment by scott1981** [comment]
I use Linux so I am unable to test it on IE. However it is server related as I installed 0.9.2 on an old Centos 5 using the following server settings and I can confirm that the problem does not occur.

General Information
Operating System:	Linux pbx.localdomain 2.6.32-431.el6.i686 #1 SMP Fri Nov 22 00:26:36 UTC 2013 i686
Operating System Type:	CATS thinks your operating system is UNIX.
PHP Version:	5.3.28
Database Version:	MySQL 5.1.73
Installation Directory:	/var/www/html/cats

Please check this link for further information: http://www.opencats.org/forums/viewtopic.php?f=4&t=586

**Comment by scott1981** [comment]
Please let me know what other steps you need me to do. I own a VPS with Centos and another one with Ubuntu server (old and newer systems respectively). I am willing to do some testing. Thanks.

**Comment by cats1000** [comment]
The quick fix is the edit your hosts file (usually /etc/hosts) and add the following:
127.0.1.1	soap.resfly.com

There are two calls to this hostname in the following files:
/wsdl/parse.wsdl  
/wsdl/status.wsdl

... that look like:
<service name="CATSDocumentParseService">
<port name="CATSDocumentParsePort" binding="typens:CATSDocumentParseBinding">
<soap:address location="http://soap.resfly.com/parse.php"/>
</port>
</service>

and 

<service name="StatusService">
<port name="StatusPort" binding="typens:StatusBinding">
<soap:address location="http://soap.resfly.com/status.php"/>
</port>
</service>

The URLs above appear to now be dead (or don't respond in a reasonable time).  I don't think there are any side effects with these removed.

**Comment by RussH** [comment]
Thank you. There are a bunch of fixes from Dan Needles to remove all talk back to catsone.com (of which this is one)which are contributed but not yet committed to trunk yet. ‎I can share the entire document if you drop me an email. Russh@opencats.org                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the O2 network.                                                                                                                                                                                                                From: cats1000Sent: Saturday, 11 April 2015 02:09To: opencats/OpenCATSReply To: opencats/OpenCATSCc: RussHSubject: Re: [OpenCATS] Cats freezes/stops working when creating candidate (#30)The quick fix is the edit your hosts file (usually /etc/hosts) and add the following:
127.0.1.1   soap.resfly.com

There are two calls to this hostname in the following files:
/wsdl/parse.wsdl
/wsdl/status.wsdl

... that look like:


 



and 



 



The URLs above appear to now be dead (or don't respond in a reasonable time).  I don't think there are any side effects with these removed.

—Reply to this email directly or view it on GitHub.

**Comment by scott1981** [comment]
Great I am willing to test. I would also like to report other bugs for
0.9.1 Is this possible or is 0.9.1 no longer maintained?

Thanks.

**Comment by RussH** [comment]
Hi Joe,

0.9.1 is no longer maintained - please can you check if the errors are
reproducible on 0.9.2 and submit them as required!

Russ

**Comment by scott1981** [comment]
Russ

These errors are present in 0.9.2

The fastest workaround for now is to edit hosts file. I think this also
needs to be taken out of the code as part of catsone cleaning.

Thanks.

**Comment by amaisonneuve** [comment]
Interesting that issue showed up this weekend, thanks for the quick workaround was going to look into it further tonight.

**Comment by RussH** [comment]
just t committed the fix - set refly parsing enabled to 'flase' in config.php.
