### ISSUE TITLE
MySQL Query Failed: Unknown column 'stored_on_s3' in 'field list'

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#300]
### Expected behavior and actual behavior.
Expetced to scan iported documents but not scaning and i am getting this error.
### What version of opencats are you running? WAMP or LAMP? 
WAMP
### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
![image](https://user-images.githubusercontent.com/29999315/28155991-778a7032-67ce-11e7-86de-fa4017d52ed6.png)

**Comment by RussH** [comment]
Can you confirm if this is opencats 0.9.4 please

**Comment by karthikjoe** [comment]
Hi @RussH  no this is full version.And i Solved this issue using your commands
ALTER TABLE 'attachment' ADD COLUMN 'stored_on_s3' tinyint(1) default 0;
ALTER TABLE 'attachment' ADD COLUMN 'stored_locally' tinyint(1) default 0;

**Comment by RussH** [comment]
Great, closing

**Comment by RussH** [comment]
Great, closing

**Comment by kiran7306** [comment]
i am getting this error in when i click on **Rescan Documents and delete Documents**   in administartion-->dataimport-->

I am using .9.4 version

Query Error -- Report to System Administrator ASAP


MySQL Query Failed: Unknown column 'stored_on_s3' in 'field list'

SELECT
                attachment_id as attachmentID,
                site_id as siteID,
                title,
                original_filename as originalFileName,
                stored_filename as storedFileName,
                content_type as contentType,
                resume,
                text,
                date_created as dateCreated,
                date_modified as dateModified,
                directory_name as directoryName,
                file_size_kb as fileSizeKB,
                stored_on_s3 as storedOnS3,
                stored_locally as storedLocally
            FROM
                attachment
            WHERE
                data_item_type = 500
            AND
                site_id = 1
