### ISSUE TITLE
How to integrate openCalais in openCATS

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#301]
Hello everyone i want to add any API for resume parsing services in opencats 0.9.4 (WAMP). Please guide me to step by step process for adding API in opencats...
Thanks in advance

**Comment by RussH** [comment]
Hi @karthikjoe this is currently out of scope for the application and will have to be added as a feature request to the roadmap. If you engage a developer to add it, please contribute the code back here
