### ISSUE TITLE
How to edit attached documents using any editor

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#303]
I want to edit attached docs with using any editor. But i don't know to integrate editor into OpenCATS.
I am using WAMP version OpenCATS 9.0.4...
Thanks in Advance

**Comment by skrchnavy** [comment]
CK editor is embedded html editor and is not intended to edit document in doc/docx format.
You can download attached doc document, edit it and then upload as new attachment.

For user support please use http://forums.opencats.org/ , github issue tracker is primarily used to track bugs and feature requests.

**Comment by karthikjoe** [comment]
Ok @skrchnavy thanks for your reply. I am going to use http://forum.opencats.org/ hereafter..
