### ISSUE TITLE
Unable to search using resume keywords in hosted sites

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#305]
### Expected behavior and actual behavior.
I am trying to search using resume keywords on my hosted opencats site but it's shown No matching entries found..
### Steps to reproduce the problem.
none
### What version of opencats are you running? WAMP or LAMP? 
WAMP OpenCATS full Master version without installing composer
### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
![image](https://user-images.githubusercontent.com/29999315/28454361-9a68dcce-6e18-11e7-915e-d532807ec6f6.png)

**Comment by RussH** [comment]
Hi @karthikjoe for resume keyword search to work, you will need to install and configure the full-text search engine sphinx as per the instructions here - this is the 64-bit installation. Thsi is typically an issue for shared hosting as they dont permit you to install the required software packages. 
https://github.com/opencats/OpenCATS/tree/master/optional-updates/latest-sphinx-search

Alternatively, on the opencats forum dveos user contribution seems to be a quick and easy replacement that will work on shared hosting (not tested this myself) ;
http://forums.opencats.org/viewtopic.php?f=4&t=907&p=3093&hilit=dveos#p3093

**Comment by karthikjoe** [comment]
Thanks @RussH  for your quick response.I'll already download those codes from opencats forum and today i replaced with old codes but its not working.So only i post this issue in git hub.
I need to search using resume keywords is that any alternative available..?
Your contribution make myself feels better with opencats.
Thanks in advance @RussH ...

**Comment by RussH** [comment]
Okay, you're on your own installation? it can get fairly technical but https://github.com/opencats/OpenCATS/tree/master/optional-updates/latest-sphinx-search is what I have configured and it works perfectly.. Otherwise you can post into the opencats forum to see if dveos can assist with his 'quick fix'

**Comment by karthikjoe** [comment]
Hi @RussH  now it's working...i did totally reset my website and upload a new opencats file including modified codes and now it's working superly...
And one more new request do you help me to add filter in "Search Candidates" tap...!!!
If i complete this task we are going launch a opencats for official use.
