### ISSUE TITLE
Reset admin password from database

### ISSUE THREAD

**Issue by rezizter** [opencats/OpenCATS#307]
I have taken over an existing install of opencats, however I don't have the username and password.

it is not the usual admin or cats password:

select * from user; shows me there is an admin user but the password field is encrypted.
How do I reset the admin password?

**Comment by karthikjoe** [comment]
hi @rezizter just login with your phpmyadmin page and select database then you must select user after that now you can see the user name and password but passwords are encrypted you don't worry just change that password and try login again using changed password.

**Comment by RussH** [comment]
@cptr13 can you add this advice into the opencats-documentation?

**Comment by skrchnavy** [comment]
added issue into documentation repository, @RussH you can close this issue here

**Comment by RussH** [comment]
https://documentation.opencats.org/how-tos/password-resets
