### ISSUE TITLE
  Cannot modify header information - URGENT HELP NEEDED

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#309]
Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd4/526/2231526/public_html/lib/Session.php:778) in /storage/ssd4/526/2231526/public_html/lib/CATSUtility.php on line 275.
![image](https://user-images.githubusercontent.com/29999315/28809633-1d38a8fa-76a2-11e7-9dae-bfa52e3b6610.png)

**Comment by skrchnavy** [comment]
duplicate to #308
