### ISSUE TITLE
Error while trying to generate report from Jobs view

### ISSUE THREAD

**Issue by scott1981** [opencats/OpenCATS#31]
Using opencats 0.9.1 I get an error whenever I try to generate a report from any given job.

These are the steps:

1) Click on Jobs
2) Click on any job
3) Click on Generate report
4) Click on ok or accept after reviewing variables

I get this error:

FPDF error: Missing or incorrect image file: https://internal.vrosolutions.com/ats/index.php?m=graphs&a=jobOrderReportGraph&data=28%2C2%2C0%2C0

Server info:

General Information
Operating System:	Linux ice.weblocalhost.com 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64
Operating System Type:	CATS thinks your operating system is UNIX.
PHP Version:	5.5.22
Database Version:	MySQL 5.5.42-cll
Installation Directory:	/home/vro/public_html/internal/ats

**Comment by scott1981** [comment]
Just noticed 0.9.1 is no longer maintained. Closing issue.

**Comment by RussH** [comment]
same issue on 0.9.2 - however

just add:

allow_url_fopen = ON

on php.ini (create new if not exists) solves the problem.

**Comment by scott1981** [comment]
I already had that function enabled in php.ini so this is not the cause of
the problem. It's been reported alredy under:

http://www.opencats.org/forums/viewtopic.php?f=4&t=24&hilit=fpdf#p172

On 12 April 2015 at 08:18, RussH <notifications@github.com> wrote:

> same issue on 0.9.2 - however
>
> just add:
>
> allow_url_fopen = ON
>
> on php.ini (create new if not exists) solves the problem.
>
>
> On 11 April 2015 at 22:47, scott1981 <notifications@github.com> wrote:
>
> > Just noticed 0.9.1 is no longer maintained. Closing issue.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/opencats/OpenCATS/issues/31#issuecomment-91932570>.
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/opencats/OpenCATS/issues/31#issuecomment-92035388>.
>



-- 
Nicolas.

**Comment by RussH** [comment]
can't reproduce - works fine on the test server at
http://opencats.org/test/cats/

**Comment by scott1981** [comment]
Found a fix (and an opportunity for feature/functionality request). I use htaccess as part of security measures to control who can access cats :)

I figured that removing htaccess fixes the issue. Is there any way that this could work along with htaccess protection?

Thanks.

**Comment by RussH** [comment]
Hiya,

you could just restrict the htaccess to the login page(s) and not to the
entire site.
