### ISSUE TITLE
 Warning: set_time_limit() has been disabled for security reasons

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#310]
Hi Everyone i got this error in shared hosting...Please help me to rectify this error
 Warning: set_time_limit() has been disabled for security reasons in /storage/ssd5/528/2449528/public_html/modules/install/ajax/ui.php on line

**Comment by skrchnavy** [comment]
@karthikjoe :
based on doc: http://php.net/manual/en/function.set-time-limit.php
there is no workaround when strict mode is on.

Anyway, it shall be OK to remove all occurrences of this function in code, the risk is that in some case when operation takes longer time script could be stopped before finalisation.
This call is used in imports, backup and install and value is in some cases set to 300/500 secs and on other places infinite. 

You can check the limit set in php.ini via `ini_get('max_execution_time')` function call in a script.
By default it is 30 secs (http://php.net/manual/en/info.configuration.php#ini.max-execution-time)

**Comment by skrchnavy** [comment]
@mlespiau / @RussH
Do you have any idea how to cope with safe mode? Shall be supported it?
First step could be to add the calls of this function inside an `if` statement detecting safe mode.

**Comment by karthikjoe** [comment]
Thanks @skrchnavy for ur quick response but I am Not a developer i am very new to programming & PHP also..so i can't do with any scripts or coding

**Comment by skrchnavy** [comment]
@karthikjoe 
Not big task even for new programmer. Just find all occurrences `set_time_limit`
and add single line comment before the function call, so this shall look like `// set_time_limit(xxx);`

To help you to identify files where the change shall be implemented, use this link: https://github.com/opencats/OpenCATS/search?q=set_time_limit&type=Code , it shall be in nine files.

**Comment by karthikjoe** [comment]
Ok @skrchnavy  thanks....I did it...Thanks again

**Comment by RussH** [comment]
Merged #311 into Master - shall be in 0.9.4-1
