### ISSUE TITLE
ca-cacert package for Debian Jessie (8) is now in the backports repo

### ISSUE THREAD

**Issue by apmuthu** [opencats/OpenCATS#313]
### Expected behavior and actual behavior.
Without the [`ca-cacert` package](http://ftp.debian.org/debian/pool/main/c/ca-cacert/ca-cacert_2011.0523-2~bpo8+1_all.deb), `composer` will not update / install.

### Steps to reproduce the problem.
Update documentation

### What version of opencats are you running? WAMP or LAMP? 
* 0.9.4 'Countach'
* Debian 8 Jessie 64 bit LAMP

**Comment by cptr13** [comment]
Moved to OpenCATS Documentation.

**Comment by apmuthu** [comment]
There are several OpenCATS Documentation links - which one has been updated.

It should be updated in [Install on Debian 8 Jessie](http://opencats-documentation.readthedocs.io/en/latest/Install-Debian8.html).
