### ISSUE TITLE
Unable to install opencats on ipower shared hosting

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#314]
### Expected behavior and actual behavior.
I am getting this error in installation screen.
**Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.**
### What version of opencats are you running? WAMP or LAMP? 
LAMP, Shared hosting, ipower , & This is full version opencats working without composer...(Tested on free hosting site)
### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
![image](https://user-images.githubusercontent.com/29999315/29364010-c69177ce-82af-11e7-8c9c-864577358025.png)
And this is my site link
http://boarding.valuewingcoe.com/info.php

**Comment by RussH** [comment]
can you show your error logs please - bound to be some MySQL or Apache issue probably bound up in shared hosting restrictions.

**Comment by karthikjoe** [comment]
My System Admin Was fixed this issue. It's Now Working Fine.
