### ISSUE TITLE
How to add extra TAB or Menu in Opencats..

### ISSUE THREAD

**Issue by prasathmscss** [opencats/OpenCATS#317]
Please help me out. how to add extra TAB or MENU in opencats.
Step by step process to create TAB OR MENU for my understanding.

**Comment by RussH** [comment]
please see the first issue you opened for this - can you reopen and comment in there please if you need further support

**Comment by prasathmscss** [comment]
Actually, it not working Russh.. could you please Send step by step process to Add TAB or Menu in Opencats

**Comment by skrchnavy** [comment]
Menu item covers module, so a module is necessary to write. You can look at a simple module, for exampel [Contacts](..\blob/master/modules/contacts).
ContactsUI.php implements user interface and it adds 3 subtabs into menu. tpl files handles rendering of GUI, Contacts.tpl is main file displayed when entering main contacts menu.

**Comment by prasathmscss** [comment]
Still, i cannot able to add extra Tab in opencats

**Comment by RussH** [comment]
Hi @prasathmscss. There are multiple examples in the forums for e.g. adding the ldap module. Please follow those as a guide;
http://forums.opencats.org/viewtopic.php?f=2&t=122&p=614&hilit=Remove+tabs#p614
http://forums.opencats.org/viewtopic.php?f=4&t=844
http://forums.opencats.org/viewtopic.php?f=4&t=213
http://forums.opencats.org/viewtopic.php?f=2&t=638&p=2234&hilit=remove+tab#p2234

and a brief overview of the codebase and how it works;
http://opencats-documentation.readthedocs.io/en/latest/shortdevguide.html

As I am not developing a new module for you I can't provide a 'step by step' guide as you're seeking to  develop entirely new functionality,. not configuring the existing opencats app.

Finally - if you do want a new module that's customised for you there are companies out there who will do this for you;
http://forums.opencats.org/viewtopic.php?f=12&t=620

Alternatively, other than re-requesting a 'step-by-step guide' - if you share what you're trying to achieve perhaps we can assist.
