### ISSUE TITLE
Mass Candidate Import

### ISSUE THREAD

**Issue by nlargebiz** [opencats/OpenCATS#319]
What do I need to do in order to do an import of Candidate information, (Not from resume) from an excel candidate spreadsheet with basic info on candidates ?

Also, no option to import contact information.

If this is still in development, when is the intended rollout for those functionalities?

Thanks :)

### Expected behavior and actual behavior.
I have an excel file with candidate data that I wish to import into the system to avoid entering the items individually.  I have CentOS7 on a VirtualBox VM and I have also tried converting the file to csv and txt but every time I try to do this it says "Oops, there is a problem with your request".  

### Steps to reproduce the problem.
Create an excel file of candidate base data and post it to var/www/html/opencats/massimport.  This is not a resume file, but I dont know how to use the GUI in opencats in order to successfully import just the candidate base data.

### What version of opencats are you running? WAMP or LAMP? 
0.9.3 Inferno on Linux Centos7 via VirtualBox VM

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
Where would I find these logs?

**Comment by RussH** [comment]
Hi, what you're looking for is in Settings / Administration / Data Import ... which supports the following
  Resumes
  Candidates
  Companies
  Contacts

**Comment by nlargebiz** [comment]
Oh ... Now I see! 

When I click on the Settings Tab it takes me straight to the settings -> profile, not directly to settings which was misleading.  But NOW I see.  Thanks for the info :)

Nick.

**Comment by nunoguerreiro** [comment]
but what is the format of the CSV to import ?
