### ISSUE TITLE
SendMail option available for regular user in 0.9.3 but not available in 0.9.4

### ISSUE THREAD

**Issue by nlargebiz** [opencats/OpenCATS#321]
### Expected behavior and actual behavior.
A regular user with only Add & Edit permission (not delete) should be able to see "Send Email" in the actions menu in Candidates.  This appears to work on a test VM using linux Centos 7 OS with opencats 0.9.3 but the option is not visible when doing the same test on a 0.9.4 implementation

### Steps to reproduce the problem.
On a default implementation of opencats 0.9.3 do the following:
  * log in as admin
  * create a user test1 and assign Add, Edit permisisons to that user.
  * log out as admin and log in as test1.
  * click on the Candidates tab.
  * click on the "Action" link on the bottom left hand side of the page.
  * The context menu should appear.  On 0.9.3 this will include a "Send Email" option and on 0.9.4 the "Send Mail" option will not be visible.

### What version of opencats are you running? WAMP or LAMP? 
As per the details above, both 0.9.3 and 0.9.4

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
Not sure where to find these.

**Comment by RussH** [comment]
There is an ACL implemented on 0.9.4 to permit / prevent standard users from some features. Update the ACL to permit standard users to email and it will be available to them.

**Comment by nlargebiz** [comment]
Thanks Russ.  What is an ACL ?  Is this a file that requires editing ?  If so, what file is that, and where and how should it be changed ?

Thanks, Nick.

**Comment by RussH** [comment]
Hi Nick, the ACL is documented here... https://github.com/opencats/OpenCATS/wiki/Access-Control-Lists
You can mention @skrchnavy here if you still have issues

**Comment by nlargebiz** [comment]
Thanks again Russ; I will certainly take a look at that. :)

Nick.

**Comment by skrchnavy** [comment]
in #192 was changed the behaviour to require ACCESS_LEVEL_SA to send email. If you reduce level to read, your installation could be used for SPAM. Be aware of that.

If you are sure that it would work, you could create role with this (role name is emailer but you could name it based on your preference):

```
const ACCESS_LEVEL_MAP = array(
    'emailer' => array(
        'candidates.emailCandidates' => ACCESS_LEVEL_SA,
        'candidates.canEmail'=> ACCESS_LEVEL_SA
    )
);
```
then you have to assign role to user  in Edit User page.

I haven't tested it, so if you see any issue with such configuration, please provide info.

**Comment by RussH** [comment]
@nlargebiz  can you confirm this resolves your issue? The Issue will auto-close in 14 days if there's no reply. Thx!

**Comment by nlargebiz** [comment]
Russ,

I am including Max in this email - he should have a better idea at this
point as-to whether the issue is still outstanding.

Thanks, Nick.

**Comment by RussH** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
