### ISSUE TITLE
New OpenCat setup, while setting up site with demo data get following db error..

### ISSUE THREAD

**Issue by mrmubi** [opencats/OpenCATS#322]
I am trying to setup opencats current version with demo data when i do that get following error.
please note it work fine with i setup with new data...

Query Error -- Please Report This Bug!

MySQL Query Failed: Invalid default value for 'date_created'

CREATE TABLE `activity` (
  `activity_id` int(11) NOT NULL auto_increment,
  `data_item_id` int(11) NOT NULL default '0',
  `data_item_type` int(11) NOT NULL default '0',
  `joborder_id` int(11) default NULL,
  `site_id` int(11) NOT NULL default '0',
  `entered_by` int(11) NOT NULL default '0',
  `date_created` datetime NOT NULL default '0000-00-00 00:00:00',
  `type` int(11) NOT NULL default '0',
  `notes` text collate utf8_unicode_ci,
  `date_modified` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`activity_id`),
  KEY `IDX_data_item_id` (`data_item_id`),
  KEY `IDX_entered_by` (`entered_by`),
  KEY `IDX_site_id` (`site_id`),
  KEY `IDX_type` (`type`),
  KEY `IDX_data_item_type` (`data_item_type`),
  KEY `IDX_type_id` (`data_item_type`,`data_item_id`),
  KEY `IDX_joborder_id` (`joborder_id`),
  KEY `IDX_date_created` (`date_created`),
  KEY `IDX_date_modified` (`date_modified`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**Comment by skrchnavy** [comment]
Could you please provide some info about componets:
- MySql / Maria DB version
- what is current version ? From develop branch sources or released?

**Comment by Bloafer** [comment]
@skrchnavy I have found that on Ubuntu 16.04.1 running MySQL 5.7.20 that `datetime` fields do not like `0000-00-00 00:00:00` as a default and have had to update my SQL queries to default to `1000-01-01 00:00:00` so

`date_created datetime NOT NULL default '0000-00-00 00:00:00'`

should be

`date_created datetime NOT NULL default '1000-01-01 00:00:00'`

👍

**Comment by RussH** [comment]
@Bloafer thanks for closing this one down
