### ISSUE TITLE
How to add extra TAB or Menu in Opencats

### ISSUE THREAD

**Issue by prasathmscss** [opencats/OpenCATS#323]
Actually, it not working Russh.. could you please Send step by step process to Add TAB or Menu in Opencats

Please screenshot, or step by step to Add Extra TAB in Opencats

**Comment by RussH** [comment]
Dup

**Comment by prasathmscss** [comment]
Like below comment, I need Explanation RussH. For Extra Tab adding

I have added the names of the tabs I want to be hidden to the printTabs method in the TemplateUtility.php class on line 602 like so

if (empty($tabText) || $tabText === 'Companies' || $tabText === 'Job Orders' || $tabText === 'Activities')
{
continue;
}

Originally the line was:

if (empty($tabText))
{
continue;
}

and I only added the modules I didn't want visible.

**Comment by skrchnavy** [comment]
@RussH  provided in #317 link to http://opencats-documentation.readthedocs.io/en/latest/shortdevguide.html where is short overview how to write module.
The change you did just ignored displaying modules in menu, but you have to create module to be 'autoloaded' into menu.
