### ISSUE TITLE
Remainder alert in Calendar

### ISSUE THREAD

**Issue by prasathmscss** [opencats/OpenCATS#324]
How to set a reminder alert in the opencats calendar.

**Comment by RussH** [comment]
Hi @cptr13 I'm afraid when I checked the new documentation I couldn't see the section on setting up cronjobs to send reminders. Can you find the correct place in the documentation sub-site please?

**Comment by prasathmscss** [comment]
Is there any possible way to set up Calendar remainder in Opencats

**Comment by skrchnavy** [comment]
issue opencats/OpenCATS_Documentation#11 created, this can be closed

**Comment by cptr13** [comment]
*coughs*....I don't know anything about them :)  

I'll have to research and circle back

**Comment by prasathmscss** [comment]
circle back ASAP  @cptr13

**Comment by RussH** [comment]
@cptr13 
here's the section from the original documentation..

     2) Scheduled E-Mail reminders
        OpenCATS can send out E-Mail reminders for calendar events before they happen.
        To enable this feature, configure cron or another scheduling daemon to
        invoke QueueCLI.php every minute.  An example crontab line would look like:

            * * * * * /usr/local/bin/php /var/www/html/opencats/QueueCLI.php

        Or,

            * * * * * curl http://mysite.com/QueueCLI.php > /dev/null
