### ISSUE TITLE
"Upload" button is not active on Career Portal URL (local XAMPP install)

### ISSUE THREAD

**Issue by OpenCATS080917** [opencats/OpenCATS#325]
cptr13 said "open an issue on our GitHub" so here I am...

### Expected behavior and actual behavior:

I would expect the "Upload" button to be active and not to be greyed out. The "Browse" button works, allowing me to select a CV 

### Steps to reproduce the problem.

Install v0.9.4 (see config below); create companies/jobs, and activate local Career Portal. Open URL. I see "Current Available Openings, Recently Posted Jobs: x". Click on a job and then on "Apply to Position" button. Enter your e-mail address and click on "Continue to Application". (NB: The "Enter your e-mail address" can be left empty, which may be a clue to the problem)

### What version of opencats are you running?

 opencats-0.9.4.tar.gz
- Windows 10 Family version (French) 64 bits
- Firefox 55.0.3 (64-bit) and, just to check, Microsoft Edge 40.15063.0.0
- XAMPP v5
- Installed in C:\xampp\htdocs\OpenCATS

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed:

none

**Comment by RussH** [comment]
Hi, this seems to be a windows issue - it's been reported previously only ever on the Windows platform. Please check apache error logs (which surely must exist).. Can you ensure that the webserver has write permissions to the upload directory?

**Comment by OpenCATS080917** [comment]
1) Here are the Apache error logs

[Wed Sep 20 14:06:12.589627 2017] [ssl:warn] [pid 11584:tid 596] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Sep 20 14:06:12.734232 2017] [core:warn] [pid 11584:tid 596] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Wed Sep 20 14:06:13.012970 2017] [ssl:warn] [pid 11584:tid 596] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Sep 20 14:06:13.514370 2017] [mpm_winnt:notice] [pid 11584:tid 596] AH00455: Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/5.6.31 configured -- resuming normal operations
[Wed Sep 20 14:06:13.514370 2017] [mpm_winnt:notice] [pid 11584:tid 596] AH00456: Apache Lounge VC11 Server built: Jun 18 2017 13:03:53
[Wed Sep 20 14:06:13.514370 2017] [core:notice] [pid 11584:tid 596] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Wed Sep 20 14:06:13.552142 2017] [mpm_winnt:notice] [pid 11584:tid 596] AH00418: Parent: Created child process 2752
[Wed Sep 20 14:06:15.448088 2017] [ssl:warn] [pid 2752:tid 540] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Sep 20 14:06:15.909552 2017] [ssl:warn] [pid 2752:tid 540] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Sep 20 14:06:16.011151 2017] [mpm_winnt:notice] [pid 2752:tid 540] AH00354: Child: Starting 150 worker threads.

2) How do I check that the webserver has write permissions to the upload directory?

**Comment by RussH** [comment]
on linux I'd check the permissions of the upload directory to ensure that whatever account runs the webserver has write permissions to the upload directory. 

if you **chmod 755 /your/path/to/upload** then it should suffice

**Comment by OpenCATS080917** [comment]
Thanks Russ
