### ISSUE TITLE
getting Notice with blank page during login 

### ISSUE THREAD

**Issue by GaneshKandu** [opencats/OpenCATS#327]
### Expected behavior
should login after fresh installation using default user and pass ie. admin/admin
### actual behavior.
Getting this Notice
Notice: Use of undefined constant LOGIN_PENDING_APPROVAL - assumed 'LOGIN_PENDING_APPROVAL' in lib/Session.php on line 778

### Steps to reproduce the problem.
install OpenCATS and login with default credential admin/admin 

### What version of opencats are you running? WAMP or LAMP? 
LAMP
### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.

Notice: Use of undefined constant LOGIN_PENDING_APPROVAL - assumed 'LOGIN_PENDING_APPROVAL' in /home/soft/public_html/manual/OpenCATS/lib/Session.php on line 778

Warning: Cannot modify header information - headers already sent by (output started at /home/soft/public_html/manual/OpenCATS/lib/Session.php:778) in /home/soft/public_html/manual/OpenCATS/lib/CATSUtility.php on line 275

[log.txt](https://github.com/opencats/OpenCATS/files/1332853/log.txt)
[error_log.txt](https://github.com/opencats/OpenCATS/files/1332854/error_log.txt)

**Comment by cptr13** [comment]
Install environment?  OS and version?  Local, server, or shared hosting?

Did you follow the install instructions and videos?

What version of OpenCATS did you install?

**Comment by GaneshKandu** [comment]
- CentOS Local Server (VM)
- [http://opencats-documentation.readthedocs.io/en/latest/install-windows.html#set-up-opencats](http://opencats-documentation.readthedocs.io/en/latest/install-windows.html#set-up-opencats)
- opencats 0.9.4 full

**Comment by cptr13** [comment]
Try this: https://github.com/opencats/OpenCATS/issues/308

**Comment by GaneshKandu** [comment]
Thanks Working 👍
