### ISSUE TITLE
MySQL Query Failed: Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cats_dev.candidate_joborder_submitted.candidate_joborder_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#329]
I installed open cats succesfully but am getting this error, "MySQL Query Failed: Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cats_dev.candidate_joborder_submitted.candidate_joborder_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
" can anyone please help me out.

**Comment by pradeep51** [comment]
![screenshot 68](https://user-images.githubusercontent.com/28918414/31605868-1f677e0c-b285-11e7-9063-33ba6dd222f8.png)

**Comment by RussH** [comment]
Hi - what version of opencats and MySQL  are you running?

**Comment by pradeep51** [comment]
Hello sir,  now it's working fine!  But am facing trouble that am unbele to
send the email to candidates

**Comment by RussH** [comment]
Hi. Good to hear!
Can you clarify - are you seeing the option to email and it's not working, or you don't get the option?
If it's the former then it's regarding your  email configuration in config.php
If it's the latter then it's likely an ACL configuration issue - see https://github.com/opencats/OpenCATS/wiki/Access-Control-Lists

**Comment by pradeep51** [comment]
Hello. Russ H i didn't get that email option. Please help me out.

**Comment by skrchnavy** [comment]
isn't issue #321 also your case?

**Comment by pradeep51** [comment]
Hello. Sveto Krchnavy i didn't get that email option. Please help me out.

**Comment by pradeep51** [comment]
Hey Russ H, I want to create an New Registration From, With Existing Data Base, Am not going to use symfony  framework. can i build new registration page using core PHP???

**Comment by RussH** [comment]
Hiya. Can you discuss in the opencats slack channel rather than extend this issue? Email me RussH at opencats.org and I'll send you an invite. Will closer this query issue now.. can you try to keep one issue on topic, makes it easier to manage.

**Comment by CTIGB** [comment]
@pradeep51 how did you get it working? I have the same issue

**Comment by gihanchathuranga** [comment]
I also have this problem;
I installed open cats succesfully but am getting this error, "MySQL Query Failed: Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cats_dev.candidate_joborder_submitted.candidate_joborder_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
" can anyone please help me out.

opencats-0.9.4 and MySQL  5.7.28  running

**Comment by RussH** [comment]
HI,

MySQL changed their default - google is your friend. See here
https://www.percona.com/blog/2019/05/13/solve-query-failures-regarding-only_full_group_by-sql-mode/


----
Russ

**Comment by shantadam** [comment]
I’d like to jump-in and propose a possible solution that worked for me, as such:

  *   While considering migration, I never recommend to modify MySQL configuration directly in the core app.
  *   Access your server with SSH > ssh <user>@<ipaddress>
  *   Find out where possibly MySQL config file is located > mysql --help | grep “my.cnf”
  *   If my.cnf is found under /etc then access the file and edit it > vi /etc/my.cnf
  *   Define SQL_Mode property in my.cnf under [mysqld] >
sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
  *   Restart MySQL server on your system.

IMPORTANT NOTICE: I’d like to state that even though my above proposed sql_mode parameter value options may suffice for my practice standards, you don’t have to take them literally. I recommend referring to the extended list of options described in the following page link and see if there are other options that you’d like to set too: https://dev.mysql.com/doc/refman/5.7/en/mysql-server.html . Thank you.

Regards,
Shant Adam,
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.
