### ISSUE TITLE
Travis fails to build - missing Docker package. Replacement package available.

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#335]
Docker build-log extract below - can you advise what needs to be changed in the config to pickup the replacement package?

> 0.35s$ sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
> 
> Reading package lists... Done
> 
> Building dependency tree       
> 
> Reading state information... Done
> 
> Package docker-engine is not available, but is referred to by another package.
> 
> This may mean that the package is missing, has been obsoleted, or
> 
> is only available from another source
> 
> However the following packages replace it:
> 
>   docker-ce
> 
> E: Package 'docker-engine' has no installation candidate
> 
> The command "sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine" failed and exited with 100 during .
> 
> Your build has been stopped.

**Comment by skrchnavy** [comment]
Docker changed naming of packages from docker-engine to docker-ce (and docker-ee)
This was fixed in master. I can see your branch release/0.9.4 crashed but it was created from an older commit.

You shall switch to master, then cherry pick the change you made. Or merge master to your branch.

**Comment by skrchnavy** [comment]
fixed in #291
