### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by chaitu24** [opencats/OpenCATS#336]

**Comment by chaitu24** [comment]
I have followed http://opencats-documentation.readthedocs.io/en/latest/Install-SharedHosting.html 
but I am getting 500 internal error. Gave right permissions and remove .htaccess.

**Comment by cptr13** [comment]
Who is the webhost?

**Comment by shaanfreny** [comment]
I have the same issue, my webhost is Crazy Domain.

Thanks in advance.

Bhaskar Dasgupta
shaanfreny@gmail.com

**Comment by chaitu24** [comment]
Resolved:
The issue with webhost. Ewebguru sucks.

**Comment by yogeshnmakwana** [comment]
> Resolved:
> The issue with web host. Ewebguru sucks.

Hello Chaitu, I am having the same issues with the web host.

Please share the details about solutions, I will apply the same,

Thanks,
Yogesh M
