### ISSUE TITLE
XSS vulnerability on OpenCATS

### ISSUE THREAD

**Issue by NaveenDA** [opencats/OpenCATS#341]
I am edit contact name details on demo site, while i am adding xss content to it and i find OpenCATS
![image](https://user-images.githubusercontent.com/20555082/33263313-5d2c7488-d38f-11e7-8b42-2d3e4470f8c5.png)
Here is the Proff.
![image](https://user-images.githubusercontent.com/20555082/33263557-4f69a266-d390-11e7-8d41-d3b6da28dd45.png)

**Comment by RussH** [comment]
@NaveenDA can you reproduce this on one of the front-end pages? I'd expect all the backend forms (such as your example here) to be accessible only to authorised users.. not publicly accessible .

**Comment by NaveenDA** [comment]
i will

**Comment by RussH** [comment]
Hi Naveen, looking for the front-end demonstration please?

**Comment by RussH** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
