### ISSUE TITLE
How do i do Email authentication for career page after submitting Application?

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#342]
@RussH @mlespiau @skrchnavy @opencats  Below pic. shows that there is a button for  submit application.  if i click on that submit application button. it will send the mail for the applied candidate with out email authentication. if i want to do email authentication for each candidate what should i need to do? 
![screenshot 94](https://user-images.githubusercontent.com/28918414/33470296-7d4ceaa8-d68d-11e7-981b-d4a2ee45ba76.png)

**Comment by RussH** [comment]
Hi @pradeep51 I'm not sure what you mean by with email authentication. If you first want to verify candidates are 'alive' at their submitted email address, and verify it via some email and response -  then that's not in the current workflow.
