### ISSUE TITLE
General Email Configuration! am getting Error.

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#345]
An error occurred.

Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in D:\xampp\htdocs\OpenCATS\lib\phpmailer\class.smtp.php on line 369
-2 Errors occurred while attempting to send mail to one or more provided addresses: *******************@gmail.com (): SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by RussH** [comment]
Hi @pradeep51 if you check the troubleshooting link in the error message, you see the specific section explaining when you'll get that error and how to resolve it;
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure

**Comment by vikash-del** [comment]
Hi,
   When i am trying to do email configuration i am getting some errors can anyone help me to solve this.
<img width="398" alt="error" src="https://user-images.githubusercontent.com/61985764/147042333-7e3742f4-b852-4dd0-bf92-01e5f98ea7f7.PNG">

**Comment by shantadam** [comment]
Hi Vikash,

I’m assuming it has to do with SMTP server access issue. Probably you might’ve skipped/misconfigured the SMTP server and access credentials in the <opencatsfolder>/config.php file?

  *   Navigate to OpenCATS project folder.
  *   Open config.php file with your text editor.
  *   Search for SMTP
  *   Update the parameters, as shown in the file:
define('MAIL_SMTP_HOST', "localhost");
define('MAIL_SMTP_PORT', 587);
define('MAIL_SMTP_AUTH', true);
define('MAIL_SMTP_USER', "user");
define('MAIL_SMTP_PASS', "password");
define('MAIL_SMTP_SECURE', "tls");

If you have done the above steps correctly and still issue is unresolved, can you please help us understand better by elaborating the steps you’ve taken prior to attempting to send an email. Thank you.

Regards,
Shant Adam

From: vikash-del ***@***.***>
Date: Tuesday, December 21, 2021 at 9:50 PM
To: opencats/OpenCATS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [opencats/OpenCATS] General Email Configuration! am getting Error. (#345)

Hi,
When i am trying to do email configuration i am getting some errors can anyone help me to solve this.
[error]<https://user-images.githubusercontent.com/61985764/147042333-7e3742f4-b852-4dd0-bf92-01e5f98ea7f7.PNG>
