### ISSUE TITLE
Allow  retrieval of forgotten passwords through email.  where it is working?

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#346]
when user was forgotten their password. how did they can create their new password?
here i got an option of Allow  `retrieval of forgotten passwords through email` if click on that check box nothing is working. and also i checked any forgot password link or button like that in login page but i cannot see anything in login page.  please help me out. thanks in advance.

![screenshot 98](https://user-images.githubusercontent.com/28918414/34201764-8fdb2a0a-e59b-11e7-9f8d-a7d65526d5ae.png)

**Comment by pradeep51** [comment]
I  am using 0.94 version of Open CATS. 
if click on that `retrieval of forgotten passwords through email`  Check box nothing is working @RussH

**Comment by RussH** [comment]
Closing as duplicate of #50
