### ISSUE TITLE
HTTP Error 500 When Adding a Candidate

### ISSUE THREAD

**Issue by robhob** [opencats/OpenCATS#349]
[phpinfo.pdf](https://github.com/opencats/OpenCATS/files/1689438/phpinfo.pdf)
### Expected behaviour and actual behaviour.
Ability to add a new candidate, HTTP Error 500 instead.

### Steps to reproduce the problem.
Click on **Add Candidate** link on **Candidates** tab.

### What version of OpenCATS are you running? Server Config?
[0.9.4 'Countach' maintenance release v1](https://github.com/opencats/OpenCATS/releases/tag/0.9.4-2) 
CentOS 7
Apache/2.4.29
PHP 5.6.26
The server API is CGI/FastCGI.
memory_limit = 512M (see attached)

### Attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.

> PHP Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 27668915 bytes) in /home/recruitm/public_html/lib/Template.php on line 116

Other than this problem, OpenCATS works perfectly.

**Comment by RussH** [comment]
Hey Rob, 

can you check these resolved issues that seem similar please?

https://github.com/opencats/OpenCATS/issues/160
https://github.com/opencats/OpenCATS/issues/130#issuecomment-254228495

Otherwise, I'll see if I can reproduce it on a clean install

**Comment by RussH** [comment]
Hi Rob, you have the composer.json file but not composer? Therefore to install composer, follow the following;

You must download composer:  **curl -sS https://getcomposer.org/installer \| php**  

and next you should run if you have composer.json file:  **composer.phar install**

**Comment by robhob** [comment]
I've followed you instructions (modified: _composer.phar install_ to _php composer.phar install_) but am still getting the error when trying to add a candidate.
![opencats cmd](https://user-images.githubusercontent.com/11555285/35737717-230b8110-0835-11e8-8335-2d1668c17e76.png)

**Comment by RussH** [comment]
@skrchnavy  looks to be different from previous similar issues - can you take a look please?

**Comment by skrchnavy** [comment]
If OpenCATS is installed from package attached to the release (opencats-0.9.4-2-full.tar.gz or opencats-0.9.4-2-full.zip), composer is not necessary (all is bundled there).

Based on line from log it looks a problem with a setting in php, can't allocate memory.

I found this article: https://www.airpair.com/php/fatal-error-allowed-memory-size so could be helpful.

The size of page looks too big, so could be a memory leak there.

**Comment by robhob** [comment]
Woohoo! I've managed to get around the problem by adding the following line to the Template.php file (/lib/Template.php)
`ini_set('memory_limit', '512M'); // or you could use 1G`

Now, clicking on the Add Candidate link opens the page without an error. 

The problem I have now is that, after adding the new candidate's information, when I hit the Add Candidate button at the bottom of the page I get the following error.

```
Query Error -- Report to System Administrator ASAP


MySQL Query Failed: Data too long for column 'name' at row 1

INSERT INTO candidate_source (
                            name,
                            site_id,
                            date_created
                         )
                         VALUES (
                            '\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"',
                            1,
                            NOW()
                         )
```

Shall I open a new issue or can you help me on this thread?

**Comment by robhob** [comment]
Okay, I 've discovered that the table cadidate_source has a ton of rubbish data starting at the 37th row. This row is blank but every row after that has the quotes symbol, each row has one more than the previous. There are 4599 rows in this table at the moment. Deleting all these rows has fixed the problem. Not sure why it's doing this though (why is it creating these records).
![cadidate_source table data](https://user-images.githubusercontent.com/11555285/36090511-51e4cc2e-0fe9-11e8-813a-80d01efd3737.png)
