### ISSUE TITLE
how to change date option to datetime while adding new field in opencats

### ISSUE THREAD

**Issue by NikhilBhilare** [opencats/OpenCATS#350]
When i was trying to add daytime column from csv file to extra field which was declared as datetime it was not taking date into consideration as obvious.can anyone tell me how to convert date to datetime while adding extra field in administration

**Comment by RussH** [comment]
Hi @NikhilBhilare can you confirm if this is still an active issue please?

**Comment by RussH** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
