### ISSUE TITLE
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\wamp64\www\CATS\lib\phpmailer\class.smtp.php on line 369

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#352]
Is there Anybody knows how to reslove it.

**Comment by skrchnavy** [comment]
Please check https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure

(or also discussion  https://github.com/PHPMailer/PHPMailer/issues/368)

**Comment by ebentil** [comment]
You can skip verification of the ssl certificate by using the below:

```
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
```

**Comment by RussH** [comment]
Closed https://documentation.opencats.org/how-tos/emails-and-reminders
