### ISSUE TITLE
Feature Request...Tracking the resume source..e.g. Dice or Indeed etc.

### ISSUE THREAD

**Issue by peerats** [opencats/OpenCATS#359]
We post jobs on Dice, Indeed, Career Builder etc. and we are planning to use the "Apply URL" functionality that is available on these job boards so when the user clicks on the Apply button on the posting, the user will land on the "Applying to: Position Title" page on our Opencats' Careers website. The user will click on Browse and upload the resume, fill the required fields and submit the resume for that particular position. We normally post the same position on all the job boards and is there a way to track in OpenCats where the resume came from? E.g. Did it come from DICE or Indeed etc.?

Matter of fact, it is a requirement from Indeed.com that we have a tracking capability with in our ATS for them to enable the Apply URL functionality. They are asking us to provide a "Tracking Token".

**Comment by RussH** [comment]
Hi @peerats tracking tokens are not a feature within the xml feed. You may want to fund this feature http://forums.opencats.org/viewforum.php?f=12 ..please contribute any changes back to opencats
