### ISSUE TITLE
PHP Error while doing full site backup on 0.9.2

### ISSUE THREAD

**Issue by scott1981** [opencats/OpenCATS#36]
When I try to generate a full site backup in cat 0.9.2 I get a PHP error.

Steps to reproduce:
1. Login as Admin
2. Go to Settings
3. Click on Administration
4. Click on Site Backup
5. Click on Full system backup.

A popup message like this comes up:

http://es.tinypic.com/r/35hjo06/8

Also these two errors appear on the browser at the top:

Strict Standards: Non-static method FileUtility::sizeToHuman() should not be called statically, assuming $this from incompatible context in /path/to/ats.test/modules/settings/SettingsUI.php on line 1980

Warning: filesize(): stat failed for attachments/site_180/1xxx/9dcdf5c645f1fd4c52452c4e0f876c4d//catsbackup.bak in /path/to/ats.test/modules/settings/SettingsUI.php on line 1981

General Information
Operating System:   Linux ice.weblocalhost.com 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64
Operating System Type:  CATS thinks your operating system is UNIX.
PHP Version:    5.5.23
Database Version:   MySQL 5.5.42-cll

**Comment by amaisonneuve** [comment]
I corrected this issues and it will get pulled in the next version.

**Comment by amaisonneuve** [comment]
Will do.

**Comment by Deibukyu** [comment]
Hi All

It looks like I'm experiencing the same issue as the OP.

Both issues exist from:

Existing Server (where 0.9.1 is operating properly)
OS: Windows Server 2008 R2
Using Wampserver
PHP: 5.2.2
MySQL: 5.5.24

[05-Jan-2016 14:08:30] PHP Warning:  filesize() [<a href='function.filesize'>function.filesize</a>]: stat failed for attachments/site_180/0xxx/1f1ecd8e53e6f833aa77db345b2b97ba//catsbackup.bak in C:\wamp\www\tempcats\modules\settings\SettingsUI.php on line 1981

[05-Jan-2016 14:08:32] PHP Warning:  gzopen(./temp/ea055d9c06b5ee1a3d2ba94f9bf224439) [<a href='function.gzopen'>function.gzopen</a>]: failed to open stream: No such file or directory in C:\wamp\www\tempcats\lib\FileCompressor.php on line 668
 
Test Server
OS: Windows Server 2012 R2
Using Wampserver
PHP: 5.5.12
MySQL: 5.6.17

Warning: filesize(): stat failed for attachments/site_180/0xxx/3b3244a895d09a2b152b0ab33797bca1//catsbackup.bak in C:\wamp\www\tempcats\modules\settings\SettingsUI.php on line 1981
Call Stack
Time Memory Function Location
1 0.0005 305728 {main}( ) ..\index.php:0
2 0.0392 6588952 ModuleUtility::loadModule( ) ..\index.php:302
3 0.0395 6599016 SettingsUI->handleRequest( ) ..\ModuleUtility.php:79
4 0.0395 6599792 SettingsUI->createBackup( ) ..\SettingsUI.php:363
5 0.0400 6608752 filesize ( ) ..\SettingsUI.php:1981

**Comment by amaisonneuve** [comment]
I'll take a look at the change i did and get back to you, sorry for the
delay.
