### ISSUE TITLE
CATS ERROR: on changing the PHP version to PHP 7.0

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#360]
Hi RussH and Opencats Team,

I am using opencats 0.9.3

I am using some other applications for which I need to run PHP 7.0
since I have changed the php version I get this error on accessing the ATS... Can you please help?
"CATS Error: All required PHP extensions are not loaded"

**Comment by fadupla** [comment]
Hi @KamalJoshiDelhi 

I didn't test running in a PHP 7.0 environment yet but seems like this error pops out when either the functions 'mysql_connect' or 'session_start' doesn't exist.
Did you check with a phpinfo() if these extensions were well installed and activated ?

**Comment by KamalJoshiDelhi** [comment]
mysql_connect is not supported in PHP 7.0

**Comment by RussH** [comment]
Hi all, 

PHP v7.0 is not supported by opencats. There are some 'early days' PR's to move to PHPv7 support, but it's not there now.
