### ISSUE TITLE
Require Resume Upload

### ISSUE THREAD

**Issue by ronswift2** [opencats/OpenCATS#363]
I need to require applicants to upload a resume to complete the applicant process. How do I do that. I am self hosting on Ubuntu 16.04 server.

**Comment by RussH** [comment]
Hi Ron, 
you'd need ot make some changes here https://github.com/opencats/OpenCATS/blob/master/modules/careers/CareersUI.php
to ensure that an application with no attachment (or a saved resume in the system) returns an error.

**Comment by ronswift2** [comment]
Can you please give an example of what to change. 
I see the required and validator sections but not sure what to add there. 
Thanks 

Ron Swift 
President 
410-788-7011 
------------------------- 
Celebrating 30 years in business, 1989 - Present 
"Staffing, IT Services, Biometric Time-clock and Web Development" 
Certified Minority Business Enterprise by the State of MD (MDOT) and Baltimore City

**Comment by RussH** [comment]
you can see a sample of what's needed here..
https://stackoverflow.com/questions/17649479/making-file-input-element-mandatory-required

**Comment by ronswift2** [comment]
Thanks 


Ron Swift 
President 
410-788-7011 
------------------------- 
Celebrating 30 years in business, 1989 - Present 
"Staffing, IT Services, Biometric Time-clock and Web Development" 
Certified Minority Business Enterprise by the State of MD (MDOT) and Baltimore City

**Comment by ronswift2** [comment]
We have struggled with fixing this in your code. 
What would you charge to fix it for us. 
We need to require a resume file is included with every application. 
Thanks 

Ron Swift 
President 
410-788-7011 
------------------------- 
Celebrating 30 years in business, 1989 - Present 
"Staffing, IT Services, Biometric Time-clock and Web Development" 
Certified Minority Business Enterprise by the State of MD (MDOT) and Baltimore City

**Comment by bromine355** [comment]
What have you tried? Just update this function:

private function _makeApplyValidator($template)

Something like this maybe (not tested)

```
if (strpos($template['Content'], '<input-file>') !== false || strpos($template['Content'], '<input-file req>') !== false)
        {
            $validator .= '
                if (document.getElementById(\'file\').value == \'\')
                {
                    alert(\'Please upload your resume.\');
                    document.getElementById(\'file\').focus();
                    return false;
                }';
        }
```

**Comment by ronswift2** [comment]
I applied the code that you suggested and it still allows persons to apply without a resume. 
Please advise, thanks. 

Ron Swift 
President 
410-788-7011 
------------------------- 
Celebrating 30 years in business, 1989 - Present 
"Staffing, IT Services, Biometric Time-clock and Web Development" 
Certified Minority Business Enterprise by the State of MD (MDOT) and Baltimore City

**Comment by bromine355** [comment]
Try this:

```
if (strpos($template['Content'], '<input-resumeUploadPreview>') !== false)
        {
            $validator .= '
                if (document.getElementById(\'file\').value == \'\')
                {
                    alert(\'Please upload your resume.\');
                    document.getElementById(\'file\').focus();
                    return false;
                }';
        }
```

I had to check what was actually in the template. The templates are in the database in career_portal_template and career_portal_site_template.

It looks like the careers portal page was set up to be configurable which is nice, but having the templates in the database have been more of a con than a pro in my opinion.

**Comment by RussH** [comment]
Hi @ronswift2 can you confirm if the information provided by @bromine355 resolved your question?

**Comment by RussH** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by arvindjkhr** [comment]
Hello @ronswift2  and @bromine355 Below code is working for resume upload

Finally running code is as below.


 if (strpos($template['Content'], '<input-resumeUpload>') !== false || strpos($template['Content'], '<input-resumeUpload req>') !== false)
        {
            $validator .= '
                if (document.getElementById(\'resume\').value == \'\')
                {
                    alert(\'Please enter a first name.\');
                    document.getElementById(\'resume\').focus();
                    return false;
                }';
        }






and if you want to use upload and paras the resume please use below.

if (strpos($template['Content'], '<input-resumeUploadPreview>') !== false)
        {
            $validator .= '
                if (document.getElementById(\'file\').value == \'\')
                {
                    alert(\'Please upload your resume.\');
                    document.getElementById(\'file\').focus();
                    return false;
                }';
        }

**Comment by Rami-Gaber** [comment]
Thanks alot @arvindjkhr 

Below instructions worked perfectly.

    if (strpos($template['Content'], '<input-resumeUploadPreview>') !== false)
    {
        $validator .= '
            if (document.getElementById(\'file\').value == \'\')
            {
                alert(\'Please upload your resume.\');
                document.getElementById(\'file\').focus();
                return false;
            }';
    }

**Comment by johnuzojr** [comment]
Where do I place this code please?

> Try this:
> 
> ```
> if (strpos($template['Content'], '<input-resumeUploadPreview>') !== false)
>         {
>             $validator .= '
>                 if (document.getElementById(\'file\').value == \'\')
>                 {
>                     alert(\'Please upload your resume.\');
>                     document.getElementById(\'file\').focus();
>                     return false;
>                 }';
>         }
> ```
> 
> I had to check what was actually in the template. The templates are in the database in career_portal_template and career_portal_site_template.
> 
> It looks like the careers portal page was set up to be configurable which is nice, but having the templates in the database have been more of a con than a pro in my opinion.

**Comment by RussH** [comment]
Hiya, please amend the function below;
https://i.imgur.com/iGXpRi3.png

**Comment by johnuzojr** [comment]
@RussH I found the file and this worked perfectly!
