### ISSUE TITLE
Veteran Status (Male?)

### ISSUE THREAD

**Issue by bromine355** [opencats/OpenCATS#364]
I didn't realize being male qualified as a veteran status. :)

![image](https://user-images.githubusercontent.com/22333977/40736928-3c28e7ee-63f4-11e8-994d-764898d9cbe3.png)

/modules/careers/CareersUI.php

![image](https://user-images.githubusercontent.com/22333977/40736874-08b64b2c-63f4-11e8-9b2f-6ac09181c212.png)

I assume this should be modified to say "No". Super easy fix.

**Comment by RussH** [comment]
Sorry @bromine355 can't reproduce, works as expected at demo.opencats.org

**Comment by bromine355** [comment]
Hi Russ. Thanks for all your help on this project. I have deployed OpenCats at work and it's been awesome so far. So much cheaper than ICIMs too. :)

The demo doesn't have the eeo fields on the careers page by default. The app have  defined templates fields like <eeo-ethnicity>. When I included those in templates things started acting weird.

**Comment by RussH** [comment]
Hi Brian.. it's not enabled by default, but I just logged into the demo as an admin and enabled in the administration menu  - please check it out and ensure it's working as per your expectations! Am glad you're finding it useful!
