### ISSUE TITLE
Unable to do mass import

### ISSUE THREAD

**Issue by arunwebber** [opencats/OpenCATS#365]
### Expected behavior 
No idea
### Actual behavior 
I am trying to upload the CV from the mass import folder of the upload directory
Screenshots are attached
![selection_002](https://user-images.githubusercontent.com/29517954/42020719-562dedd0-7ad6-11e8-800f-c5ad45d60d17.png)
![selection_003](https://user-images.githubusercontent.com/29517954/42020737-63362cd6-7ad6-11e8-9b95-44f834f2ac11.png)

### Steps to reproduce the problem.
I just downloaded open cats from this directory and tried uploading the CV
### What version of opencats are you running? WAMP or LAMP? 
LAMP

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
sh: 1: \path\to\pdftotext: not found

**Comment by bromine355** [comment]
![image](https://user-images.githubusercontent.com/22333977/42343190-1f7ce4b8-804d-11e8-8410-6931b7c0e83a.png)

Check the config file.

**Comment by RussH** [comment]
Hi @arunwebber can you confirm if @bromine355 response resolves your issue?

**Comment by arunwebber** [comment]
Yes that is the answer but i have done it in linux machine i dont know how the command lines will work in windows machine if some one is using it

**Comment by RussH** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by arunwebber** [comment]
@RussH Hi there This issue was fixed for me @bromine355 s comment is right fit for us.

Best,

**Comment by RussH** [comment]
@arunwebber thank you very much!
