### ISSUE TITLE
Status emails are going to spam folder

### ISSUE THREAD

**Issue by arunwebber** [opencats/OpenCATS#368]
### Expected behavior and actual behavior.
Make the auto-generated mail to the inbox. But when we generate status changed mail it is directly going to junk folder.

![selection_009](https://user-images.githubusercontent.com/29517954/42757770-cf6641a6-891e-11e8-8eab-42133283a727.png)

### What version of opencast are you running? WAMP or LAMP? 
LAMP

**Comment by RussH** [comment]
Hi, 

this is a typical problem for automatically generated emails. You have a few options;
- remove the asterisks and CAPS from the first line. This looks very spammy. 

Once you have contents that that you like run it through an email spamminess tester - like https://www.mail-tester.com/ 
http://www.isnotspam.com/
http://www.spamanalyse.com/

and tweak it until it gets a lower score. Alternatively - if this is your own mail system flagging it as spam, then just whitelist it.
