### ISSUE TITLE
How do you change statuses?

### ISSUE THREAD

**Issue by meatballcoder** [opencats/OpenCATS#374]
Are the statuses done at the db level or is there a frontend way to do it?

Edit:  Same with Activity Type.  DB only?

**Comment by bromine355** [comment]
I believe just database. But be carefull when updating lookup tables. I found that alot of the drop down list values are hard coded so updating the database tables is not always enough. For example: 

![image](https://user-images.githubusercontent.com/22333977/45056327-719bc280-b047-11e8-8fc6-30f3e6e57e14.png)

**Comment by skrchnavy** [comment]
See this PR: #236 where is change to be able to maintain list of job order statuses.

**Comment by meatballcoder** [comment]
I saw that after I posted.  Was that something left over from the original fork, or is there a design reason for it?  Something that needs refactoring?

**Comment by RussH** [comment]
Hi @meatballcoder that's a PR waiting to be rolled into the release. There are a few stacked up - they've passed CI but I'm testing locally before adding to the develop branch. If you want to test some, start at the bottom of the list https://github.com/opencats/OpenCATS/pulls
