### ISSUE TITLE
What is License_Key for?

### ISSUE THREAD

**Issue by meatballcoder** [opencats/OpenCATS#376]
config.php has this,

define('LICENSE_KEY','

What is this for?

**Comment by RussH** [comment]
Hi there - this dates to the fork from CATS to OpenCATS. Before the original Dvevelopers closed the source to make a SAAS product, they looked to have a Community vs Professional version.. mainly, it permitted users to access a hosted resume parsing service that they operated. That service is defunct, and license key checks are irrelevant within the codebase... and being stripped out when code is updated.
