### ISSUE TITLE
The problem of Setting up CandidATS in Synology NAS

### ISSUE THREAD

**Issue by ichris007** [opencats/OpenCATS#377]
#### Release or downloaded from Git? 
Version: candidats-CandidATS-2.0.0-Stable, download from SourceForge.net
#### WAMP or LAMP? 
Synology NAS 213j with Apache HTTP Server 2.4, PHP 7.0, MariaDB 10, phpMyAdmin
### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.

I have set Database Name, Database User, Database Password, Database Host, and follow up the installwizard,

Step 1: System Check
The test result is All tests passed successfully!

but ,

Step 2: Database Connectivity
there is a error:

Test ResultsPDOException: SQLSTATE[HY000] [2002] No such file or directory in /volume1/web/candidats/lib/ClsNaanalPDO.php:44 Stack trace: #0 /volume1/web/candidats/lib/ClsNaanalPDO.php(44): PDO->__construct('mysql:host=loca...', 'candidats', NULL) #1 /volume1/web/candidats/lib/ClsNaanalPDO.php(484): ClsNaanalPDO->__construct('localhost', 'candidats', NULL, 'candidats', 'mysql') #2 /volume1/web/candidats/lib/DatabaseConnectionPDO.php(98): ClsNaanalPDO::getNamedInstance('cats', 'candidats', 'candidats', NULL, 'mysql', 'localhost') #3 /volume1/web/candidats/lib/DatabaseConnectionPDO.php(45): DatabaseConnection->connect() #4 /volume1/web/candidats/lib/InstallationTests.php(334): DatabaseConnection::getInstance() #5 /volume1/web/candidats/modules/install/ajax/ui.php(254): InstallationTests::checkMySQL('localhost', 'candidats', '', 'candidats') #6 /volume1/web/candidats/ajax.php(122): include('/volume1/web/ca...') #7 {main}

Could you tell me how to resolve it? 
Thanks!

BTW, I'm not a IT engineer, don't know any coding.

**Comment by RussH** [comment]
Hey @ichris007 , CandidATS is a different project.. sorry!

**Comment by ichris007** [comment]
@RussH sorry, I made a mistake.
