### ISSUE TITLE
Canadian Postal Codes

### ISSUE THREAD

**Issue by amaisonneuve** [opencats/OpenCATS#38]
Is there value in adding canadian postal codes to the zipcode table?

I have the full list.

**Comment by RussH** [comment]
I don't have a postcode/zipcode db available for the UK - so what use is it? Does it provide distance matching for candidates?

**Comment by amaisonneuve** [comment]
sourcing a UK dB of postal codes is pretty easy.  need one?

**Comment by RussH** [comment]
Sure - just trying to find the value - as I've not used a postal code db
previously

**Comment by amaisonneuve** [comment]
OK excellent i will add it.

**Comment by RussH** [comment]
Alain,

looking forward - I suspect we can bin the whole zipcode db and move ot a
google maps lookup?

Such as this?
http://www.hashbangcode.com/blog/find-longitude-and-latitude-postcode-or-zipcode-using-google-maps-and-php
(assuming it's not out of date)



----
Russ

**Comment by RussH** [comment]
Actually - can you drop me an email describing where in the app you use this functionality? Just trying to see if the zipcode.php replacement works with google maps lookup. But as I've never used this functionality, I can't see where you "enter a zipcode and find near candidates?" or is the functionality slightly different?

**Comment by amaisonneuve** [comment]
The functionality is on the 'Edit' Candidates page. there are a few
enhancements i'm working on for that page.

In terms of the candidate 'Search' thats actually not a bad idea. and
wouldn't be to difficult to build.

**Comment by RussH** [comment]
I only asked on 'distance from jobs to candidates' as I see there is
commented out code in ziplookup.php to calculate distance for candidates -
but there's no functionality in the app to actually use it. I guess it was
planned functionality..



----
Russ

**Comment by RussH** [comment]
I have the code added for worldwide zipcode (postcode) lookup via Google, i.e.;
http://maps.googleapis.com/maps/api/geocode/xml?sensor=false&address=G612RW

However it returns the information in XML. I'm just working through the SimpleXML elements that're required to extract the useful info and replace the 'zipcode database' for USA only.

**Comment by amaisonneuve** [comment]
Oh fantastic,  much better solution

**Comment by RussH** [comment]
Okay, so if you go to http://demo.opencats.org/index.php?m=candidates&a=add
and use a zipcode / postcode it should now populate the address, city &
state.

Will assemble into a pull request.



----
Russ

**Comment by RussH** [comment]
upon checking - it looks like Google uses different labels in its XML
response for Address / City/State in different countries.

My test (for the UK) http://maps.googleapis.com/maps/api/geocode/xml?sensor=
false&address=G612RW

The lookup functions to return the '*route*' as street address, the '
*postal_town*' as the City, and '*administrative_area_level_2*' for state.

For USA it's slightly different. If I try http://maps.googleapis.com/
maps/api/geocode/xml?sensor=false&address=37403

The '*locality*' field is Chattanooga, and * administrative_area_level_2*
is Hamilton County. There's also '*administrative_area_level_1*' which is
Tennessee - therefore unless we have a separate lookup table based upon the
returned country from the Google XML response  it may be simpler to
document that folks may need to make manual amendments to the lookup to
return the different field appropriate for their country.

A lookup table based upon the XML country to decide which fields to return
would be the ideal solution & would also accommodate opencats installations
which are recruiting in foreign countries - but that can be an enhancement
for the future. It's beyond my scope!




----
Russ

**Comment by amaisonneuve** [comment]
I'm not sure I follow, why would you want to read the <type>? The only address components that should be considered would be the <long_name> for each component, no?

**Comment by RussH** [comment]
Hi Alain, yes we have to select on **type**  and return the associated **long_name**. The issue appears to be that for different countries, we may want to return different *type* fields for city & state; 
In the UK, 
I'd use a **type** of {(locality) OR (post_town)} for city, and;
use  a **type** of  {administrative_area_level_2} for state.
