### ISSUE TITLE
Change default field name

### ISSUE THREAD

**Issue by EktaPro** [opencats/OpenCATS#383]
Hi,
Can anyone guide me how can i customize code to change default filed name??

Expected behavior : 
In job order table I want to change field name 'Owner' to 'Sourcer'.

opencats version : opencats-0.9.4-2 install from Release

PHP version : 5.6.37

Attachment :
![issue](https://user-images.githubusercontent.com/42994840/46079860-f5b01880-c1b5-11e8-95db-52c1ad2d9c37.PNG)

**Comment by wjcheers** [comment]
lib/JobOrder.php
in class: class JobOrdersDataGrid extends DataGrid
'Owner' =>         array('select'   => 'owner_user.first_name AS ownerFirstName,' .
change to 
'Sourcer' =>         array('select'   => 'owner_user.first_name AS ownerFirstName,' .

modules\joborders\dataGrids.php
in function joborderSavedListByViewDataGrid and JobOrdersListByViewDataGrid
array('name' => 'Owner', 'width' => 55),
change to
array('name' => 'Sourcer', 'width' => 55),

**Comment by EktaPro** [comment]
Hi wjcheers,
after changing this, Owner column disappears from datagrid. :( 

Currently I have used javascript to change column name on page load
 $(document).ready(function() {
  $("body").children().each(function () {
    $(this).html( $(this).html().replace(/Owner/g,"Sourcer") );
  });
});

**Comment by wjcheers** [comment]
![1](https://user-images.githubusercontent.com/11549391/46135250-52273c80-c277-11e8-88fb-ecc80d45b6ae.png)
You need to reset to default columns.

**Comment by EktaPro** [comment]
Thanks wjcheers
