### ISSUE TITLE
Problem with installation - antiword, pdftotext, html2text and unrtf executable binaries does not exist

### ISSUE THREAD

**Issue by shantadam** [opencats/OpenCATS#386]
### Expected behavior and actual behavior.
OpenCATS installation's step 4 should pass, as such:
- It should locate, find and execute antiword binary at the user's specified system directory path.
- It should locate, find and execute pdftotext binday at the user's specified system directory path.
- It should locate, find and execute html2text at the user's specified system directory path.
- It should locate, find and execute unrtf at the user's specified system directory path.

### Steps to reproduce the problem.
- Download the master version zip file.
- Extract , setup and configure the host directory.
- Point your browser to the host site.
- Start the installation process.
- Step through step 1, 2 and 3.
- Define step 4's antiword, pdftotext, html2text and unrtf binary file's paths.
- Run the step 4's test by clicking "Test Configuration" button.

### What version of opencats are you running? 
- Master version

#### Release or downloaded from Git? 
- Yes

#### WAMP or LAMP? 
- LAMP

### What version of PHP and MySQL are you running
- PHP 5.3.3 (CLI)
- MySQL 14.14 Distrib 5.1.73

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
- NOTE: Activate php.ini => display_errors = On
- Restart Apache service.
[php error output]
Warning: is_executable(): open_basedir restriction in effect. File(/usr/bin/antiword) is not within the allowed path(s): (/var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com:/var/sentora/temp/) in /var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com/lib/InstallationTests.php on line 522 Warning: file_exists(): open_basedir restriction in effect. File(/usr/bin/antiword) is not within the allowed path(s): (/var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com:/var/sentora/temp/) in /var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com/lib/InstallationTests.php on line 524 Warning: is_executable(): open_basedir restriction in effect. File(/usr/bin/pdftotext) is not within the allowed path(s): (/var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com:/var/sentora/temp/) in /var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com/lib/InstallationTests.php on line 572 Warning: file_exists(): open_basedir restriction in effect. File(/usr/bin/pdftotext) is not within the allowed path(s): (/var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com:/var/sentora/temp/) in /var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com/lib/InstallationTests.php on line 574 Warning: is_executable(): open_basedir restriction in effect. File(/usr/bin/html2text) is not within the allowed path(s): (/var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com:/var/sentora/temp/) in /var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com/lib/InstallationTests.php on line 622 Warning: file_exists(): open_basedir restriction in effect. File(/usr/bin/html2text) is not within the allowed path(s): (/var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com:/var/sentora/temp/) in /var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com/lib/InstallationTests.php on line 624
<img width="809" alt="screen shot 2018-10-06 at 8 58 41 am" src="https://user-images.githubusercontent.com/3911765/46571816-dc436500-c949-11e8-8ec0-fe18e35cc63d.png">

**Comment by cptr13** [comment]
What's your hosting environment?

**Comment by shantadam** [comment]
- CentOS release 6.10 (Final)
- MySQL 14.14 Distrib 5.1.73
- PHP 5.3.3 (cli)

**Comment by cptr13** [comment]
OK. But you're self hosting? On a laptop or server, not a shared hosting
environment like go daddy?

**Comment by cptr13** [comment]
Did you install the resume indexing tools?

Install resume indexing tools
$ sudo wget ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/Kenzy:/modified:/C7/CentOS_7/x86_64/antiword-0.37-20.1.x86_64.rpm
$ sudo rpm -ivh antiword-0.37-20.1.x86_64.rpm
$ sudo wget http://dl.fedoraproject.org/pub/epel/7/x86_64/h/html2text-1.3.2a-14.el7.x86_64.rpm
$ sudo rpm -ivh html2text-1.3.2a-14.el7.x86_64.rpm
$ sudo yum install poppler poppler-utils unrtf
If you want to remove the files after you have installed them then do: * $ sudo rm antiword-0.37-20.1.x86_64.rpm html2text-1.3.2a-14.el7.x86_64.rpm

**Comment by RussH** [comment]
Php 5.3.3 isn't a supported version, and you seem to have some unusual configuration in PHP as the errors aren't letting you search in /usr

.. So fix both of them, install the parsing tools and try again!

**Comment by shantadam** [comment]
State I'm running-in:
- I have full access to my hosted Dynadot VPS.
- All four (4) executable binaries are in my operating system installed under /usr/bin.

**Comment by shantadam** [comment]
I went ahead and updated my php to 5.6.

**Comment by shantadam** [comment]
Resolution:
- Gave execution rights to Sentora panel's directory and the binary executable directory, as such:
- Modified my Apache httpd-vhosts.conf file to configure open_basedir for my host directory under Sentora.
- The following is the sample extract:
<Directory "/var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com">
  Options +FollowSymLinks -Indexes
  AllowOverride All
  Order Allow,Deny
  Allow from all
 php_admin_value open_basedir /var/sentora/hostdata/zadmin/public_html/cats_tmknoble_com/:/usr/bin
</Directory>

**Comment by shantadam** [comment]
Specifying PHP's open_basedir under Apache's httpd-vhost.conf worked. 
<img width="814" alt="screen shot 2018-10-06 at 12 17 15 pm" src="https://user-images.githubusercontent.com/3911765/46573341-cfcb0680-c961-11e8-9b64-1f8823c93f1b.png">

**Comment by shantadam** [comment]
My observations:
- Code logic is not verifying if user can execute defined binaries within the directory path under the existing php configuration.

My suggestions:
- I recommend adding code logic that allows configuration of php's open_basedir parameter runtime, which is allowed, something along the lines like:
```
ini_set( 'open_basedir', implode( PATH_SEPARATOR, array( __DIR__, '/usr/bin' ) ) );
```

**Comment by shantadam** [comment]
Furthermore, I noticed that documentation is missing installation instructions to ask users: 
(This is for Linux users.)
- install [Composer](https://getcomposer.org/), as such:
```
cd /tmp
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
```
- Move to OpenCATS directory and run:
```
composer install
```

**Comment by RussH** [comment]
Hi @shamtadam, composer is only required if you don't download the full package from the release. If you don't use the full release package and download 'source' or download directly from the GitHub repo then you will need to run composer.

Full (no composer needed)
https://github.com/opencats/OpenCATS/releases/download/0.9.4-2/opencats-0.9.4-2-full.zip

Source(for docker, requires composer)
https://github.com/opencats/OpenCATS/archive/0.9.4-2.zip

**Comment by RussH** [comment]
Glad you resolved the issue by fixing your permissions issue
