### ISSUE TITLE
Advanced Filter/Search feature request

### ISSUE THREAD

**Issue by dvirilan** [opencats/OpenCATS#387]
### Expected behavior and actual behavior.
Today the Filter is showing all fields BUT on lists (Enums) it does not display the values to choose from, this may be a bug BUT it is not my feature request (I would like to see enums searched by option selection in my feature request).

I would like to have a simple yet "Advanced Filter" where one can re-use the current search form inside a "Must have" or "May have" sections, which represent the AND and OR in a query.
A search like that could be visualized as:

Must have:
     Key Skills : programmer
     Key Skills : PHP
     Key Skills : SQL (or space/comma separated) 
May have:
     City : NYC
     Can Relocate : True

I initially posted this as a "search", but "filter" is much more is use by me, (classic "lost in translation")
### What version of opencats are you running? 
CATS Version 0.9.4 Countach
#### Release or downloaded from Git? 
release
#### WAMP or LAMP? 
wamp

**Comment by dvirilan** [comment]
This should be an easy feature since the code shows that you can use keywords 'AND, OR, NOT' in order to basically achieve half of what I was looking for, I wish I knew PHP in order to submit such a fix

But as a tip to all: use the "AND", "OR" & "NOT" keywords to get more of the filter 
example: first name is equal to _Anna_ **OR** _Bob_ will bring all Anna's and Bob's out there :)

**Comment by RussH** [comment]
uncompleted / will not be added
