### ISSUE TITLE
Strict standards: Only variables should be passed by reference in D:\wamp\www\cats\lib\DataGrid.php on line 1714

### ISSUE THREAD

**Issue by Rakkeshs** [opencats/OpenCATS#39]
This is what i get after i the installation. Please help

Error: "Strict standards: Only variables should be passed by reference in D:\wamp\www\cats\lib\DataGrid.php on line 1714"

**Comment by RussH** [comment]
Hi, this is resolved in 0.9.2 (the current version). Alternatively, disable
strict standards in your PHP configuration.

**Comment by Rakkeshs** [comment]
Thanks for the response but I am little confused of this 0.9.2 version. can you plz send me the link.

**Comment by RussH** [comment]
https://github.com/opencats/OpenCATS/archive/master.zip

**Comment by Rakkeshs** [comment]
Hi,

 After updating this file I am unable to connect to database and ended up in this error “Failed to select database 'cats_dev'.” Also adding the screenshot for the same. Plz help

 



 

Regards,

Sre Rakkesh .S
