### ISSUE TITLE
Naming convention: Placed vs Hired

### ISSUE THREAD

**Issue by geniusupgrader** [opencats/OpenCATS#391]
### Expected behavior and actual behavior.

Actual behavior: In the job order pipeline the „last position“ is `placed`. But in the Dashboard it is `Hires`.

Expected behavior: I would like to see the same naming convention, in the application and the source code. For this I would propose `hired`, instead of `placed`.

### What version of opencats are you running? 
CATS Version 0.9.4-2

#### Release or downloaded from Git? 
Normal Release: 0.9.4 'Countach' maintenance release v1

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
MariaDb: 10.1-36-1
PHP Version 5.6.38

**Comment by RussH** [comment]
Typically the terms used are Placed and Placements.
