### ISSUE TITLE
Date - Make it changeable

### ISSUE THREAD

**Issue by geniusupgrader** [opencats/OpenCATS#393]
### Expected behavior and actual behavior.
I would expect to change the dates (**Create Date, Modified Date**) from all Activities and Status Changes, as well as from Job Order, Companies, Lists, Contacts and so on. Because sometimes you want to supplement or add an entry at a later/earlier date.

### What version of opencats are you running? 
CATS Version 0.9.4 Countach.

#### Release or downloaded from Git? 
Normal 0.9.4 Countach Release.

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
MariaDb: 10.1-36-1
PHP Version 5.6.38

**Comment by geniusupgrader** [comment]
Workaround: Change the dates directly inside the database, with a database administration tool, like DBeaver. Do this only at your own risk. And this approach is quite exhausting, because there may be  multiple tables, where you want to set the same date (because of the design of OpenCATS, which creates a new table for everything)

**Comment by RussH** [comment]
date created and modified date are intentionally the date of creation and modification and are not intended  to be modified after the fact.. unless as you say you have admin access to MySQL backend.
