### ISSUE TITLE
Edit Action on multiple entries

### ISSUE THREAD

**Issue by geniusupgrader** [opencats/OpenCATS#394]
### Expected behavior and actual behavior.
I would suppose to change multiple entries and their properties at the same time with the checkboxes on the left and the Action button. But this does not seem like it is the case. You can only add them to lists?. 

For example: I want to change the City property from multiple Job Orders at the same time to the same value. Is this already possible?

### What version of opencats are you running? 
CATS Version 0.9.4 Countach.

#### Release or downloaded from Git? 
Normal 0.9.4 Countach Release.

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
MariaDb: 10.1-36-1
PHP Version 5.6.38

**Comment by RussH** [comment]
This feature won;t be added due to lack of developers - but you can code it and contribute back to the project.
