### ISSUE TITLE
Feature request: Own Activities

### ISSUE THREAD

**Issue by geniusupgrader** [opencats/OpenCATS#395]
### Expected behavior and actual behavior.

We have now these types of activities (which can be logged):

- Call
- Email
- Meeting
- Other
- Call (Talked)
- Call (LWM)
- Call (Missed)

I would propose that one can define own activity types. For example when one company is hiring throuh skype, then there should be a skype activity, which can be entered manually.
This should not be that difficult to implement, or are these type of activities connected with other functionality?

### What version of opencats are you running? 
CATS Version 0.9.4 Countach.

#### Release or downloaded from Git? 
Normal 0.9.4 Countach Release.

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
MariaDb: 10.1-36-1
PHP Version 5.6.38

**Comment by RussH** [comment]
you can add in your own types with minimal effort. However there are no customisable types within the app envisaged right now.
