### ISSUE TITLE
Persistant Rows per page setting

### ISSUE THREAD

**Issue by geniusupgrader** [opencats/OpenCATS#396]
### Expected behavior and actual behavior.
I would like to a preference setting for the rows per page option. So it is persistant.

### What version of opencats are you running? 

CATS Version 0.9.4 Countach.
Normal 0.9.4 Countach Release.

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
MariaDb: 10.1-36-1
PHP Version 5.6.38

**Comment by RussH** [comment]
see config.php, line 100

**Comment by geniusupgrader** [comment]
Unfortunately not every page (like activities page) does have this setting.
