### ISSUE TITLE
HTML Emails - 0.9.2

### ISSUE THREAD

**Issue by dveos** [opencats/OpenCATS#40]
Unable to send HTML emails using CKEditor in 0.9.2, I receive following error: http://s22.postimg.org/sk9nar869/Error1.png then standard email body is displayed. 

Also, cannot action send email using "selected" button only "all".

**Comment by skrchnavy** [comment]
@RussH isn't this solved in PR #132?

**Comment by RussH** [comment]
Confirmed as solved. Can successfully send on my installation - Please reopen if your issue persists after upgrading to 0.9.3
