### ISSUE TITLE
Activities Page Action not working

### ISSUE THREAD

**Issue by EktaPro** [opencats/OpenCATS#403]
### Expected behavior and actual behavior.
In Activities page, there should be checkbox in 1st column, for action purpose.
But checkbox are not shown in 1st column. Action is not working properly.

### What version of opencats are you running? 
opencats-0.9.4-2 install from Release

#### Release or downloaded from Git? 
From Release

### What version of PHP and MySQL are you running
PHP version : 5.6.37

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
![image](https://user-images.githubusercontent.com/42994840/49562314-fe089a80-f940-11e8-9fd5-73c8aaea0dbe.png)

**Comment by RussH** [comment]
Hi, this has been the behaviour since 0.9.1 (oldest version I can check). I suspect it's included in activities as part of the default template, but not used because we don't actually want to have actions available on this page - which are available on candidates, contacts, lists. Do you have an actual requirement for this or you're just flagging it as an inconsistency?

**Comment by EktaPro** [comment]
Hi RussH,
I actually want to export the activities as a report, 
I have a great need of actions in this page. Kindly request you to guide me.

**Comment by EktaPro** [comment]
Hey Russh, 
Can you guide me? or suggest me what can I do??

**Comment by RussH** [comment]
Okay, 
two things. Firstly the 'nice' approach would be to re-implement the activities options. Unfortunately this would take some time and there's not a huge demand for it. However I have similar 'reporting' queries that just run as a cron job, they'll extract info and email it out on a regular basis without intervention. So if you can design the SQL query you want, just amend the bash script below;

`check-active-joborders.sh 
#!/bin/bash
# Proper header for a Bash script.

# Send summary of open Jobs with no updates in the past week
mysql -u dbuser -p cats --password=xxxxxxxx << QUERY_INPUT

#sql commands go here
USE cats;

SELECT
        cats.joborder.joborder_id AS Job,
        cats.joborder.status,
        cats.user.user_name AS Recruiter,
        cats.company.name,
        cats.joborder.title AS Job_Title,
        DATE_FORMAT( cats.joborder.date_created , '%M %D, %Y' ) AS "Creation_Date",
        DATEDIFF( NOW( ) , cats.activity.date_modified ) AS "Days_since_touched",
        cats.contact.first_name,
        cats.contact.last_name,
        LEFT( cats.activity.notes , 30 ) AS "Latest_Notes_Summary"
FROM
        cats.user
        INNER JOIN cats.joborder
         ON cats.user.user_id = cats.joborder.recruiter
        RIGHT OUTER JOIN cats.activity
         ON cats.joborder.joborder_id = cats.activity.joborder_id
        INNER JOIN cats.company
         ON cats.joborder.company_id = cats.company.company_id
        INNER JOIN cats.contact
         ON cats.joborder.company_id = cats.contact.company_id
WHERE
        cats.joborder.status = "Active"
GROUP BY
        cats.joborder.joborder_id
ORDER BY
        cats.user.user_name ASC INTO OUTFILE '/tmp/active-joborders.csv'
                FIELDS TERMINATED BY '|'
                ENCLOSED BY '"'
                LINES TERMINATED BY '\n';

QUERY_INPUT

# convert to XLSX
csv2xlsx -infile "/tmp/active-joborders.csv" -outfile "/tmp/active-joborders.xlsx" 

# Email the results to recipients    

echo "FOR YOUR ACTION: Please review." | mail -s "ACTION REQUIRED:All active joborders" -a /tmp/active-joborders.xlsx email@recipient.com email2@recipient.com 

# clean-up the tmp file or MYSQL won't over-write
rm /tmp/active-joborders.csv
rm /tmp/active-joborders.xlsx
`
