### ISSUE TITLE
Resume Indexing Configuration Issues

### ISSUE THREAD

**Issue by zoomiest2** [opencats/OpenCATS#404]
### Expected behavior and actual behavior.
On installation getting all red lights. System not recognizing locations of resume indexing tools.

### What version of opencats are you running? 
0.9.4-2

#### WAMP or LAMP? 
LAMP on AWS Lightsail

### What version of PHP and MySQL are you running
MySQL: 5.7.24-0ubuntu.18.04.1
PHP: 5.6.38-3+ubuntu18.04.1+deb.sury.org+1

So, as I read up on other solutions, I notice that on AWS Lightsail VPS (where I am hosting), they don't provide access to httpd-vhosts.conf, or httpd.conf

When I go to comment out open_basedir in the php.ini, I find that its not even set.

So, do I need another host?
Is there another way to address this?

**Comment by RussH** [comment]
Hi @zoomiest2 I've not used lightsail before but looks like a vps. Shouldn't be any issue at-all with using this. I run the opencats demo site on a digitalocean droplet which must be very similar. If you're not tied to AWS then try digitalocean - otherwise let me know and  I'll spin up a free trial AWS instance and see why it gets stuck.

**Comment by RussH** [comment]
I assume you HAVE installed the resume indexing tools?!

**Comment by zoomiest2** [comment]
Update:
I installed OpenCats on a completely different host and again, could not find any of the files mentioned in [the article](https://techjourney.net/php-scripts-open_basedir-restriction-in-effect-error/) referenced for open_basedir issues (vhost.conf and vhost_ssl.conf). 

I am using 

> grep -r "vhost.conf"

 and also 

> find -name vhost.conf

 with wildcards...

Are you guys talking about apache virtual hosts? (they didn't work for me)

> /etc/apache2/sites-available/000-default.conf

**_Environment:_**

- Yes, I have installed the resume parsing utilities (antiword, unrtf, html2text, etc.)
- Ubuntu 16.04.5 LTS
- PHP Version 5.6.38-3+ubuntu16.04.1+deb.sury.org+1

Any pointers would be fantastic...

**Comment by zoomiest2** [comment]
Is there any OS (debian, ubuntu, red hat, etc.) that is known to not have these problems? At this point, I can install OpenCATS on anything...

**Comment by RussH** [comment]
Hey Allan, not sure about this issue. I would complete the installer, then simply ensure that the path in config.php points correctly to the tool. I know that Amazon EC3 is reported to work just fine - and I can confirm that a digitalocean droplet works fine, too. If you have a particular target that's not working let me know and I'll see if I can reproduce the problem.

**Comment by zoomiest2** [comment]
Thanks.
I closed off that host account and went over to DigitalOcean. But I have
not completed the install yet.

Stay tuned.

**Comment by RussH** [comment]
whew!
