### ISSUE TITLE
Exchange/Outlook Calendar Sync

### ISSUE THREAD

**Issue by tomytiet** [opencats/OpenCATS#405]
Hello dear team,

I'm loving your software and it has been a great help to our company.

One thing that would make it perfect would be Exchange Calendar Sync so that we don't have to enter a meeting twice.

Is that feature possible? I saw the possibility of creating an ical file but it doesn't update real time.

**Comment by RussH** [comment]
Hey @tomytiet just to be clear, @dveos developed the iCal feed  ;-)

As he says though you can set the polling frequency for how often the feed is checked.
