### ISSUE TITLE
XSS Vulnerabilities: Careers Portal

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#406]
a scan of the careers portal for demo.opencats.org shows;

Summary
Overall risk level: HIGH
Risk ratings:High:	
Medium: 1
Vulnerable Page	Vulnerable Parameter	Method	Attack Vector	
/careers/index.php	email	POST	http://demo.opencats.org/careers/index.php?ID=56&m=careers&p=applyToJob
POST Data:  email="><script>alert(1);</script>	
/careers/index.php	lastName	POST	http://demo.opencats.org/careers/index.php?ID=56&m=careers&p=applyToJob
POST Data:  lastName="><script>alert(1);</script>	
/careers/index.php	zip	POST	http://demo.opencats.org/careers/index.php?ID=56&m=careers&p=applyToJob
POST Data:  zip="><script>alert(1);</script>	

XSS Mitigation needs to be investigated

**Comment by RussH** [comment]
Mitigation: enable HttpOnly Cookie; https://geekflare.com/httponly-secure-cookie-apache/
(Note: See also https://www.garron.me/en/bits/enable-mod-headers-apache-2.html)

Also need to look at input field validation.

**Comment by RussH** [comment]
Looks like this can be added to /lib/UserInterface.php line 384;
return trim(htmlspecialchars ($request[$key]), ENT_QUOTES)

**Comment by Rami-Gaber** [comment]
I enabled  mod headers module on Apache 2, however when I added 
return trim(htmlspecialchars ($request[$key]), ENT_QUOTES) to line number 384, I get "This page isn’t working" HTTP ERROR 500 on chrome for all pages. When I remove that line things get back to normal.

**Comment by RussH** [comment]
I've enabled HTMLspecialchars but not htmlonly cookies and it works on the demo site. Can you try?

**Comment by Rami-Gaber** [comment]
I am sorry but I dont know how to enable that.

**Comment by dcdefioreREISS** [comment]
> Looks like this can be added to /lib/UserInterface.php line 384;
> `return trim(htmlspecialchars ($request[$key]), ENT_QUOTES)`
> 
> Already changed on demo.opencats.org... I will make a PR and see if all the unit tests pass.



Russ,

Just wanted to say that this caused some issues with my install.

It seemed to strip HTML from any field, and that lead to problems.

IE. If a user put an & in a field, it would turn to ;amp on save.

**Comment by RussH** [comment]
Thanks for the feedback - I understand that it should change and ampersand to ;amp.. but what's the issue with a list?

**Comment by dcdefioreREISS** [comment]
Click on "Edit" Candidate -> "Sources"
It keeps duplicating the "Sources" list on save and keeps adding additional length to it (https://i.imgur.com/TYhoRdI.png). Leading to some DB errors as well due to length of the field.

And this is what I'm talking about on the ;amp/& issue https://i.imgur.com/2i8nnt3.png - see current employer.

**Comment by RussH** [comment]
ahh yes - it's replacing the brackets so we could replace (none) with none and there wouldn't be a problem. So not as simple as first thought. We could still use htmlspecialchars to strip from input, but then recreate them using htmlspecialchars_decode before they're displayed. Damn! Ahh well that'll have to wait

**Comment by RussH** [comment]
Okay, so we duplicate the library, retain the htmlspecialcharacters feature and call it ExternalUserInterface.php. Only call ExternalUerInterface.php on the public-facing external portal.

**Comment by dcdefioreREISS** [comment]
> Okay, so we duplicate the library, retain the htmlspecialcharacters feature and call it ExternalUserInterface.php. Only call ExternalUerInterface.php on the public-facing external portal.

I just realized, that for some reason, this is Truncating the number '3' if it is at the beginning of a field.

So I have this in my 'CareersUI.php'
`$zip            = $this->getSanitizedInput('zip', $_POST);`

And this in my 'UserInterface.php'
```
protected function getSanitizedInput($key, $request)
    {
        if (isset($request[$key]))
        {
        return trim(htmlspecialchars ($request[$key]), ENT_QUOTES);
	}
        return '';
    }
```

Many of my zip codes and phone numbers begin with '3' - so if a candidate enters their ZIP code as 32708, it's actually stored in the DB as 2708. If they enter their zip code as 33333, nothing is stored, and if they enter 33433, then 433 is stored.

If I revert back to the 'getTrimmedInput' , the '3' does no get truncated. Any ideas?


Dominic

**Comment by Bloafer** [comment]
The bracket is in the wrong place:
```
return trim(htmlspecialchars ($request[$key]), ENT_QUOTES);
```
Should be 
```
return trim(htmlspecialchars($request[$key], ENT_QUOTES));
```

**Comment by RussH** [comment]
That'll be the problem then.. thanks @Bloafer
