### ISSUE TITLE
PHP Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by BentCoder** [opencats/OpenCATS#408]
Hi,

Would please someone tell me what the exact problem here please? It is hard to tackle the issue pointed out in the image below.

Kind regards

![screen shot 2019-01-04 at 11 24 55](https://user-images.githubusercontent.com/8837278/50735747-8b8f1280-11ab-11e9-98dd-b519a2550910.png)

### What version of opencats are you running? 
OpenCATS-opencats-0.9.3

#### Release or downloaded from Git?
Forked (downloaded and installed on a shared hosting)

#### WAMP or LAMP?
LAMP

### What version of PHP and MySQL are you running
MySQL version: MySQL 5.6
PHP version: PHP 7.2

**Comment by RussH** [comment]
I assume it's a PHP compatibility issue? 

See here https://stackoverflow.com/questions/15735099/fatal-error-using-this-when-not-in-object-context-in

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BentCoder** [comment]
I think it is to do with [this issue](https://github.com/opencats/OpenCATS/issues/411).

**Comment by rongten** [comment]
> I assume it's a PHP compatibility issue?
> 
> See here https://stackoverflow.com/questions/15735099/fatal-error-using-this-when-not-in-object-context-in
> 
> Sent with [GitHawk](http://githawk.com)

Hello, I have a similar issue trying with php 7.2 on a ubuntu bionic lts. 

it seems the 
`public function getDepartmentIDByName($departmentName, $companyID, $db)`

function in lib/Contacts.php behaves strangely in 7.2.

I had to change lines 788 and 790 putting $this in place of $sql to be able to add a contact, but when I am adding a job order I need to change the lines back to the original value.

Something to do with class vs function definition in php 7.2.. I do not chew php so I cannot help more.

**Comment by rongten** [comment]
I forgot to say I am using the test-php-7.x branch.

**Comment by arunwebber** [comment]
This is the problem with this function
public function getDepartmentIDByName($departmentName, $companyID, $db)
```
    {
        /* (none) always has an ID of 0. */
        if ($departmentName === '(none)')
        {
            return 0;
        }

        $sql = sprintf(
            "SELECT
                company_department_id AS departmentID
             FROM
                company_department
             WHERE
                name = %s
             AND
                company_id = %s
             AND
                site_id = %s",
             $this->_db->makeQueryString($departmentName),
             $companyID,
             $this->_siteID
        );
        $rs = $db->getAssoc($sql);

        if (empty($rs))
        {
            return 0;
        }

        return $rs['departmentID'];
    }
```
Over here https://github.com/opencats/OpenCATS/blob/96e1db325f7e7a504132aed37a86e1e3eab96677/lib/Contacts.php#L788
In this line changing 

`this->_db to $db`
Will work from the question 
https://stackoverflow.com/questions/56348310/using-this-when-not-in-object-context-php-fatal-error
