### ISSUE TITLE
Make CSV exports in UTF-8 readable for Excel

### ISSUE THREAD

**Issue by pes-soft** [opencats/OpenCATS#41]
When OpenCATS exports CSV file and content is in UTF-8, special characters are not properly imported to Excel, because Excel cannot identify that CSV file has UTF-8 encoding. By adding UTF-8 BOM to the beginning of the file, Excel will recognize this correctly.

I've been able to test it by adding `echo chr(239) . chr(187) . chr(191)` after headers within _lib/DataGrid.php_ in function _drawCSV_.

For backward compatibility, this feature/fix could be also enabled/disabled by configuration variable.

**Comment by RussH** [comment]
Hi, do you have any recommended code you can contribute to rectify this?

**Comment by RussH** [comment]
Resolved by commit 41 by @wjcheers
