### ISSUE TITLE
Candidates Mysql error

### ISSUE THREAD

**Issue by JacquesLeJacques** [opencats/OpenCATS#413]
Hello,

I've installed Opencats (0.9.4-2) on a shared hosting:

Operating System: | Linux sharedserver13.host-stage-dns.com 3.10.0-714.10.2.lve1.4.74.el7.x86_64 #1 SMP Wed Oct 11 15:51:10 EDT 2017 x86_64
-- | --
Operating System Type: | CATS thinks your operating system is UNIX.
PHP Version: | 5.6.39
Database Version: | MySQL 5.7.24

But I have some Mysql errors, like:
MySQL Query Failed: Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'hmsxznnz_kronostartkcats.candidate_joborder_submitted.candidate_joborder_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT SQL_CALC_FOUND_ROWS 

For candidates pages, when I try to add some users or when I try to activate the career portal. 

Could I get some help with that? 

Thank you in advance!

**Comment by RussH** [comment]
HIya, 

see here;
https://stackoverflow.com/questions/23921117/disable-only-full-group-by

**Comment by JacquesLeJacques** [comment]
Hi,

Unfortunately the databases are on a shared hosting, I don't have superadmin privileges on phpmyadmin.
I tried the two solutions and in variables > SQL mode - there is no Only full group by

Any idea?

**Comment by RussH** [comment]
Sorry - can you try at the CLI for MySQL? https://tableplus.io/blog/2018/08/mysql-how-to-turn-off-only-full-group-by.html
