### ISSUE TITLE
Veteran misspelled in two spots

### ISSUE THREAD

**Issue by loganripplinger** [opencats/OpenCATS#414]
### Expected behavior and actual behavior.
"Veteran" should be spelled correctly on modules/settings/EEOEOCSettings.tpl and modules/candidates/Edit.tpl

It is currently spelled, "Vetran"

### Steps to reproduce the problem.
N/A

### What version of opencats are you running? 
0.9.4

#### Release or downloaded from Git? 
Release. It is currently not fixed in the github repo, https://github.com/opencats/OpenCATS/search?q=vetran&unscoped_q=vetran

#### WAMP or LAMP? 
N/A

### What version of PHP and MySQL are you running
N/A

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
N/A

**Comment by RussH** [comment]
corrected  in the develop branch
