### ISSUE TITLE
Decoding of UTF-8 characters mangles Calendar entries

### ISSUE THREAD

**Issue by pes-soft** [opencats/OpenCATS#42]
When there are special characters ( non-latin ) used in Calendar entries ( as Calendar entry title or name of the person involved ), these entries are not decoded from event strings correctly by JavaScript and are displayed mangles ( as UTF-8 string in ASCII ).

To fix this behaviour, it is required to replace `unescape` with `decodeURIComponent` within *modules/calendar/Calendar.js* in function *calendarDataPopulateString*.

**Comment by skrchnavy** [comment]
PR #84 shall fix this issue
