### ISSUE TITLE
This page is not working, when i try to add job/company or any other activities

### ISSUE THREAD

**Issue by focusagain** [opencats/OpenCATS#421]

**Comment by RussH** [comment]
Please fill in the minimum questions when submitting an issue

**Comment by focusagain** [comment]
after installing i am able to login and see the page but unable to do any activities like adding company, adding candidates, adding jobs and changing status.  please find the attached screen record.
i am using latest version

[ScreenCapture_3-7-2019 2.50.59 PM.zip](https://github.com/opencats/OpenCATS/files/3000102/ScreenCapture_3-7-2019.2.50.59.PM.zip)

**Comment by RussH** [comment]
Hi, you are using the latest version? You've downloaded this from Master on github, or this is one of the releases? 

Sounds as though you haven't downloaded 'full' you've downloaded the standard docker image and therefore need to run composer to get the dependencies installed. 

1. install composer from getcomposer.org
2. run `composer install` in the webroot of opencats.

**Comment by focusagain** [comment]
yes am using latest version. i have downloaded from github.
i dont know how to solve this issue please help me out

**Comment by focusagain** [comment]
can i have your email id? or phone number so that we can have teamviewer

**Comment by RussH** [comment]
I'm sorry I can't install this for you - but if you install composer and then install the dependencies it'll work.
