### ISSUE TITLE
Users not with Administrative Access should be allowed to view only their contacts information

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#427]
Hi
Is there any way to implement one change in the OpenCATS-0.9.3-1 version...

The logged in user should be taken to his/her contacts only and the check box provided on the right top corner should allow to further show "Only Hot Contacts" out of the logged in user's contacts only. They should not be allowed to view contacts owned by other users till the time they have administrative access...

Only users with the administrative or root access to be taken to all contacts with both the current options on the right hand corner to view "Only My Contacts" and to view "Only Hot Contacts"... If both the buttons are checked then they should be shown only their hot contacts...

With great regards
Kamal Joshi

**Comment by RussH** [comment]
Hi Kamal, the access restrictions added in by @skrchnavy were extensive so I doubt this one feature can be retrofitted. If you upgrade to 0.9.4-2 you should be able to take advantage of them.

**Comment by KamalJoshiDelhi** [comment]
Hi RussH Thanks for your reply to this one... does your upgraded version also cater to php7.0 deprecation issues as well? and also what happens to my candidates database is it the same database that is going to be used? Do you people have any utility to automatically upgrade the site??? I am desperately waiting for this one feature to be incorporated in the ATSystem I am using...

**Comment by KamalJoshiDelhi** [comment]
Hi RussH I upgraded the Opencats to 0.9.4-2 and am not able to set the desired restrictions in that as well... Also in the error log I constantly get reference to some 'vendor/autoupload.php' which I could not find anywhere in the entire file system...

**Comment by dveos** [comment]
Hi can I just add in here,  I don't think the ACL was set up for **object ownership** rather than just for limiting functionalities i.e. emailing / deleting etc. 

However, there is a solution to achieve this. 

1. You can create a new column in user table, maybe something like:- view_own. 
2. Add into lib/session.php a new function, something like getViewOwn, which includes the DB instance, and an sql query to check whether the user is view_own or not. 
3. Then on the Show function of each UI add in something along the lines of if session user is getViewOwn, & the User is not DATA Owner, then permission error! 

Hope this helps someone and I've explained well enough.

**Comment by dveos** [comment]
OH! And most importantly, you would need to add in the same not just to the Show function but the listByView function too (otherwise they will still see all in the datagrid)

**Comment by KamalJoshiDelhi** [comment]
> Hi can I just add in here, I don't think the ACL was set up for **object ownership** rather than just for limiting functionalities i.e. emailing / deleting etc.
> 
> However, there is a solution to achieve this.
> 
> 1. You can create a new column in user table, maybe something like:- view_own.
> 2. Add into lib/session.php a new function, something like getViewOwn, which includes the DB instance, and an sql query to check whether the user is view_own or not.
> 3. Then on the Show function of each UI add in something along the lines of if session user is getViewOwn, & the User is not DATA Owner, then permission error!
> 
> Hope this helps someone and I've explained well enough.

Hey Dveos,
Since I am not a programmer I don't know any of the things you mentioned in each of the steps mentioned above...

Is it possible for you to write what code I need to be add in each of these steps and let me know which file to be updated with that code I guess I would be able to try and implement this...

It is a very important feature for me to implement as no sales team member wants to share their contacts info with other team members...

**Comment by RussH** [comment]
@dveos and @KamalJoshiDelhi  can you guys contact each other and agree a way forwards? I'll close this as it's not an issue against the current codebase.
