### ISSUE TITLE
unable to load php on blue hosting

### ISSUE THREAD

**Issue by RKDevelopment** [opencats/OpenCATS#430]
Your package name OpenCATS/OpenCATS is invalid, it should not contain uppercase characters. We suggest using open-cats/open-cats instead. Make sure you fix this as Composer 2.0 will error.

i am getting the above error and when i am trying my domain then i am getting internal server error

**Comment by RussH** [comment]
this is a warning only for composer 2.0. Not an error

**Comment by shantadam** [comment]
Indeed,

If I may have a say on this subject matter.

In fact, I don’t disagree with @RussH. Simply put, a warning is not a blocker like an error. Earlier this week, I did, as well, had the urge of changing it. But, something else held me back.

In fact, when considering a change you’re ought to consider the extent of the context in which the change will have an impact on. In this case, it will have to propagate up to the upper level repository and all its users.

Consider for a moment the difference between a solo project vs enterprise level. Minor changes that improve functionality on a given project, you can assert a go ahead green-light with ease. Just think of it in terms of migrating all the users to the new major change. What would be the plan? Best to have a strategic and tactical plan.

I see this kind of change as a “major” upgrade with no turning back. Major, as in software versioning (i.e. major.minor.revision). I, also, see it as a major foundational change, like leveraging a development framework -e.g.Laravel or Symfony.

After all, with my reply, I didn’t want to open another can of warms with my later expressed views on a framework. I simply wanted to elaborate on @RussH’s feedback.

Cheers,
--
Shant Adam,
Digital Business Advisor,
Founding Executive Director
—
MXCGI Multispex Consulting Group, Inc.
Shaping & Empowering Digital Economy Ready Businesses, Enterprises & Institutions
—
Toronto Canada Area
Tel.: (647) 287-9726<tel:(647)%20287-9726>
Email: shant.adam@mxcgi.com<mailto:shant.adam@mxcgi.com>
Online: www.mxcgi.com<http://www.mxcgi.com/>
—
Follow MXCGI on
LinkedIn<https://www.linkedin.com/company/mxcgi> / Facebook<https://www.facebook.com/mxcgi> / Twitter<https://www.twitter.com/mxcgi>

On May 10, 2019, at 5:59 AM, RussH <notifications@github.com<mailto:notifications@github.com>> wrote:


this is a warning only for composer 2.0. Not an error

**Comment by RKDevelopment** [comment]
> this is a warning only for composer 2.0. Not an error

thanks I will try again
