### ISSUE TITLE
Logging redirection error

### ISSUE THREAD

**Issue by jtarrico** [opencats/OpenCATS#431]
Hi, 
when logging into my cats session and after adding user/pass (I m admin here) I get redirected to index.php?m=wizard instead of index.php?

I m running on CATS Version 0.9.1 (Beas)

Any ideas on how to solve this? 

Jon

**Comment by RussH** [comment]
Hi Jon, 

if you don't have the INSTALL_BLOCK file present, then opencats will assume it's a new install and redirect you to the install wizard. 0.9.1 is fairly old though?!

**Comment by jtarrico** [comment]
Any clue of where should I be finding this INSTALL_BLOCK and where I need to copy/paste it? Thanks @RussH

**Comment by RussH** [comment]
hi, just create a file in your webroot called INSTALL_BLOCK, so for you probably in /var/www/html/cats/
I'm fairly sure it can be empty, but in my automatically generated one it has the following text;

`This file prevents the installer from running. Remove this file to edit or reset your CATS installation.`

If you're running 0.9.1, you'll probably have to be running php 5.3 as the highest version and no higher?

**Comment by jtarrico** [comment]
Weird, I do have the file and it does have the same text in it. Any other clue? heheh 

Thanks for your patience @RussH

**Comment by RussH** [comment]
Okay, so before we go hacking the code to ignore the install_block, lets check some basics;
- what's your PHP version
-whats your mysql version
- how long have you run the system, and what's changed recently?

what's in the apache error logs when this happens?
