### ISSUE TITLE
Feature Request: Client Portal

### ISSUE THREAD

**Issue by thond1st** [opencats/OpenCATS#432]
Client's own portal and dashboard.
Can only see their applicants and job orders.
They can create their own job order.
They can send invitations for interviews and also set them on the calendar.
They can only see their related calendar activities and other stuff.

If I implement this. Would it be possible and a bit easy and the current data structure is a bit aligned?

**Comment by RussH** [comment]
Hi @thond1st you can change the code however you wish, however it's not something we'd look to merge into our codebase.  I believe the original code was developed with this in mind, however it's not been purused for osme time.
