### ISSUE TITLE
Job orders: Cannot See

### ISSUE THREAD

**Issue by visamp** [opencats/OpenCATS#438]
Once a job order is added by the administrator and assigned to a recruiter, the recruiter cannot see the job orders. Please help.

**Comment by RussH** [comment]
Hi @visamp  I must admit I've never used the Site Administrator account in this way. It's always been an admin account only for me. I'll have to  try and reproduce your error. 

Can you provide the info requested when an issue is created?  opencats version, php version, mysql/mariadb version etc etc, error logs.

**Comment by visamp** [comment]
Hi,

Thanks for getting back to me. Actually, I found the solution. The
sharingaccess table was empty in the database, I populated it with access
permission and bingo, it started working for me. Thanka a lot once again.

Regards,
Vishal.
