### ISSUE TITLE
Getting http error 500 when trying to add a company

### ISSUE THREAD

**Issue by johnuzojr** [opencats/OpenCATS#443]
I'm on opencats 0.9.4. I just installed it. I'm getting an http error 500 when trying to add a company. I have no idea what to do next.

Apache Version | 2.4.41
PHP Version | 7.3.9
MySQL Version | 10.3.17-MariaDB

**Comment by RussH** [comment]
Hi @johnuzojr the current release does not support PHP 7.x, only a maximum PHP 5.6
The php 7.x compatible development version is not released yet. 

Furthermore once installed you need to run composer to pick-up the dependencies!

**Comment by johnuzojr** [comment]
Thanks @RussH ,

Oh no! I'm I in a hole now? Since I have PHP 7.x, what do I do now to salvage the situation? And what is running composer, I've never heard of it? Can you guide me?

**Comment by RussH** [comment]
Hi johnuzojr

unless you want to run the php 7.2 opencats development version, you can run two versions of php alongside one-another. e.g. https://www.tecmint.com/install-different-php-versions-in-ubuntu/

**Comment by johnuzojr** [comment]
Thanks @RussH 

I had already switched to installing it on the web platform, like shared hosting (even though I'm using a VPS). Worked perfectly! I was able to downgrade the php version to 5.6 for my specific domain name on Cpanel.

**Comment by RussH** [comment]
whew.. we'll get there with PHP 7.x soon enough!
