### ISSUE TITLE
rss is not valid

### ISSUE THREAD

**Issue by ThomasKujawa** [opencats/OpenCATS#444]
### Expected behavior and actual behavior.

Expected: valid
actual: not valid

### Steps to reproduce the problem.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.personal247.de%2Frss%2F

### What version of opencats are you running? 

0.9.4

### What version of PHP and MySQL are you running

Server:  via TCP/IP
Server-Typ: MySQL
Server-Version: 5.7.26-nmm1-log - (Ubuntu)
Protokoll-Version: 10
Benutzer: @85.13.144.137
Server-Zeichensatz: cp1252 West European (latin1)

Apache
Datenbank-Client Version: libmysql - mysqlnd 5.0.12-dev - 20150407 - 
PHP-Erweiterung: mysqliDokumentation curlDokumentation mbstringDokumentation
PHP-Version: 7.2.19-nmm1

phpMyAdmin Versionsinformationen: 4.9.0.1

**Comment by RussH** [comment]
PHP 7.x is not supported on the 0.9.4.x release version and will generate errors

**Comment by shantadam** [comment]
Hello Thomas,

I’m currently helping @RussH on the app enhancement and bug resolutions.

PROBLEM:

  *   Further peaking in your error log, I noticed the message clearly state that a non-static function is being called as if it was declared to be static.
  *   This is certainly a bug. Which need to be resolved.
  *   The following files reference to a non-static function:
     *   OpenCATS/modules/rss/RssUI.php (line 93 and line 124)
     *   OpenCATS/modules/xml/XmlUI.php (line 97 and line 163)

ANALYSIS:

  *   An object class typically declare non-static function(s), which get reference calls through instantiation, as such::
     *   class DateUtility() { public function getRSSDate(){…} }
     *   $dateUtil = new DateUtility();
     *   $dateUtil->getRSSDate();
  *   Optionally, an object class may declare static function(s), which get reference calls directly. The later functions are independent of class variable initialization, as such:
     *   class DateUtility() { public static function getRSSDate(){…} }
     *   DateUtility::getRSSDate();
  *   In this case, some programmer referenced the non-static function as if it was static call.

RESOLUTION:

  *   Further analyzing the project source code for the use of getRSSDate(), I can confirm that the call should be made statically, as CATSUtility::getAbsoluteURI() is done.
  *   To resolve the issue we need to correct the function’s signature declaration in OpenCATS/lib/DateUtility.php, as such:
     *   Add the word “static” at the beginning of the line 350, as such:
        *   static public function getRSSDate($unixTime = false)

FIX RELEASE:

  *   I’ll relay the through towards @RussH to comment on the fix release timeline.
  *   If you are in a rush, I’d say (ask a programmer) to apply the fix manually on your server.
  *   If I provide you the file, you’ll have to still apply the appropriate file permission for the server to run it.
  *   I don’t know your level of expertise with programming and server administration.

Regards,
Shant Adam

**Comment by RussH** [comment]
I'm still unsure on why this is erroring. The demo site does not show this issue, and it's also on php5.6

https://demo.opencats.org/rss/

**Comment by ThomasKujawa** [comment]
You're right, I did.

I used the original code from github and the error remains.

Where can I search?

**Comment by ThomasKujawa** [comment]
The later functions are independent of class variable initialization, as such: * class DateUtility() { public static function getRSSDate(){…} } * DateUtility::getRSSDate(); *


I inserted the static and the bug is fixed.

**Comment by shantadam** [comment]
Indeed, @ThomasKujawa the function was not declared as "static". This fix will be part of the next release.

I'm glad my fix recommendation resolved your issue :)
