### ISSUE TITLE
Plain Text Password

### ISSUE THREAD

**Issue by amaisonneuve** [opencats/OpenCATS#45]
Need to apply password has for passwords stored in the database.. i can't understand why they are stored in plain text.

**Comment by libregeek** [comment]
I have seen this before, but never bothered because in our company we use LDAP and never stored the passwords in MySQL database. This is a very very important feature and it should be top priority.

**Comment by RussH** [comment]
Need to do two things - first implement a function to use (save/read/etc) MD5crypt for passwords. Then, a migration script to work through all existing passwords and apply the function to them.

**Comment by libregeek** [comment]
The best approach is to use PHP's native password hashing (http://in.php.net/manual/en/faq.passwords.php). But, this is available only in 5.5 and later. The default PHP version in majority of server distributions (CentOS) is 5.4, so I think we should do a simple md5 implementation for the time being and later upgrade.
