### ISSUE TITLE
OpenCATS vs CandidATS

### ISSUE THREAD

**Issue by mwdmwd1** [opencats/OpenCATS#46]
OpenCATS is very very good.  CandidATS is a fork from OpenCATS and following its own development cycle.

I am planning to implement either one of these for the first time within my organization.  So far what I have understood is this:

CandidATS
- is  on a good development cycle since about a year
- has security and permissions implemented
- has some extra filters in candidate advanced search results page
- is currently on 2.0 RC1 release
- has bugs in online Demo and hence I assume will have bugs when installed too
- Does not have integration with Sphinx 2.x
- supports docx, html, doc, pdf, etc

OpenCATS
- has been a little slow on development since Asim (CATSone) stopped contributing
- is currently on <1.0 release
- has much more stable online demo with no bugs that I came across
- has integration with Sphinx 2.x
- supports doc, html, pdf.  Not sure if docx is supported

Because of the 2.0 release and faster development since last 1 year, I am leaning towards CandidATS.  However, its long term vision is unknown, and the online demo is buggy, so not sure if CandidATS is really the way to go.  We plan to sync it with vTiger and use both in tandem.  Both OpenCATS and CandidATS dont seem to have SOAP or public API access, hence the sync to the ATS will be direct DB or code level API calls.  vTiger has a public API hence the sync on vTiger will be via vTiger API.

If anyone here can please recommend one over the other, or just some points that can help me make a more firm decision, that will be great.  Thank you.

**Comment by RussH** [comment]
Hi there, sorry to close the issue here - but can you post this to the forums instead please - either with opencats or with CandidATS.

**Comment by RussH** [comment]
Not an issue

**Comment by RussH** [comment]
@mwdmwd1 I'd like to talk about your use-cases with vTiger if you're using it alongside opencats - can you email me at russh@opencats.org please?

**Comment by dspacepoland** [comment]
RussH have you www or blogsite?

**Comment by RussH** [comment]
hi @dspacepoland the opencats website is at http://opencats.org
