### ISSUE TITLE
0.9.5 missing Vendor folder & PHPMailer not working

### ISSUE THREAD

**Issue by kykpeng** [opencats/OpenCATS#468]
### Expected behavior and actual behavior.
0.9.5 repositories are missing ./vendor folder.  It works after simply taking the ./vendor folder from 0.9.4.  However, the PHPMailer function outputs errors and cannot send email via any of the ... mail(), sendmail, or SMTP options

### Steps to reproduce the problem.
download and install a fresh copy of 0.9.5 on a PHP7.2 LAMP machine

### What version of opencats are you running? 
0.9.5

#### Release or downloaded from Git? 
Downloaded

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
PHP 7.2.4, MySQL 14

**Comment by shantadam** [comment]
Hello kykpeng,

You seem to be pointing to two different concerns, as such:

  1.  The missing of <vendor> folder.
  2.  Email related error message being notified.

Issue #1:
1.a - Resolution is not copying over another app version’s <vendor> folder over.
1.b – You need to run Composer install command to download and retrieve the right modules for the application’s correct version.

Issue #2:
2.a – Certainly copying of another <vendor> folder from another version of the app will not help.
2.b – 1st ensure you run the Composer install command to download and retrieve the right modules’ versions for the application to work as expected.

If issue persists, please feel free to follow-up with the followings:

  *   Detailed steps you’ve taken for us to reproduce the error.
  *   Detailed error message (or server log file preferably).

Regards,
Shant Adam

**Comment by kykpeng** [comment]
Worked perfectly!  "composer install" that's it!!

**Comment by shantadam** [comment]
Glad to read that it all worked out well.

Regards,
Shant Adam


On Mar 7, 2020, at 9:20 AM, kykpeng <notifications@github.com> wrote:

﻿

Worked perfectly! "composer install" that's it!!
