### ISSUE TITLE
0.9.4 ../careers/index.php HTTP 500 Error

### ISSUE THREAD

**Issue by kykpeng** [opencats/OpenCATS#471]
### Expected behavior and actual behavior.
When enter ../careers/index.php, the Client browser sees an HTTP 500 error.

### Steps to reproduce the problem.
Seems like index.php simply missing Include ../config.php

### What version of opencats are you running? 
0.9.4
#### Release or downloaded from Git? 
Download
#### WAMP or LAMP? 
LAMP
### What version of PHP and MySQL are you running
PHP 7.2

**Comment by alexandre433** [comment]
Please post or give a gist of the php_error.log please.

**Comment by kykpeng** [comment]
It's been fixed.  Just add "Include ../config.php"
