### ISSUE TITLE
Features Missing/That Should Be Implemented

### ISSUE THREAD

**Issue by alexandre433** [opencats/OpenCATS#474]
Hello,

I've just installed this project into my company's server and some features, I think, are missing to make the website more configurable on the admin/root panel.
This, for now, is just a list that I think should be added, and I might start on those features myself

Features:
- [ ] **SMTP Configurations**
  - [ ] Update Host
  - [ ] Update Username
  - [ ] Update Password
  - [ ] Update Port

- [ ] **Email Configurations**
  - [ ] Update Subject
  - [ ] Accept special characters
    - once it sends the email, characters like ç, aren't properly formated and gibberish comes out

- [ ] **Language Picker**
  - If someone wants to use this project and use it on another language its really hard to change languages due to everything being in english and it has to be changed "hardcoded" instead of a "global language picker"

- [ ] **API** ? (not sure)

**Comment by RussH** [comment]
Hi alexandre

thanks for the comments - certainly some configuration changes are only configurable if you amend the config.php file.

Email & Special Characters, I've not come across this - but I assume that'll be a check on th einput to phpmailer (see https://github.com/PHPMailer/PHPMailer/issues/1010) . Additionally, there are (aged) PR's that would permit bulk mailshots to candidate and client lists, and customised footers. These were submitted against 0.9.4 so would need reviewed and updated before any incorporation into the current php 7.x version in develop. They should be in the aged-pr branch.

Finally - Il8n, there was a PR submitted for this, but the original PR was never updated after comments (https://github.com/opencats/OpenCATS/pull/263). It may well be a useful starting point.
