### ISSUE TITLE
Nginx Blank page after fresh install

### ISSUE THREAD

**Issue by jahagirdar** [opencats/OpenCATS#476]
I followed all the steps listed in https://opencats-documentation.readthedocs.io/en/latest/Install-Ubuntu-16.04.html with four major differences.

1. My environment is LEMP and not LAMP
2. I installed to `/var/www` and not `/var/www/html`
3. I created a nginx.opencats.conf file to host the app at job.{mycompany}.com
4. I used a password other than "databasepassword"

On browsing to job.{mycompany}.com I find a blank page. and not the "Click: Installation Wizard" page

### Expected behavior and actual behavior.
Expected to see   "Click: Installation Wizard"  page. seeing blank page
### Steps to reproduce the problem.
Install with the 4 differences listed above.
### What version of opencats are you running? 
opencats-0.9.4-full.zip
#### Release or downloaded from Git? 
wget https://github.com/opencats/OpenCATS/releases/download/0.9.4/opencats-0.9.4-full.zip
#### WAMP or LAMP? 
LEMP
### What version of PHP and MySQL are you running
PHP 7.2.30-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Apr 19 2020 07:50:50) ( NTS )
mysql  Ver 14.14 Distrib 5.7.29, for Linux (i686) using  EditLine wrapper

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
Missing favicon is the only error seen in server log.

My nginx.conf is as follows

```
server {
        listen 80;
        server_name job.<mycompany>.com;

        location / {
                root   /var/www/opencats;
                index  index.php index.html;

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
	
		# With php5-cgi alone:
		# fastcgi_pass 127.0.0.1:9000;
		# With php5-fpm:
		fastcgi_pass unix:/var/run/php/php5.6-fpm.sock;
		fastcgi_index index.php;
		include fastcgi_params;
	}
        }
}
```

**Comment by jahagirdar** [comment]
Going through some other issues, I guess the php version is the issue.
Please not the version supported by this app (php5) EOL'ed in 2018.

**Comment by RussH** [comment]
HI @jahagirdar the test release supports v7.x
