### ISSUE TITLE
Listings Empty

### ISSUE THREAD

**Issue by hfiles04** [opencats/OpenCATS#489]
### Expected behavior and actual behavior.
When loading the Job Orders, Candidates, Companies, Contacts screens no items are listed.

### Steps to reproduce the problem.
1. Installed using database from existing 0.9.1 installation.
2. Every page was blank.
3. Fixed missing \" on line 211 of \lib\Mailer.php, installed composer, and ran "composer dump-autoload -o" on opencats directory.
4. Was able to log in, but opening aforementioned pages the listings show no entries.

### What version of opencats are you running? 
RussH's test release v3, listed as 0.9.5-3

#### Release or downloaded from Git? 
Release

#### WAMP or LAMP? 
Lamp

### What version of PHP and MySQL are you running
PHP 7.4.3, 4.9.5deb2

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
No errors were listed on page load. Please let me know what logs should be added.

**Comment by DJI1957** [comment]
I fixed this issue by swapping mysql out for mariadb see above
