### ISSUE TITLE
New job and company add issue 

### ISSUE THREAD

**Issue by PoojaMintex** [opencats/OpenCATS#490]
I installed opencats CATS Version 0.9.4 in linux hosting
it installed properly, but when i create job or company i get issue 500 error

i also attached screenshot
![opencats issue](https://user-images.githubusercontent.com/69916051/92705999-c890ac80-f371-11ea-9f77-865f4c0485f3.png)

plz reply fast

**Comment by RussH** [comment]
Hi, 

okay, firstly you need to install v0.9.5-3 if you're doing a new install. https://github.com/opencats/OpenCATS/releases. v0.9.4 will have php 5.6 compatibility only. 

0.9.5-3 is a test release, but it's being used in production. As this isn't tagged as a full release you will need to use composer to install the dependencies after you install the software. 

I have some PR's to be approved before I can create a full release.

**Comment by RussH** [comment]
no response - closing
