### ISSUE TITLE
ACL:  how to get Role of current user logged in to control access to Page Fields

### ISSUE THREAD

**Issue by ringk-itcs** [opencats/OpenCATS#503]
Hi Everyone!

Such a great product for Open Source !     

We've created 2x new user Roles via **_config.php (class ACL_SETUP)_** and both are working as intended:

- Recruiter
- Senior Recruiter

We want to "lockdown" the visibility of data of fields on the Joborder Tab. based on the User's Role when they login.

For example, in **_modules/joborders/Show.tpl_** (lines: 114-117), we want to stop "Role: Recruiter" from seeing **_data_** in  the "Max Rate:" field and replace it with a **_default "message"_** 

```
                            <tr>
                                <td class="vertical">Max Rate:</td>
                                <td class="data"><?php $this->_($this->data['maxRate']); ?></td>
                            </tr>
```

Would you mind to show an example using the _"demo"_ role (as in config.php)? 

I can re-work it to match our new roles.

I've trolled through **_modules/settings/EditUser.tpl_** to try and reverse engineer how the **_Role Radio Button_** is populated for the existing value for a given user but am at a loss how to do it.

Essentially, here is the pseudo code of what we need  to do in **_modules/joborders/Show.tpl_**:

```
             IF ( USER_ROLE == "demo" ) 
             THEN
                            <tr>
                                <td class="vertical">Max Rate:</td>
                                <td class="data"><?php $this->_($this->data['maxRate']); ?></td>
                            </tr>
            ELSE
                            <tr>
                                <td class="vertical">Max Rate:</td>
                                <td class="data"><?php $this->_($this->"NOT_ALLOWED"); ?></td>
                            </tr>
          END IF
```

Thanks in advance for any assistance.

KarlR

**Comment by RussH** [comment]
not sure if @skrchnavy is still around, but the ACL work was from him and @Kixy25

**Comment by shantadam** [comment]
Hi @ringk-itcs,

Your ask is to hide a UI element based on a user’s access level.

Probably the blocker you’re having is the lack visualising the app’s module form of architecture that is based on the good old MVC model:
- Take JobOrders module for instance. When we break it down into pieces we get:
— M (Model) = dataGrids.php
— V (View) = JobOrders.tpl
— C (Controller) = JobOrdersUI.php
- The controller (JobOrderUI.php) orchestrates content data read/write from/to the data model (dataGrids.php) and read/write from/to the view (JobOrder.tpl).
- Meaning you can define a variable on the view from the controller that determines your view component’s visibility based on user’s access level.
- Then on the view you can use PHTML to wrap a visual element with code logic that verifies the variable’s value to show or hide it.

Hope the above guides you to see a module’s architecture puzzle pieces better.

Regards,
Shant Adam


On Oct 21, 2020, at 6:22 AM, RussH <notifications@github.com> wrote:

﻿

not sure if @skrchnavy<https://github.com/skrchnavy> is still around, but the ACL work was from him and @Kixy25<https://github.com/Kixy25>

**Comment by ringk-itcs** [comment]
Hi @shantadam 

Great thanks for taking the time and effort for that explanation!  

Really does help.

Will need to digest and reverse through the scripts to have it all make sense.

Thanks again,
KarlR

**Comment by skrchnavy** [comment]
Please check wiki: https://github.com/opencats/OpenCATS/wiki/Access-Control-Lists

**Comment by shantadam** [comment]
Thanks @Sveto for the insight.

The ACL definition list and the mapping list certainly helps. On the flip side, it’s also as important to understand the MVC model application and the related pieces in ordre to apply custom controlling.

Regards,
Shant Adam,


On Oct 23, 2020, at 7:06 AM, Sveto Krchnavy <notifications@github.com> wrote:

﻿

Please check wiki: https://github.com/opencats/OpenCATS/wiki/Access-Control-Lists

**Comment by shantadam** [comment]
Furthermore to my last statement, it’s important to consider the practice of isolating added customization to the app by extending and overriding added custom code logic in ordre not to mingle in the app’s core source files. Unless your intention is to ask the OpenCATS team to intake the change.

Regards,
Shant Adam,

On Oct 23, 2020, at 8:58 AM, Shant Adam <shant.adam@mxcgi.com> wrote:

﻿ Thanks @Sveto for the insight.

The ACL definition list and the mapping list certainly helps. On the flip side, it’s also as important to understand the MVC model application and the related pieces in ordre to apply custom controlling.

Regards,
Shant Adam,


On Oct 23, 2020, at 7:06 AM, Sveto Krchnavy <notifications@github.com> wrote:

﻿

Please check wiki: https://github.com/opencats/OpenCATS/wiki/Access-Control-Lists

**Comment by ringk-itcs** [comment]
Thanks @shantadam and @sveto for your replies.  

We don't have any intentions at this stage to merge changes with the project.  We have other "UI/UX" updates that will share to the opencats.forum.org so others can have a play around.

Thanks again.
