### ISSUE TITLE
ACL: Activities tab control via config.php

### ISSUE THREAD

**Issue by ringk-itcs** [opencats/OpenCATS#504]
Hi everyone!.

We would like to "lockdown" the **Activities tab** for certain roles like OC can for Candidates and Joborders.  In **config.php** for example, we have a role and have locked the **Candidates Tab** like this:

            'candidates' => ACCESS_LEVEL_DISABLED, //ACCESS_LEVEL_READ,
            'candidates.add'  => ACCESS_LEVEL_DISABLED,
            'candidates.deleteAttachment'  => ACCESS_LEVEL_DISABLED,
            'candidates.addActivityChangeStatus'  => ACCESS_LEVEL_DISABLED,
            'candidates.deleteAttachment'  => ACCESS_LEVEL_DISABLED,
            'candidates.createAttachment'  => ACCESS_LEVEL_DISABLED,
            'candidates.addCandidateTags'  => ACCESS_LEVEL_DISABLED,
            'candidates.history'  => ACCESS_LEVEL_DISABLED,
            'candidates.edit'  => ACCESS_LEVEL_DISABLED,
            'candidates.delete'  => ACCESS_LEVEL_DISABLED,
            'candidates.administrativeHideShow'  => ACCESS_LEVEL_DISABLED,
            'candidates.considerForJobSearch'  => ACCESS_LEVEL_DISABLED,
            'candidates.manageHotLists'  => ACCESS_LEVEL_DISABLED,
            'candidates.show'  => ACCESS_LEVEL_DISABLED,
            'candidates.add'  => ACCESS_LEVEL_DISABLED,
            'candidates.search'  => ACCESS_LEVEL_DISABLED,
            'candidates.viewResume'  => ACCESS_LEVEL_DISABLED,
            'candidates.search'  => ACCESS_LEVEL_DISABLED,
            'candidates.hidden'  => ACCESS_LEVEL_DISABLED,
            'candidates.emailCandidates'  => ACCESS_LEVEL_DISABLED,
            'candidates.show_questionnaire'  => ACCESS_LEVEL_DISABLED,
            'candidates.list'  => ACCESS_LEVEL_DISABLED,

I have not found anything in the docs online of the forum, is there a way we can add the same "ACL" to the **Activities Tab** for user defined roles in **config.php**?

Thanks again for your help, and I will share any code updates here for the community.

KarlR

**Comment by skrchnavy** [comment]
Hi.

You can find it here: https://github.com/opencats/OpenCATS/wiki/Access-Control-Lists

Access level map in form `category => securedObject  => accessLevel` so it means you have to define:
- category (something as group or role);
- securedObject - it is functionality, usualy accessible via menu/submenu/submenu/.... it is cascaded, so you can define level for menu and it is then appkied for all subMenu items. Then you can make exception adding special menu.submenu level.
- accessLevel is from list of available defined levels - see https://github.com/opencats/OpenCATS/blob/develop/constants.php#L71 ; this access level is checked against required level and must be higher or equal.

user has it's own accessLevel (you can set it) but when you define category for user, it has preference for the secured object..

**Comment by ringk-itcs** [comment]
Thanks @skrchnavy, much appreciated.  Willhave a look at the link.
