### ISSUE TITLE
Install resume indexing step doesn't use shown paths unless you edit one.

### ISSUE THREAD

**Issue by JoshMcCullough** [opencats/OpenCATS#51]
When you get to step 4, if you immediately click "Test Configuration", it will fail (on Linux at least) because it is testing under "C:..." instead of the paths which are pre-populated in the textboxes. So I made a fake edit to one of the textboxes and then clicked "Test Configuration" again and this time it used the correct paths.

**Comment by RussH** [comment]
Resolved in PR#17
