### ISSUE TITLE
./vendor/autoload.php

### ISSUE THREAD

**Issue by vanderkoltadmin29** [opencats/OpenCATS#516]
### Expected behavior and actual behavior.
Going to homepage after install into ionos hosting
### What version of opencats are you running? 
0.9.5-3
#### Release or downloaded from Git? 
Yes
### What version of PHP and MySQL are you running
7.4
### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
Fatal error: require(): Failed opening required './vendor/autoload.php' (include_path='.:/usr/lib/php7.4') in /homepages/46/d858011460/htdocs/ats/lib/Mailer.php on line 43

**Comment by RussH** [comment]
php 7.4 is unsupported. Max of PHP 7.2 ; please use https://github.com/opencats/OpenCATS/releases/tag/0.9.6 and the opencats-0.9.6-full.zip package.
It's built successfully, auto-generated the full packages, and I've done a test build and install myself.

I'm gonna close this - but please re-open if it's still got errors.
