### ISSUE TITLE
No candidate listing

### ISSUE THREAD

**Issue by DJI1957** [opencats/OpenCATS#518]
Candidates tab shows no entries, quick search and recents works as expected
swapping mysql 5.7 out for mariadb 10 listing works as expected

### What version of opencats are you running? 
0.9.5.2

#### Release or downloaded from Git? 
from git

**Comment by RussH** [comment]
opencats was tested with MariaDB only

**Comment by RussH** [comment]
Hi please use https://github.com/opencats/OpenCATS/releases/tag/0.9.6 and the opencats-0.9.6-full.zip package.
It's built successfully against php7.2, auto-generated the full packages, and I've done a test build and install myself.

I'm gonna close this - but please re-open if it's still got errors.
