### ISSUE TITLE
docker install?

### ISSUE THREAD

**Issue by cptr13** [opencats/OpenCATS#520]
### Expected behavior and actual behavior.
Docker install doesn't seem to work.  I'm getting a 403 error.  Not sure how to correct it.  Could be incorrect permissions on /var/www/  ?

**Comment by RussH** [comment]
Okay let me sort this out. Don't generally use Docker but will check and fix.

**Comment by blazej-czuk** [comment]
For me, the problem was generated using this docker-compose.
https://opencats.readthedocs.io/en/latest/Install-on-Docker-Tutorial.html

If I use this docker-compose then I have a different problem.
https://github.com/opencats/OpenCATS/blob/master/docker/docker-compose.yml
ERRORS:
opencats_data exited with code 0
opencats_mariadb | ERROR 1146 (42S02) at line 2: Table 'cats.user' doesn't exist
opencats_mariadb exited with code 1

**Comment by RussH** [comment]
Okay - so it appears to work for me.
![opencats_docker_successful](https://user-images.githubusercontent.com/282748/113162130-eb63af00-9236-11eb-9e04-a009cbd03ea7.png)

However the error message about cats.user also appears. But as I'm using  'production' docker and not  'testing' docker then I wouldn't expect it to pre-populate with users. In fact, I checked (and updated) my 'quick and Dirty opencats Docker how-to' and it covers user creation;
[docker-install-instructions.txt](https://github.com/opencats/OpenCATS/files/6237368/docker-install-instructions.txt)

I'll leave this open for now in-case this doesn't resolve your issues!

**Comment by RussH** [comment]
okay, you can't try to connect to localhost in the install wizard - you have to use the IP address of the MariaDB container. In this case, it's   172.19.0.3.

All working.

**Comment by blazej-czuk** [comment]
@RussH  thank you very much for the instruction.

There were errors during the installation.
![image](https://user-images.githubusercontent.com/71962806/113264217-0257df00-92d3-11eb-86ad-c514df2e172c.png)

I have more errors after going through the installation.
![image](https://user-images.githubusercontent.com/71962806/113264294-1ac7f980-92d3-11eb-8370-e0c0dc4f5ef8.png)

**Comment by RussH** [comment]
yes, you need to do the 'run composer' step (line 18) to pull down the php dependencies.
https://getcomposer.org/
(this isn't 'docker-compose'!)

**Comment by blazej-czuk** [comment]
Finally, I installed OpenCATS with your help @RussH 
Thank you very much again.

Now I am ready to integrate with LDAP.
However, I cannot find the LDAP configuration instructions

https://github.com/opencats/OpenCATS/wiki/LDAP_Authentication_module

This link is not working.
http://sarovar.org/frs/shownotes.php?release_id=736

**Comment by RussH** [comment]
Okay, will close this issue - however for LDAP, that external module you reference is the very first version of LDAP support that was committed. LDAP is something I've *genuinely* never touched with OpenCATS.

It was integrated subsequently after the module you reference - if you search for PR's referencing LDAP you should find them, and whilst looking for LDAP documentation, it looks like it should have been migrated to readthedocs, but possibly was deleted by mistake?    

Here's what it used to be; https://github.com/AnritsuSolutionsSK/OpenCATS/blob/dd1cbfdb5edafbef55f40510352aa7879e6b7810/doc/INSTALL.md
