### ISSUE TITLE
Fresh install, no index.php

### ISSUE THREAD

**Issue by cptr13** [opencats/OpenCATS#524]
### Expected behavior and actual behavior.
Working on updating Ubuntu install script.  Entire install process goes fine.  No errors whatsoever.  Nothing loads on first post-install screen (index.php)
### What version of opencats are you running? 
9.5-3
#### Release or downloaded from Git? 
release (pre-release)
#### WAMP or LAMP? 
LAMP, Ubuntu 20.04, MariaDB, PHP 7.2

**Comment by RussH** [comment]
@cptr13 did you use the full package I added to the 9.5-3 release?

**Comment by cptr13** [comment]
I'm not sure how you mean. It's Travis so it's got the post install files. Yes... Is that what you mean?

**Comment by RussH** [comment]
ahh you're looking at the php7 version. Okay - will upload a revised package  to the release shortly!

**Comment by cptr13** [comment]
Blank screen still.  I assume you're using apache still, correct?

**Comment by RussH** [comment]
Hi @cptr13 please use https://github.com/opencats/OpenCATS/releases/tag/0.9.6 and the opencats-0.9.6-full.zip package.
It's built successfully, auto-generated the full packages, and I've done a test build and install myself.

I'm gonna close this - but please re-open if it's still got errors.
