### ISSUE TITLE
child 8 said into stderr: "NOTICE: PHP message: Can't contact LDAP server"

### ISSUE THREAD

**Issue by blazej-czuk** [opencats/OpenCATS#530]
### Expected behavior and actual behavior.
I would like to log into the system with the user from Active Directory.
I cannot contact the LDAP server.

LDAP server ports 636 and 389 are open.
![image](https://user-images.githubusercontent.com/71962806/113284973-af8a2180-92ea-11eb-8a18-6f493f715855.png)

### Steps to reproduce the problem.
I followed the instructions:

https://github.com/AnritsuSolutionsSK/OpenCATS/blob/dd1cbfdb5edafbef55f40510352aa7879e6b7810/doc/INSTALL.md

![image](https://user-images.githubusercontent.com/71962806/113284502-06432b80-92ea-11eb-9ade-e8ce15e42ed8.png)
![image](https://user-images.githubusercontent.com/71962806/113284608-2b379e80-92ea-11eb-8a18-bdac2d5a34c8.png)

### What version of opencats are you running? 
![image](https://user-images.githubusercontent.com/71962806/113284003-4b1a9280-92e9-11eb-9503-ed61651e4e83.png)

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
![image](https://user-images.githubusercontent.com/71962806/113284055-5c639f00-92e9-11eb-9e94-3947b1bd2a03.png)
![image](https://user-images.githubusercontent.com/71962806/113284320-c0866300-92e9-11eb-85f6-33befc30e65a.png)
![image](https://user-images.githubusercontent.com/71962806/113285626-7b633080-92eb-11eb-90c1-161ba2af6528.png)

**Comment by RussH** [comment]
you might need to check this info here?

https://github.com/opencats/OpenCATS/pull/366

**Comment by wumb0** [comment]
sounds like you don't have LDAP set up right, since it cannot contact the LDAP server. 
just because you can hit the port doesn't mean the PHP LDAP plugin can communicate with it properly. 
it's also running in docker, which might be causing issues as well.
See if you can hit 636 from your OpenCATS container, and then use a tool like `ldapsearch` to see if you can make remote queries using the information you provided in the config. 

Beyond that, set more debug messages in the code to figure out on what line it is breaking on would be the next step, so we can narrow down the issue and help further.

**Comment by blazej-czuk** [comment]
I wanted to install ldap-tools in container opencats.
I can't because there is no apt-get library added.
![image](https://user-images.githubusercontent.com/71962806/113386574-d9932080-938a-11eb-8014-b99871cc029d.png)

**Comment by blazej-czuk** [comment]
> I wanted to install ldap-tools in container opencats.
> I can't because there is no apt-get library added.
> ![image](https://user-images.githubusercontent.com/71962806/113386574-d9932080-938a-11eb-8014-b99871cc029d.png)

**Comment by blazej-czuk** [comment]
I wanted to install ldap-tools in container opencats.
I can't because there is no apt-get library added.
![image](https://user-images.githubusercontent.com/71962806/113386574-d9932080-938a-11eb-8014-b99871cc029d.png)

apk update  and apk add
**NOT** resolve my problem.

**Comment by blazej-czuk** [comment]
![image](https://user-images.githubusercontent.com/71962806/113389914-19f59d00-9391-11eb-9b85-c01ded1432e4.png)
Container opencats_php and opencats_web see open port 636 and 389.

**Comment by blazej-czuk** [comment]
Could the problem be with BusyBox? Are utilities sufficient? But I don't know if it depends on it.

**Comment by blazej-czuk** [comment]
We have successfully installed ldap tools.
![image](https://user-images.githubusercontent.com/71962806/113399733-fc303400-93a0-11eb-9f2c-16070f30c018.png)

The users do not have access, but they are created in the database.

Now we have this problem error:
![image](https://user-images.githubusercontent.com/71962806/113400360-f6871e00-93a1-11eb-834f-6d1fe039c342.png)

**Comment by blazej-czuk** [comment]
Now I have a problem with the attribute mapping :)
![image](https://user-images.githubusercontent.com/71962806/113401296-73ff5e00-93a3-11eb-9be5-1a7970037d46.png)

**Comment by blazej-czuk** [comment]
I have one more request @wumb0 
Is it possible to restrict logging for an AD group?
AUTH_LDAP_REQUIRE_GROUP_DN

**Comment by skrchnavy** [comment]
It is possible to add check for membership in group after bind:  
https://www.php.net/manual/en/ref.ldap.php#99347  
See checkGroup(Ex) functions.

**Comment by blazej-czuk** [comment]
yes i know it is possible but it is not implemented in OpenCATS.
Maybe someone will want to implement such a function in the future?
