### ISSUE TITLE
q

### ISSUE THREAD

**Issue by taplog13** [opencats/OpenCATS#536]
I have 150000 candidates rows in candidate table and 150000 attachments in attachment table. I am facing issue when do order by query in candidate table columns except candidate_id column so order by query takes lots of time and some time timeout. Order by query takes more time like 70sec, 80sec or 90sec but when query has order by primary key(column) then query working fine and execute in 0.60 sec. 

same thing in attachment table, order by column slowing down system.

**Comment by RussH** [comment]
Please see issue #312  as a possible fix
