### ISSUE TITLE
Order by query slowing down system and timeout for candidate and attachment tables

### ISSUE THREAD

**Issue by ashishnishad** [opencats/OpenCATS#537]
I have 150000 candidates rows in candidate table and 150000 attachments in attachment table. I am facing issue when do order by query in candidate table columns except candidate_id column so order by query takes lots of time and some time timeout. Order by query takes more time like 70sec, 80sec or 90sec but when query has order by primary key(column) then query working fine and execute in 0.60 sec.

same thing in attachment table, order by column slowing down system.

**Comment by RussH** [comment]
Please see issue #312  as a possible fix

**Comment by RussH** [comment]
See here for similar issue https://stackoverflow.com/questions/13389817/mysql-slow-select-order-by-on-a-large-table

**Comment by ashishnishad** [comment]
I created indexes but not helpful
This is my query 

`SELECT 
                candidate.candidate_id AS candidateID,
                candidate.candidate_id AS exportID,
                candidate.is_hot AS isHot,
                candidate.date_modified AS dateModifiedSort,
                candidate.date_created AS dateCreatedSort,
            candidate.candidate_id AS candidate_id,
attachment_id, IF(candidate_joborder_submitted.candidate_joborder_id, 1, 0) AS submitted,
                                                IF(attachment_id, 1, 0) AS attachmentPresent,
candidate.first_name AS firstName,
candidate.last_name AS lastName,
candidate.key_skills AS keySkills,
DATE_FORMAT(candidate.date_modified, '%m-%d-%y') AS dateModified,
candidate.email1 AS email1,
candidate.phone_home AS phoneHome
            FROM
                candidate
            LEFT JOIN attachment
                                                        ON candidate.candidate_id = attachment.data_item_id
														AND attachment.data_item_type = 100
                                                    LEFT JOIN candidate_joborder AS candidate_joborder_submitted
                                                        ON candidate_joborder_submitted.candidate_id = candidate.candidate_id
                                                        AND candidate_joborder_submitted.status >= 400
                                                        AND candidate_joborder_submitted.site_id = 1
                                                        AND candidate_joborder_submitted.status != 650 LEFT JOIN saved_list_entry
                                    ON saved_list_entry.data_item_type = 100
                                    AND saved_list_entry.data_item_id = candidate.candidate_id
                                    AND saved_list_entry.site_id = 1
            WHERE
                candidate.site_id = 1
            
            
            
            
            GROUP BY candidate.candidate_id
            
            order by email1 desc
            LIMIT 0, 15`

**Comment by RussH** [comment]
Also - have you looked at optimising your MySQL / MariaDB instance using mysqltuner to identify bottlenecks?  
https://www.linode.com/docs/guides/how-to-optimize-mysql-performance-using-mysqltuner/

**Comment by ashishnishad** [comment]
When i am using   ORDER BY candidate.candidate_id DESC  LIMIT 119985, 15 then query very slow 
means query also not working with large data or more offset value
