### ISSUE TITLE
Candidate search query is very slow for large data like 150000

### ISSUE THREAD

**Issue by ashishnishad** [opencats/OpenCATS#538]
Candidate search query is very slow for large data like 150000. Candidate search page count query is taking 17 sec. I tried every indexing but nothing is working.

`
SELECT
                COUNT(*) AS count
            FROM
                attachment
            LEFT JOIN candidate
                ON attachment.data_item_id = candidate.candidate_id
                AND attachment.data_item_type = 100
                AND attachment.site_id = candidate.site_id
            LEFT JOIN user AS owner_user
                ON candidate.owner = owner_user.user_id
            WHERE
                resume = 1 AND attachment.data_item_id != 0
            AND
                ((attachment.text LIKE '%java%'))
            AND
                (ISNULL(candidate.is_admin_hidden) OR (candidate.is_admin_hidden = 0))
            AND
                (ISNULL(candidate.is_active) OR (candidate.is_active = 1))
            AND
                attachment.site_id = 1
`

**Comment by RussH** [comment]
this is why the searchd functionality exists - please ensure you have searchd enabled.
See https://github.com/opencats/OpenCATS/tree/master/optional-updates/latest-sphinx-search

**Comment by ashishnishad** [comment]
I tried searchd and it is working but for limited result like if i set limit 1000 then it will show 1000 results but db has more results for same string so how can i search string using searchd and paginate all results not only 1000

**Comment by RussH** [comment]
I updated your other issue you raised for the 1000 result limit with the info you need from the sphinx / searchd project
