### ISSUE TITLE
Candidate search is not working when adding AND OR condition.

### ISSUE THREAD

**Issue by ashishnishad** [opencats/OpenCATS#540]
I am searching with this keywords **"JAVA DEVELOPER" AND "SPRING" AND "MONGO DB"**
but it DatabaseSearch::makeBooleanSQLWhere returning me  **((attachment.text REGEXP '[[:<:]]JAVA DEVELOPER[[:>:]]') AND  (attachment.text REGEXP '[[:<:]]SPRING AND MONGO DB[[:>:]]'))**

When i add multiple AND OR condition in search field then it is not creating correct mysql like query.
Giving 504 errors

**Comment by RussH** [comment]
quick check on a test system does not show an error for;

JAVA DEVELOPER" AND "SPRING" AND "MONGO DB"
