### ISSUE TITLE
empty backup

### ISSUE THREAD

**Issue by donster22** [opencats/OpenCATS#545]
### Expected behavior and actual behavior.
backing up the database. am expecting the .bak file to contain data. it doesn't.

### Steps to reproduce the problem.
backing up via the settings menu.

### What version of opencats are you running? 
0.9.6 on Ubuntu 18.04.5 LTS

#### Release or downloaded from Git? 
downloaded

#### WAMP or LAMP? 
LAMP (i think)

### What version of PHP and MySQL are you running
PHP 5.6.40-51+ubuntu18.04.1+deb.sury.org+1 (cli)
mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.

this looks relevant from the apache2 error logs but I have no idea what it means.

    [Thu Jul 01 10:51:04.005303 2021] [:error] [pid 10446] [client xx.xx.xx.xx:53797] PHP Warning:  mysqli_query() expects 
    parameter 1 to be mysqli, object given in
    /var/www/html/opencats/modules/settings/ajax/backup.php on line 241, referer: https://xx.xx.xx.xx/opencats/index.php? 
    m=settings&a=createBackup

Line 241:
    $queryResult = mysqli_query($db, $sql);

**Comment by RussH** [comment]
Dup of #542
