### ISSUE TITLE
OpenCats v0.9.4 - # Results Button - Missing

### ISSUE THREAD

**Issue by acpsupport** [opencats/OpenCATS#548]
### Expected behavior and actual behavior.
The expected behavior is to display the #Results on the "Job Order" tab.
The actual behavior is disabled or does not display the # Result button

### Steps to reproduce the problem.
We have download and installed the OpenCats v0.9.4 via https://github.com/opencats/OpenCATS/releases/
After installed, Go to the "Job Order" tab

### What version of opencats are you running? 
We are running OpenCats v0.9.4

#### Release or downloaded from Git? 
Yes. we have downloaded it from Git (https://github.com/opencats/OpenCATS/releases/)

#### WAMP or LAMP? 
It is LAMP (Ubuntu 20.04.2 LTS, Apache 2.4.41, MariaDB 10.3, PHP 5.6.40)

### What version of PHP and MySQL are you running
PHP v5.6.40 and MariaDB 10.3

**Comment by acpsupport** [comment]
We have download and installed the OpenCats v9.0.4 via https://github.com/opencats/OpenCATS/releases/

However, we do not see the “**# Result**” button on the “**Job Order**” tab which is near the top-right corner to select “publish”.

This will help us to click on “configure Job Posting Service” to enable the job boards that integrate with others [i.e. Monster, JobStreet, Indeed, etc.,]

The Environment:
**LAMP (Ubuntu 20.04.2 LTS, Apache 2.4.41, MariaDB 10.3, PHP 5.6.40)**

So please advise us how to make the “# Results” button to be visible on the “Job Order” Tab

Would appreciate your assistance on this.

Thank you,

**Comment by RussH** [comment]
I had an email conversation on this one, seems like Indeed offered the OP advice for CATS and not OpenCATS. I've pointed them to where XML is configured and the CML template setup.

Closing.

**Comment by shantadam** [comment]
Sounds like there’s been a confusion and I’m glad the concern was clarified and resolved. Thanks, Russ.

Regards,
--
Shant Adam,
T: (778) 877-2028
E: ***@***.******@***.***>
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.


From: RussH ***@***.***>
Date: Friday, August 13, 2021 at 1:20 AM
To: opencats/OpenCATS ***@***.***>
Cc: Shant Adam ***@***.***>, Comment ***@***.***>
Subject: Re: [opencats/OpenCATS] OpenCats v0.9.4 - # Results Button - Missing (#548)

I had an email conversation on this one, seems like Indeed offered the OP advice for CATS and not OpenCATS. I've pointed them to where XML is configured and the CML template setup.

Closing.
