### ISSUE TITLE
Event Reminders not working. Help with Cron Job or Windows Scheduler.

### ISSUE THREAD

**Issue by summit1691** [opencats/OpenCATS#549]
Emails are working but when I schedule an event reminder I am not receiving any email reminders. I read about setting up a cron job or scheduler for Windows but coudn't find any information on how to set up using the current build.

**Comment by RussH** [comment]
Hi,

it's the same instructions as per previous builds, create the same cron job.

**Comment by summit1691** [comment]
Hello Rush, thanks for your response but I am not able to find any instructions in installation document. Can you please provide me a link for the instructions to set up a cron job.

**Comment by RussH** [comment]
Hiya, 

sorry - I see the update never made it into the Documentation. I'll have to update that myself..

Here you go https://github.com/opencats/OpenCATS_Documentation/issues/11

**Comment by dharias** [comment]
Hi Rush when I run QueueCLI.php it shows the message Deprecated: Non-static method QueueProcessor :: getHour () should not be called statically in /var/www/html/lib/QueueProcessor.php on line 544

Deprecated: Non-static method QueueProcessor :: getMinute () should not be called statically in /var/www/html/lib/QueueProcessor.php on line 548
CATS Queue Processor status: NO TASKS

I am running PHP 7.3
sorry for my English ;)

**Comment by RussH** [comment]
Hi Diego,

php 7.2 is the maximum PHP level currently supported - our Travis CI tests
for PHP 7.3 are failing for the most recent build. I would not deploy on
that level.

However - what you see for QueueProcessor.php are deprecation warnings -
not errors. Functionality should be unchanged.


----
Russ

**Comment by summit1691** [comment]
Hello Russh, I am on Windows so I set up a scheduler to invoke queuecli.php every minute but still it's not working. I tried to manually invoke queuecli.php but I always get the result "CATS Queue Processor status: NO TASKS"
Do any changes are required in Module or Lib files as well.

**Comment by shantadam** [comment]
Hello @summit1691, if I may,

Based on QueueProcessor::startNextTask() your database table "queue" should have some entries. Can you see what the status of your database table "queue" looks like?

**Comment by summit1691** [comment]
Hello Shantadam, Database table Queue is empty. I have entered few events and reminders. They are showing up in reminders table but Queue is empty.

**Comment by shantadam** [comment]
@summit1691,

Can you check if you have any "tasks.php" file under any module folder in "<opencats>/modules".
Kindly, requesting to open your PowerShell command terminal and cd to your <opencatsdir> then run Get-Childitem –Path ".\modules" -Filter "tasks.php" -Recurse.
See if anything comes-up.

**Comment by shantadam** [comment]
@summit1691,

After all, the reason of getting your attention under /modules folder is the expectation that tasks are configured under /modules/queue/tasks.php.

The fact is it's important to understand QueueCLI.php's activities. It starts calling ModuleUtility::registerModuleTasks() which in its turn runs recursively through modules and picks-up "tasks.php" found files to include and make it available for QueueCLI.php to subsequently call for QueueProcessor::startNextTask(). 

Prior to the latter method (QueueProcessor::startNextTask()) call if you haven't defined your tasks files and registered in tasks.php for your modules it won't find any tasks to run, as described in {opencatsdir}/modules/queue/tasks.php, as such: 
// Add a new task to the queue processor using the following line as an example.
// Use the modules/queue/tasks/SampleRecurring.php file as a template
// QueueProcessor::registerRecurringTask('SampleRecurring');

Hope it helps.

**Comment by summit1691** [comment]
I have added a task in the module/calendar/tasks:
QueueProcessor::registerRecurringTask('./modules/calendar/tasks/Reminders.php'); 
Reminders.php was already there.

**Comment by shantadam** [comment]
@summit1691, can you break at QueueProcessor::startTask() and see if that method is being triggered at all?

**Comment by summit1691** [comment]
QueueProcessor::startTask()
Sorry but I am not sure where that is.

**Comment by shantadam** [comment]
@summit1691,  

If you haven't installed xdebug yet, please follow the simplest no IDE solution "Command Line Debug Client" instructions found at https://xdebug.org/download, and familiarize with the quick basic documentation at https://xdebug.org/docs/dbgpClient.

Once the command line terminal starts set a debugging breakpoint at line 231 or the 1st line inside startTask() found inside {opencatsdir}/lib/QueueProcessor.php, as such:
(cmd) 
breakpoint_set -t line -f file:///{opencatsdir}/lib/QueueProcessor.php -n 231

Reload the app in the browser.

**Comment by summit1691** [comment]
Ok, I will do that. But I think the problem I am facing is not tasks are getting entered in Queue. So there are no tasks to be processed in Queue.

**Comment by summit1691** [comment]
Hello, I was trying to install xdebug and I found out it does not support PHP 5.6 which was required for installing opencats. So is there any other options.

**Comment by RussH** [comment]
Hi @summit1691 https://github.com/opencats/opencats/releases - v0.9.6 supports PHP7.2  - which package have you installed if it's not 0.9.6?

**Comment by summit1691** [comment]
I have installed v0.9.6 only but I read in the installation document that it was better to run the installation wizard in PHP5.6
I am assuming I should upgrade to PHP7.2 after installation was completed?

**Comment by summit1691** [comment]
Hello, I upgraded to PHP7.2 and installed xdebug but after running the breakpoint_set command the webpage did not reload.

**Comment by dharias** [comment]
hello I have the same problem as summit. I add the reminder in the calendar, I run the scheduled task and it always shows me "CATS Queue Processor status: NO TASKS".
and it doesn't add any records in the queue table of my db.
sorry for my English

**Comment by ashishnishad** [comment]
I found issue in this file \lib\QueueProcessor.php
and in this function public static function registerRecurringTask($taskPath)
   
in this function, change this   if ($cnt > 0)  with this  if ($cnt[0] > 0) then all will work
