### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by zoomiest2** [opencats/OpenCATS#553]
### Expected behavior and actual behavior.
I get green lights on all of my install tests. But, when I click on the get into the initial screen, I get HTML Error 500

### Steps to reproduce the problem.
Install CATS according to [these steps.](https://opencats-documentation.readthedocs.io/en/latest/Install-Ubuntu-16.04.html) **Is this documentation out of date?**

### What version of opencats are you running? 
I download a ZIP file from the Github Code tab (green button)

#### Release or downloaded from Git? 
Yes.

#### WAMP or LAMP? 
LAMP 

### What version of PHP and MySQL are you running
10.0.38-MariaDB-0ubuntu0.16.04.1
PHP Version 7.0.33-0ubuntu0.16.04.16

I had been installing my own database from past versions of CATS, so today, I dropped that database, and reinstalled OpenCATS with a fresh clean database, and it will got the HTML Error 500. 

In past discussions, people made reference to the use of composer. Is that documented anywhere? Is there new installation instructions?

**Comment by Alt37** [comment]
Ubuntu 16.04 is now EOL.
Currently you need to get some newer Ubuntu LTS or Debian Stable version and install PHP 7.2 from [repository](https://deb.sury.org/#php-packages)

Example for Ubuntu 18.04/20.04:
`sudo add-apt-repository ppa:ondrej/php`
`sudo apt install php7.2 php7.2-soap php7.2-ldap php7.2-mysql php7.2-gd php7.2-xml php7.2-curl php7.2-mbstring php7.2-zip`

**Comment by zoomiest2** [comment]
Thank you. That worked.

**Comment by menatito** [comment]
<html>
<body>
<span id="subFormBlock" style="color: rgb(0, 0, 0); font: 9pt Arial, Tahoma, sans-serif; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(241, 243, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Antiword binary public_html/mycv/antiword does not exist.
--
Pdftotext binary public_html/mycv/pdftotext does not exist.
Html2Text binary public_html/mycv/html2text does not exist.
UnRTF depends on Html2Text and can not execute.

</span><span style="color: rgb(0, 0, 0); font-family: Arial, Tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(241, 243, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div id="testFailed" style="color: rgb(0, 0, 0); font-family: Arial, Tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(241, 243, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by RussH** [comment]
These are external dependencies that have to be manually installed

**Comment by shantadam** [comment]
Hello menatito,

You will need to provide more insights, as such:

  *   Are you following the online documentation for installation?
  *   Are you using the automated installation script or the installation wizard?
  *   Are you hosting the app locally, on a cloud platform, or with a service provider?
  *   Is your hosting tech stack XAMP or LAMP?
  *   Which operating system are you using and its version?
  *   Are you using MySQL or Maria, and which version?
  *   Which version of Apache and PHP are you using?
  *   Do you have SSH access to the host server?
  *   Please describe your installation steps taken before reaching the blocker.
  *   Did you modify anything after the installation? If so, what?

Thank you.

Regards,
Shant Adam

From: menatito ***@***.***>
Date: Sunday, February 13, 2022 at 4:48 AM
To: opencats/OpenCATS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [opencats/OpenCATS] Not installing (#553)

when i login
show me this error and the system dont work
Query Error -- Report to System Administrator ASAP

MySQL Query Failed: Illegal mix of collations for operation 'UNION'

SELECT SQL_CALC_FOUND_ROWS
activity.activity_id AS activityID,
activity.data_item_id AS dataItemID,
activity.data_item_type AS dataItemType,
activity.site_id AS siteID,
data_item_type.short_description AS item,
candidate.first_name AS firstName,
candidate.last_name AS lastName,
candidate.phone_work AS workPhone,
candidate.phone_cell AS cellPhone,
candidate.phone_home AS otherPhone,
candidate.is_hot AS isHot,
joborder.is_hot AS jobIsHot,
company.is_hot AS companyIsHot,
company.company_id AS companyID,
activity.joborder_id AS jobOrderID,
activity.notes AS notes,
activity_type.short_description AS typeDescription,
DATE_FORMAT(DATE_ADD(
activity.date_created, INTERVAL 8 HOUR), '%m-%d-%y %h:%i %p'
) AS dateCreated,
activity.date_created AS dateCreatedSort,
entered_by_user.first_name AS enteredByFirstName,
entered_by_user.last_name AS enteredByLastName,
CONCAT(entered_by_user.last_name, entered_by_user.first_name) AS enteredBySort,
IF(ISNULL(joborder.title),
'General',
CONCAT(joborder.title, ' (', company.name, ')'))
AS regarding,
joborder.title AS regardingJobTitle,
company.name AS regardingCompanyName
FROM
activity
JOIN data_item_type
ON activity.data_item_type = data_item_type.data_item_type_id
LEFT JOIN user AS entered_by_user
ON activity.entered_by = entered_by_user.user_id
LEFT JOIN activity_type
ON activity.type = activity_type.activity_type_id
LEFT JOIN joborder
ON activity.joborder_id = joborder.joborder_id
LEFT JOIN company
ON joborder.company_id = company.company_id
INNER JOIN candidate
ON activity.data_item_id = candidate.candidate_id
WHERE
activity.data_item_type = 100
AND
activity.entered_by = 1
AND
activity.site_id = 1
AND activity.date_created >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH)

        UNION

        SELECT

            activity.activity_id AS activityID,

            activity.data_item_id AS dataItemID,

            activity.data_item_type AS dataItemType,

            activity.site_id AS siteID,

            data_item_type.short_description AS item,

            contact.first_name AS firstName,

            contact.last_name AS lastName,

            contact.phone_work AS workPhone,

            contact.phone_cell AS cellPhone,

            contact.phone_other AS otherPhone,

            contact.is_hot AS isHot,

            joborder.is_hot AS jobIsHot,

            company.is_hot AS companyIsHot,

            company.company_id AS companyID,

            activity.joborder_id AS jobOrderID,

            activity.notes AS notes,

            activity_type.short_description AS typeDescription,

            DATE_FORMAT(DATE_ADD(

                activity.date_created, INTERVAL 8 HOUR), '%m-%d-%y %h:%i %p'

            ) AS dateCreated,

            activity.date_created AS dateCreatedSort,

            entered_by_user.first_name AS enteredByFirstName,

            entered_by_user.last_name AS enteredByLastName,

            CONCAT(entered_by_user.last_name, entered_by_user.first_name) AS enteredBySort,

            IF(ISNULL(joborder.title),

                'General',

                CONCAT(joborder.title, ' (', company.name, ')'))

            AS regarding,

            joborder.title AS regardingJobTitle,

            company.name AS regardingCompanyName

        FROM

            activity

        JOIN data_item_type

            ON activity.data_item_type = data_item_type.data_item_type_id

        LEFT JOIN user AS entered_by_user

            ON activity.entered_by = entered_by_user.user_id

        LEFT JOIN activity_type

            ON activity.type = activity_type.activity_type_id

        LEFT JOIN joborder

            ON activity.joborder_id = joborder.joborder_id

        LEFT JOIN company

            ON joborder.company_id = company.company_id

        INNER JOIN contact

            ON activity.data_item_id = contact.contact_id

        WHERE

            activity.data_item_type = 300

        AND

            activity.entered_by = 1

        AND

            activity.site_id = 1

             AND activity.date_created >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH)





        ORDER BY dateCreatedSort DESC

        LIMIT 6
