### ISSUE TITLE
please help..not installing and after wizard setup..blank page

### ISSUE THREAD

**Issue by sshheerr** [opencats/OpenCATS#554]
Warning: include_once(./vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\master\lib\TemplateUtility.php on line 38

Warning: include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\master\lib\TemplateUtility.php on line 38

Warning: require(./vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\master\lib\Mailer.php on line 43

Fatal error: require(): Failed opening required './vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\master\lib\Mailer.php on line 43

**Comment by sshheerr** [comment]
I uploaded my sql table and and it went fine, the funny thing is CATS 5.0 worked very good, but this version, I cant seem to get around it. Any help please.

**Comment by RussH** [comment]
Hi, 

please use the full install zip file https://github.com/opencats/OpenCATS/releases/download/0.9.6/opencats-0.9.6-full.zip

..and delete the install_block directory before installing

..this package includes all the required dependencies
