### ISSUE TITLE
Is there new Installation Docs (including PHPMailer & Composer)?

### ISSUE THREAD

**Issue by zoomiest2** [opencats/OpenCATS#556]
I installed the latest stable, FULL version (including dependencies), and then started messing around with PHPMailer to get my E-mail notifications working (not working yet), and delved into installing composer. Not working yet.

But, I see that the vendor directory seems to have copies of PHPMailer and Composer within. Are these supposed to operate without intervention during installation?

**1)** Is there a set of installation instructions that include installation activities and validation tests with PHPMailer and Composer? I am still going off of these [original instructions](https://opencats-documentation.readthedocs.io/en/latest/Install-Ubuntu-16.04.html).

**2)** I have PHP 7.2 installed, as per directions (currently 7.2.34-28), but when I updated my dependencies with Composer, now my opencats pages aren't viewable (HTTP error 500). I am tempted to reinstall.

**Comment by RussH** [comment]
Hi @zoomiest2  I'll update the (new!) documentation to be clear - there are always two different options when you download the release. There's the archive with a -FULL suffix which already has the dependencies (phpmailer, ckeditor, etc) and a smaller archive that doesn't have the dependencies, and you use composer to pull down the dependencies and install them.
