### ISSUE TITLE
Opencats v9.6 not displaying candidate or job orders lists

### ISSUE THREAD

**Issue by ronswift2** [opencats/OpenCATS#557]
### Expected behavior and actual behavior.
When selecting Job Orders or Candidates list it show a list of jobs or candidates and it does not. I restored the database and attachments from a v9.4 system that we were running. 
### Steps to reproduce the problem.
Install v9.6 as new install and then import saved sql file and attachments from v9.4 
### What version of opencats are you running? 
Version 9.6
#### Release or downloaded from Git? 
Downloaded from Git
#### WAMP or LAMP? 
LAMP on Ubuntu 20.04 server
### What version of PHP and MySQL are you running
Php 7.2.34 MySQL 8.0.27
### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
There are no errors in the apache2/mysql logs nor are any errors shown on the application screens
![Screenshot from 2021-12-15 15-01-38](https://user-images.githubusercontent.com/39599323/146258123-4ace7790-b6c9-4254-b51e-ceae03a36d79.png)
![Screenshot from 2021-12-15 15-12-42](https://user-images.githubusercontent.com/39599323/146258274-1c4755d9-126a-4e27-b0d3-636107868f34.png)
.

**Comment by arorapuneet29** [comment]
same even I am facing same issue

**Comment by RussH** [comment]
Hi both,

please use MariaDB10 and not MySQL 8. There is now divergence seen between
MySQL and MariaDB behaviour, and we are testing only with MariaDB.


----
Russ

**Comment by ronswift2** [comment]
It worked. Hopefully others can benefit from my experience. Thanks

**Comment by vikash-del** [comment]
Hi,
I have converted the database to mariaDB10, but its throwing some warnings.
<img width="938" alt="issue" src="https://user-images.githubusercontent.com/61985764/146875068-ea35852d-40fd-4381-b9c8-b768bccc5df7.PNG">

How to rectify these warnings.

**Comment by shantadam** [comment]
If I may jump-in with my important advice, Vikash,

It’s important to install the application’s 3rd party libraries to enable all required features.

Instructions:

  1.  Ensure you have Composer installed from https://getcomposer.org/download/ .
  2.  After completing Composer installation, open a command line terminal.
  3.  Navigate using command line to <youropencatsfolder>.
  4.  Next, type “composer install” and hit enter button to initiate the Composer library installation.
  5.  Once the 3rd party libraries are installed, reload your application’s browser page.

Let me know if that resolves your issue.

Cheers,
Shant Adam

From: vikash-del ***@***.***>
Date: Monday, December 20, 2021 at 9:14 PM
To: opencats/OpenCATS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [opencats/OpenCATS] Opencats v9.6 not displaying candidate or job orders lists (Issue #557)

Hi,
I have converted the database to mariaDB10, but its throwing some warnings.
[issue]<https://user-images.githubusercontent.com/61985764/146875068-ea35852d-40fd-4381-b9c8-b768bccc5df7.PNG>

How to rectify these warnings.

**Comment by edtaaffe** [comment]
Just noticed the comments above re installing Composer etc.
Does this mean that installing on shared hosting like godaddy is unlikely to work?

**Comment by RussH** [comment]
In the release page you'll find different packages, done with all the dependencies bundled (don't need to run composers) or smaller packages that will need composer run. If you need all the dependencies bundled, get the larger packages.

**Comment by edtaaffe** [comment]
Thanks Russ.
