### ISSUE TITLE
Issue's when restoring from backup on .9.4 to .9.6

### ISSUE THREAD

**Issue by riiwjohnson** [opencats/OpenCATS#559]
### Expected behavior and actual behavior.
Expecting all users to work, but all users are inactive when restoring from backup.  
### Steps to reproduce the problem.

- Start new install of 0.9.6
- Create restore directory
- Upload catsbackup.bak
- Restore from backup

### What version of opencats are you running? 
0.9.6
#### Release or downloaded from Git? 
Release
#### WAMP or LAMP? 
LAMP
### What version of PHP and MySQL are you running
7.4.25 /  MariaDB 10.3.17

**Comment by RussH** [comment]
Versions of PHP above PHP 7.2 are not supported and will not function!
