### ISSUE TITLE
another issue when i login

### ISSUE THREAD

**Issue by menatito** [opencats/OpenCATS#561]
when i login
show me this error and the system dont work
Query Error -- Report to System Administrator ASAP

MySQL Query Failed: Illegal mix of collations for operation 'UNION'

SELECT SQL_CALC_FOUND_ROWS
activity.activity_id AS activityID,
activity.data_item_id AS dataItemID,
activity.data_item_type AS dataItemType,
activity.site_id AS siteID,
data_item_type.short_description AS item,
candidate.first_name AS firstName,
candidate.last_name AS lastName,
candidate.phone_work AS workPhone,
candidate.phone_cell AS cellPhone,
candidate.phone_home AS otherPhone,
candidate.is_hot AS isHot,
joborder.is_hot AS jobIsHot,
company.is_hot AS companyIsHot,
company.company_id AS companyID,
activity.joborder_id AS jobOrderID,
activity.notes AS notes,
activity_type.short_description AS typeDescription,
DATE_FORMAT(DATE_ADD(
activity.date_created, INTERVAL 8 HOUR), '%m-%d-%y %h:%i %p'
) AS dateCreated,
activity.date_created AS dateCreatedSort,
entered_by_user.first_name AS enteredByFirstName,
entered_by_user.last_name AS enteredByLastName,
CONCAT(entered_by_user.last_name, entered_by_user.first_name) AS enteredBySort,
IF(ISNULL(joborder.title),
'General',
CONCAT(joborder.title, ' (', company.name, ')'))
AS regarding,
joborder.title AS regardingJobTitle,
company.name AS regardingCompanyName
FROM
activity
JOIN data_item_type
ON activity.data_item_type = data_item_type.data_item_type_id
LEFT JOIN user AS entered_by_user
ON activity.entered_by = entered_by_user.user_id
LEFT JOIN activity_type
ON activity.type = activity_type.activity_type_id
LEFT JOIN joborder
ON activity.joborder_id = joborder.joborder_id
LEFT JOIN company
ON joborder.company_id = company.company_id
INNER JOIN candidate
ON activity.data_item_id = candidate.candidate_id
WHERE
activity.data_item_type = 100
AND
activity.entered_by = 1
AND
activity.site_id = 1
AND activity.date_created >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH)

        UNION
        SELECT 
            activity.activity_id AS activityID,
            activity.data_item_id AS dataItemID,
            activity.data_item_type AS dataItemType,
            activity.site_id AS siteID,
            data_item_type.short_description AS item,
            contact.first_name AS firstName,
            contact.last_name AS lastName,
            contact.phone_work AS workPhone,
            contact.phone_cell AS cellPhone,
            contact.phone_other AS otherPhone,
            contact.is_hot AS isHot,
            joborder.is_hot AS jobIsHot,
            company.is_hot AS companyIsHot,
            company.company_id AS companyID,
            activity.joborder_id AS jobOrderID,
            activity.notes AS notes,
            activity_type.short_description AS typeDescription,
            DATE_FORMAT(DATE_ADD(
                activity.date_created, INTERVAL 8 HOUR), '%m-%d-%y %h:%i %p'
            ) AS dateCreated,
            activity.date_created AS dateCreatedSort,
            entered_by_user.first_name AS enteredByFirstName,
            entered_by_user.last_name AS enteredByLastName,
            CONCAT(entered_by_user.last_name, entered_by_user.first_name) AS enteredBySort,
            IF(ISNULL(joborder.title),
                'General',
                CONCAT(joborder.title, ' (', company.name, ')'))
            AS regarding,
            joborder.title AS regardingJobTitle,
            company.name AS regardingCompanyName
        FROM
            activity
        JOIN data_item_type
            ON activity.data_item_type = data_item_type.data_item_type_id
        LEFT JOIN user AS entered_by_user
            ON activity.entered_by = entered_by_user.user_id
        LEFT JOIN activity_type
            ON activity.type = activity_type.activity_type_id
        LEFT JOIN joborder
            ON activity.joborder_id = joborder.joborder_id
        LEFT JOIN company
            ON joborder.company_id = company.company_id
        INNER JOIN contact
            ON activity.data_item_id = contact.contact_id
        WHERE
            activity.data_item_type = 300
        AND
            activity.entered_by = 1
        AND
            activity.site_id = 1
             AND activity.date_created >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH) 
            
        
        ORDER BY dateCreatedSort DESC
        LIMIT 6

**Comment by RussH** [comment]
so I need issues raised with the template, as this may be a MariaDB/MySQL version issue. 

### Expected behavior and actual behavior.

### Steps to reproduce the problem.

### What version of opencats are you running? 

#### Release or downloaded from Git? 

#### WAMP or LAMP? 

### What version of PHP and MySQL are you running

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
