### ISSUE TITLE
0.9.4

### ISSUE THREAD

**Issue by mselavarasan** [opencats/OpenCATS#564]
Hi,
We are using OpenCATS 0.9.4 however, understand that, there is a security patch for this version.
So how to procced to security patch for my existing version 0.9.4 to 0.9.4-3?

My Environment:
LAMP [CentOS v7, Apache v2.4.x, MySQL 5.7.x & PHP v5.6.40]

Thank you,
Ela

**Comment by RussH** [comment]
Hi, to fully secure the system you really need to be on 0.9.6 which is a major upgrade and will involve upgrading PHP and MariaDB. I would suggest copying your application/database to a test server(or PC) and then working through the upgrade in the test environment.
