### ISSUE TITLE
Candidate data not showing in Joborder

### ISSUE THREAD

**Issue by sidsingh1001** [opencats/OpenCATS#569]
#Not able to see candidate data in Joborder and Lists
**Expected behavior and actual behavior.**
Assigned candidates to a specific job order. When i go to details in the joborder the candidates assigned should show at the bottom of the page. The report graph shows that there are candidates assigned to the JobOrder but the table where the candidates should be shown is not populated.

**What version of opencats are you running?**
my OPenCats version is 0.9.6
Release downloaded from GIT

**Version of PHP and MySQL**
PHP version is 7.3.32
MySQL version is 5.6.43

**Hosted on** 
Godaddy shared hosting LAMP

Data is available in the table candidate_joborder (i did check that.)

<img width="911" alt="Issue" src="https://user-images.githubusercontent.com/106084367/180385079-d21be761-61bd-470f-a563-bf7e708acc1e.png">

**Comment by RussH** [comment]
I've just verified that MariaDB 10.6 works fine, the 'latest' MariaDB 10.8 does not. You need to use MariaDB with a maximum of 10.6
