### ISSUE TITLE
Dev and Prod on same machine

### ISSUE THREAD

**Issue by MCVitzz** [opencats/OpenCATS#579]
Hello,

I don't know if this is the right place to ask this kind of question, but I didn't know where else to ask it.

Can I have a development and production environment on the same machine?

I'm using Ubuntu

Thank you very much for all the help!

**Comment by RussH** [comment]
Hi @MCVitzz sure you can have prod and dev environments on the same host - either traditionally with two copies installed in different directories (i.e. /var/www/html/dev and /var/www/html/prod) with two separate databases, or using Docker to host test
