### ISSUE TITLE
Use fluid width pages

### ISSUE THREAD

**Issue by libregeek** [opencats/OpenCATS#58]
OpenCATS uses fixed width pages (1024x768 resolution) which doesn't looks good in wide screens. The fixed width should be changed to fluid width so that the application utilized available screen space and reduces vertical scrolling.
![selection_410](https://cloud.githubusercontent.com/assets/145110/13346128/24536430-dc8a-11e5-8e42-19290f52c230.png)

**Comment by mlespiau** [comment]
Hi @libregeek, would you consider this issue fixed since my last PR?

**Comment by amaisonneuve** [comment]
I took a look and the changes are clean I have yet to merge into my repo, but I think it should be safe.

Cheers,
Alain
