### ISSUE TITLE
demo site is down

### ISSUE THREAD

**Issue by maxadamo** [opencats/OpenCATS#585]
The link in your home page doesn't work:  [demo.opencats.org](http://demo.opencats.org/)

**Comment by mazharqayyum** [comment]
This indeed is very annoying and needs to be fixed. It seems to be broken for few months now.

**Comment by RussH** [comment]
Not broken  - by design. Will be replaced once travis-ci builds are fixed.

**Comment by ralyodio** [comment]
still down.
