### ISSUE TITLE
Access array offset on value of type bool in [Add.tpl on line 193]

### ISSUE THREAD

**Issue by bernardo-campos** [opencats/OpenCATS#594]
### Expected behavior and actual behavior.
On candidates > Add candidate
a warning is shown below Home Phone:
**Notice:** Trying to access array offset on value of type bool in C:\xampp\htdocs\opencats096\modules\candidates\Add.tpl on line 192
corresponds to the line
`<?php if ($this->parsingStatus['parseLimit'] >= 0 && $this->parsingStatus['parseUsed'] >= $this->parsingStatus['parseLimit']): ?>`
I made a var dump of `$this->parsingStatus` and the result is `bool(true`)

### Steps to reproduce the problem.
Download Opencats release 0.9.6
Remove Install_block folder
create database and config
log in with admin/admin
go to option Candidates > Add candidate

### What version of PHP and MySQL are you running
PHP 7.4.6
MariaDB 10.4.11

**Comment by RussH** [comment]
Short answer is only php 7.2 odd supported.
