### ISSUE TITLE
Important Candidates ( BUG )

### ISSUE THREAD

**Issue by anatechRepositories** [opencats/OpenCATS#603]
On dashboard, Important Candidates section, when click on next.
All the candidates list gone.

I'm upgrading by using database transfer, old version to new one.

OpenCATS Version 0.9.7.2

Release

CPanel web hosting

7.4

**Comment by RussH** [comment]
Hi @anatechRepositories 

Firstly, this needs to be on v7.2 latest and not 7.4.
Secondly - the behaviour you describe is if you install the source package and have not run composer to pull in the php dependencies. 

Please either reinstall the -FULL package in releases or run composer as per the link below;
https://documentation.opencats.org/#which-package-to-install
