### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by michaelcollis11** [opencats/OpenCATS#609]
Hi, When i'm trying to install open cats i see the following error 
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\OpenCats\lib\CATSUtility.php on line 108

It does not allow me to move on with the installation 

Thanks,

**Comment by lolalilelu** [comment]
I have the same issue. I've read the documentation and other posts talking about it, I don't understand any of it, I'm merely following the guide step by step. What do I need to do to fix this? Thanks.

**Comment by RussH** [comment]
Hi @lolalilelu the current version 0.9.7.2 only supports PHP 7.2. I suspect you're trying to install on PHP 7.4 or above.. as this will generate a similar sounding error. 

Please downgrade PHP to v7.2 and retry the installation.

**Comment by michaelcollis11** [comment]
@lolalilelu yeah I had that issue I had to downgrade to an older version of php. If you’re using windows which I am. Easiest way is to download an older version of xmapp which has the requested version of php needed, you may also notice when you enable careers portal there it will come up blank. But there is an easy fix to resolve that. Drop a message back here and I can tell you how to resolve that
