### ISSUE TITLE
Careers Page Blank

### ISSUE THREAD

**Issue by michaelcollis11** [opencats/OpenCATS#610]
Good Morning, 

I have successfully installed OpenCats, we have enabled web portal for careers but when we click the link it comes up blank Unsure if there are any settings that need to be changed to allow this 

Thanks
![Capture](https://user-images.githubusercontent.com/129226869/228812890-1e430435-b0fd-4bf3-8c07-18972671973b.PNG)

**Comment by RussH** [comment]
Hi Michael, am assuming this is a xampp issue only-as i don't see it on Linux.  Can you share hope you resolved it please?

**Comment by michaelcollis11** [comment]
Sure Can - I got it from another post - But added the step by step to my FAQ on our system 

Got to the following file location C:\xampp\htdocs\OpenCats\careers open careers.php In notepad ++ and add the following line at the end of chdir('..');
include_once('./'.CATSUtility::getIndexName());

Restart the services - and try opening careers page 

Hope this helps
