### ISSUE TITLE
Getting Blank Screen after installing OpenCATS 9.7.2

### ISSUE THREAD

**Issue by zoomiest2** [opencats/OpenCATS#614]
### Expected behavior and actual behavior.
- I installed OpenCATS as per normal instructions, and after I click "Start OpenCATS" I get a blank screen. I have installed this ats many times. I am expecting to see the tabs. 
- I have reviewed the posts in the help forum, and others have had this problem, but no solution has been proposed.
- In the logs, there are a bunch of files that fail to open. How can we configure OpenCATS to open those?

### Steps to reproduce the problem.
- Install CATS. Click Start OpenCATS

### What version of opencats are you running? 
- 0.9.7.2

#### Release or downloaded from Git? 
- Link from Git "latest"

#### WAMP or LAMP? 
- Ubuntu Server 22.04.2 LTS

### What version of PHP and MySQL are you running
- PHP Version 7.2.34-38+ubuntu22.04.1+deb.sury.org+1
- MariaDB 10.6.12

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
- MySQL logs: empty

-  PHP errors Displayed:

> Warning: include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vcats/lib/TemplateUtility.php on line 38

> Warning: include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/vcats/lib/TemplateUtility.php on line 38

> Warning: include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vcats/lib/Companies.php on line 2

> Warning: include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/vcats/lib/Companies.php on line 2

> Warning: require(./vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vcats/lib/Mailer.php on line 43

> Fatal error: require(): Failed opening required './vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/vcats/lib/Mailer.php on line 43

- Apache2 Logs: See below:

Mon May 01 14:01:07.994793 2023] [core:notice] [pid 32955] AH00094: Command line: '/usr/sbin/apache2'
[Mon May 01 14:09:50.984388 2023] [php7:warn] [pid 32958] [client 23.17.234.209:42368] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vcats/lib/TemplateUtility.php on line 38, referer: http://216.158.225.210/vcats/index.php
[Mon May 01 14:09:50.984454 2023] [php7:warn] [pid 32958] [client 23.17.234.209:42368] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/vcats/lib/TemplateUtility.php on line 38, referer: http://216.158.225.210/vcats/index.php
I can't find the name of your HOME directory
I can't find the name of your HOME directory
I can't find the name of your HOME directory
[Mon May 01 14:12:18.800543 2023] [php7:warn] [pid 32960] [client 23.17.234.209:58624] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vcats/lib/TemplateUtility.php on line 38, referer: http://216.158.225.210/vcats/installwizard.php
[Mon May 01 14:12:18.800612 2023] [php7:warn] [pid 32960] [client 23.17.234.209:58624] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/vcats/lib/TemplateUtility.php on line 38, referer: http://216.158.225.210/vcats/installwizard.php
[Mon May 01 14:12:18.817643 2023] [php7:warn] [pid 32960] [client 23.17.234.209:58624] PHP Warning:  include_once(./vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vcats/lib/Companies.php on line 2, referer: http://216.158.225.210/vcats/installwizard.php
[Mon May 01 14:12:18.817685 2023] [php7:warn] [pid 32960] [client 23.17.234.209:58624] PHP Warning:  include_once(): Failed opening './vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/vcats/lib/Companies.php on line 2, referer: http://216.158.225.210/vcats/installwizard.php
[Mon May 01 14:12:18.820159 2023] [php7:warn] [pid 32960] [client 23.17.234.209:58624] PHP Warning:  require(./vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vcats/lib/Mailer.php on line 43, referer: http://216.158.225.210/vcats/installwizard.php
[Mon May 01 14:12:18.820180 2023] [php7:error] [pid 32960] [client 23.17.234.209:58624] PHP Fatal error:  require(): Failed opening required './vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/vcats/lib/Mailer.php on line 43, referer: http://216.158.225.210/vcats/installwizard.php
root@vps2667486:/var/log/apache2# 

**So, I commented out the fatal error: required: './vendor/autoload.php' (and now it opened)
Is that bad?**

**Comment by zoomiest2** [comment]
So, I commented out the fatal error: required: './vendor/autoload.php' (and now it opened)

Is that bad?

**Comment by zoomiest2** [comment]
So I went to the location of the error and commented out the reference that is causing problems, and the index.php opened.

Specifically:
/var/www/html/vcats/lib/Mailer.php on line 43
/var/www/html/vcats/lib/Companies.php on line 2
/var/www/html/vcats/lib/TemplateUtility.php on line 38

There isn't an existing ./vendor/autoload.php file. 

What this put in by composer in development?

**Comment by RussH** [comment]
Hi Zoomiest. 
If you download latest from git, then the dependencies aren't packaged,  you need to use composer to pull in the dependencies. Documented here (https://documentation.opencats.org/#which-package-to-install)

so you need to go and find composer, install it, run it, then all will be good.

Alternatively - just use the release which already has the dependencies  packaged

**Comment by zoomiest2** [comment]
Thank you.
Everything worked when I used the stable release.
