### ISSUE TITLE
Array and string offset access syntax error

### ISSUE THREAD

**Issue by T2PAE** [opencats/OpenCATS#616]
To install OpenCats on my laptop, I prepared my system by downloading & installing XAMPP. I launched phpMyAdmin, granted all privileges on database opencats then clicked go. It looked like it worked however once I went to install OpenCATS software and went to the localhost/opencats and clicked on the installation wizard, it gave me a fatal error.

Fatal Error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\OpenCATS\lib\CATSUtility.php on line 108

Can you please let me know what's the best way to fix this syntax error. Thanks (Russ let me know to use PHP 7.2, where exactly do I find this version??)

When I installed XAMPP I didn't see a XAMPP that had a PHP 7.2 version. I installed XAMPP V64-8.0.28.0-VS16-installer.exc
Since I already have XAMPP on my computer can I just download a PHP 7.2 or do I have to take off the XAMPP and start over??

**Comment by RussH** [comment]
Hi T2PAE, sorry but I don;t use XAMPP myself. I think you should install a PHP 7.2 version of XAMPP  and retry the opencats application? If that doesn't work it's wipe it out  and start again.

**Comment by T2PAE** [comment]
Ok, thank you Russ. I'll look for the version and download it and try it.

Thanks again,
Donna
