### ISSUE TITLE
Timeout on AJAX Query after 70 seconds. Please refresh the page and try again.

### ISSUE THREAD

**Issue by mselavarasan** [opencats/OpenCATS#624]
### Expected behavior
The expected behaviors' supposed to export the results in CSV format

### Actual behavior.
The actual bahavior is "**_Timeout on AJAX query after 70 seconds. Please refresh the page and try again"_** 

### Steps to reproduce the problem.
1.	Login OpenCATS with the admin credential
2.	Go to "**_Job Orders_**" Tab
3.	Select a "_**Title**_"
4.	Under "**_Candidate Pipeline_**" section
5.	Click "**_Export_**"

### What version of opencats are you running? 
CATS Version 0.9.4 Countach

#### Release or downloaded from Git? 
It was download from the GIT

#### WAMP or LAMP? 
Using with LAMP

### What version of PHP and MySQL are you running
PHP v5.6 and MySQL v5.7

**Comment by mselavarasan** [comment]
As a workaround for the above AJAX Timeout,

Steps:
1. Go to lib folder
2. Open js file
3. look for  var AJAX_TIMEOUT =********; increase the value as much as based on your requirements
4. Look for Timeout function and adjust, if required
![1a3587ab-1486-47b7-bd1c-b67ecfcfcfd2](https://github.com/opencats/OpenCATS/assets/35727098/a2b0b941-94ed-4fa7-ae04-b9930d8ce65d)

Thank you,
Ela

**Comment by RussH** [comment]
Yes, I suspect your export is quite large! Good catch.
