### ISSUE TITLE
Missing User login

### ISSUE THREAD

**Issue by Fullhouser** [opencats/OpenCATS#628]
I installed this ATS.

But there is not a single step during the installation to create a user.

Which credentials to use to connect?

Database and Email credentials (from install steps) are not working

**Comment by Fullhouser** [comment]
It's 

user: admin
pass: admin

**Comment by RussH** [comment]
Hi, 

that's already in the documentation but I did go & check!
"The default username and password for your new install is : admin/admin (all lowercase)"
