### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by raghuramanc** [opencats/OpenCATS#64]
I installed the CATS using php and wampserver on my laptop and it was working well. when i logged out and tried to login again am unable to login. Pls help. Attched the screenshot.

![capture](https://cloud.githubusercontent.com/assets/19236700/15091275/7036d44a-1461-11e6-84af-938a189d5b5b.JPG)
When i click reset nothing seems to happen.

**Comment by libregeek** [comment]
Do you still have this issue?

**Comment by raghuramanc** [comment]
Hello,

Yes pls.



Many thanks,

Best regards,
Plus Consulting

**Comment by libregeek** [comment]
I'm not sure which version you are using, but there is a recent issue on the default password. Please check whether it's applicable to you. https://github.com/opencats/OpenCATS/issues/53

**Comment by RussH** [comment]
User issue, not problem with the codebase. Please can you request support via the opencats.org forums.
