### ISSUE TITLE
Data Import Functionality Issue

### ISSUE THREAD

**Issue by logiclawyers** [opencats/OpenCATS#65]
RELEASE: OpenCATS-Master as of May 10, 2016

SUMMARY: Without a "temp" directory in the opencats root, the migration import functionality available within "Settings"-->"Administration"-->"Data Import" will not work.

ISSUE: The latest "OpenCATS-Master" (as of May 10, 2016) does not contain a "temp" directory, thus causing data migration to fail.

MY SETUP:
Operating System:   Linux OpenCATS 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) i686
Operating System Type:  CATS thinks your operating system is UNIX.
PHP Version:    5.6.20-0+deb8u1
Database Version:   MySQL 5.5.49-0+deb8u1
Installation Directory: /var/www/html/opencats

SOLUTION/FIX:
Create the directory, apply the appropriate ownership and permissions as described in the installation guide, and it'll then work fine:

As a superuser...

> mkdir /var/www/html/opencats/temp
> chown www-data:www-data /var/www/html/opencats/temp
> chown -R www-data:www-data /var/www/html/opencats/temp

The above assumes a working knowledge of *nix, sudo, etc.

Cheers,

Dave

**Comment by mlespiau** [comment]
I can confirm the same issue.

The fix proposed like Dave worked like a charm :)

**Comment by RussH** [comment]
Hi @logiclawyers closing this issue as a fix was committed in #258
