### ISSUE TITLE
Editing joborder status causes system crash

### ISSUE THREAD

**Issue by ichris007** [opencats/OpenCATS#657]
### Expected behavior and actual behavior.
I want to edit the status of the joborder:
1. From **Active** to **On Hold** (Some joborders can be modified successfully, some modifications cause the system to crash)
2. Or, check the box to become **HOT** status (No joborder has ever succeeded in checking the **HOT** box.)
Both of these actions can cause the system crash

### Steps to reproduce the problem.
<img width="807" alt="iShot_2024-07-08_20 02 58" src="https://github.com/opencats/OpenCATS/assets/30898935/87388bfb-acbe-418d-84f7-50ce2dc92e97">
<img width="1313" alt="iShot_2024-07-08_20 07 51" src="https://github.com/opencats/OpenCATS/assets/30898935/525f8f6f-650a-4ae3-abd6-3204d2dd1a69">

### What version of opencats are you running? 
OpenCATS Version 0.9.7.4

#### Release or downloaded from Git? 
yes

#### WAMP or LAMP? 
Synology DSM 7.2 Web Station

### What version of PHP and MySQL are you running
PHP 7.4 
MariaDB 10

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
<img width="1313" alt="iShot_2024-07-08_20 07 51" src="https://github.com/opencats/OpenCATS/assets/30898935/d6179bfc-43e7-41ec-8c54-3615518614b3">

**Comment by RussH** [comment]
HI @ichris007 for that release, the maximum supported version of PHP is PHP 7.2;

_"The main dependencies for this software are PHP and MariaDB. PHP 7.2 and MariaDB 10.6 are the most recent versions supported. Higher levels may work, but are untested"_

So initially - please downgrade and retry. If you still have errors, please share the errors from your apache  error.log and access.log (or nginx equivalent)

**Comment by ichris007** [comment]
@RussH thanks for your response. I will downgrade php to 7.2.
