### ISSUE TITLE
asp File in module

### ISSUE THREAD

**Issue by jaychaube** [opencats/OpenCATS#69]
asp file in module is empty so the file cannot be redirected to the ElementITMultiPowUpload1.7.swf

**Comment by RussH** [comment]
'professional features' are enabled after a filecheck for asp or an asp directory. Therefore as there's no ASP module, there's an empty file called 'asp'. you can replace this with the directory you want if you need it, **but it will give you no additional features.**

**Comment by jaychaube** [comment]
I have change the path of the directory but still show that . Element
multiple upload.swf not found...

**Comment by jaychaube** [comment]
If you can provide me soution i would be very thank full to u.
