### ISSUE TITLE
To unify documentation for installation

### ISSUE THREAD

**Issue by skrchnavy** [opencats/OpenCATS#76]
There are 2 pages describing installation steps:
- https://github.com/opencats/OpenCATS/wiki/Install-on-Windows-Tutorial from part: Step 1 System Connectivity
- https://github.com/opencats/OpenCATS/wiki/Install-on-Linux-Tutorial.--Centos7,-Debian8-and-Ubuntu16.06#install-the-opencats-software

I propose to create extra wiki page with common steps, which can be reused in particular installation manuals.

_Motivation: to create docker installation steps without common part._

**Comment by RussH** [comment]
Closed as Duplicate of #97
