### ISSUE TITLE
Cannot import any data. New Unit test?

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#86]
after initial setup, the 'data import' facility no longer works, and no candidates, companies, CV's or contacts can be imported. 

Clicking 'upload' just generates the 'uploading graphic; nothing is actually done.

**Comment by RussH** [comment]
Can you add this as a unit test please?

**Comment by RussH** [comment]
I'll check 0.9.1a and will also install the current version on an older version of MySQL / PHP to see where the issue manifests. 

Both the current and initial version of 0.9.2 are affected.

**Comment by mlespiau** [comment]
Sure, i can check it. Will take a look tonight.

**Comment by mlespiau** [comment]
Hi Russ, i've done an initial research on this issue on current branch and I can reproduce the problem as that the temp folder is not created during the installation.

Adding the temp folder fixes the issue. 

Is that the same issue that you were able to reproduce? 

Regardless of that, this situation is being handled by the code and an error should be displayed in the UI, but it's not happening as for now. 

I'll work on a fix and also in understanding why error are not being shown. Let me know if I'm on the right path.

**Comment by RussH** [comment]
Hi Matias , fixed this also when I added the temp folder. Good catch,
couldn't see that.





----
Russ

**Comment by mlespiau** [comment]
Hi @RussH, 

I've done a fix for the issue, please check the comments regarding the unit test and the video attached to the following PR:

https://github.com/opencats/OpenCATS/pull/88

**Comment by RussH** [comment]
Issue fixed..
