### ISSUE TITLE
Issue with showing Profile Picture when changing

### ISSUE THREAD

**Issue by ManuelNL** [opencats/OpenCATS#94]
If you want to change/edit the candidates profile picture in OpenCats it didn't show the current picture. Just a empty square.
The changes you have to make are minor.

You have to edit the file: ...\modules\candidates\CreateImageAttachmentModal.tpl

At line 12 and 13 you wil find:

<a href="attachments/<?php $this->_($attachmentsData['attachmentID']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>">
<img src="attachments/<?php $this->_($attachmentsData['attachmentID']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>" border="0" width="165">
</a>

Change : attachmentID into directoryName

It will look like this

<a href="attachments/<?php $this->_($attachmentsData['directoryName']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>">
<img src="attachments/<?php $this->_($attachmentsData['directoryName']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>" border="0" width="165">
</a>

The allready changed file:
[CreateImageAttachmentModal.zip](https://github.com/opencats/OpenCATS/files/384000/CreateImageAttachmentModal.zip)

**Comment by RussH** [comment]
Manuel's comments form the forum.. 
If you want to change/edit the candidates profile picture in OpenCats it didn't show the current picture. Just a empty square.
The changes you have to make are minor.

You have to edit the file: ...\modules\candidates\CreateImageAttachmentModal.tpl

At line 12 and 13 you wil find:

```
<a href="attachments/<?php $this->_($attachmentsData['attachmentID']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>">
<img src="attachments/<?php $this->_($attachmentsData['attachmentID']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>" border="0" width="165">
</a>
```

Change : attachmentID into directoryName

It will look like this

```
<a href="attachments/<?php $this->_($attachmentsData['directoryName']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>">
<img src="attachments/<?php $this->_($attachmentsData['directoryName']) ?>/<?php $this->_($attachmentsData['storedFilename']) ?>" border="0" width="165">
</a>
```

Save the file and the problem is solved.

Happy recruiting
