### ISSUE TITLE
To remove duplicated content from doc directory and wiki

### ISSUE THREAD

**Issue by skrchnavy** [opencats/OpenCATS#97]
There are currently 3 places (or more?) where is stored documentation:
- [doc dir in this repo](../tree/master/doc)
- [doc at wiki](../wiki)
- [doc at readthedocs](http://opencats-documentation.readthedocs.io/) / [it's sources](https://github.com/cptr13/OpenCATS_Documentation)

As best I see the readthedocs (thanks @cptr13) and it seems that this is compilation of the 2 previous places.
Proposed is to remove already migrated documentation from those obsolete places and to finalize migration of rest and improve the readthedocs documentation.

**Comment by RussH** [comment]
Yes, @cptr13 did a great job, I'll point the website to the new docs over at readthedocs.org. We did have some discussions up-front to see where the best place would be - as the wiki isn't even as flexible as the old mediawiki. Readthe Docs will do nicely.

**Comment by cptr13** [comment]
Sorry for the ridiculously late response.  I just noticed this.  Going
through everything Wiki, misc docs, etc) is something on my to-do list.  My
intention is to write the documentation, clean up the documentation, then
go through everything OpenCATS and organize and consolidate everything as
much as possible.

Thanks for pointing these out.  I'll be sure to cover those areas when I
get there.  If you spot anything else (anything at all!) Please let me know.

**Comment by mlespiau** [comment]
HI @RussH @cptr13 Let's use readthedocs then. 

Can we move the documentation project inside OpenCATS organization so that admins have permissions to accept and merge PR?

**Comment by mlespiau** [comment]
Just figured I can edit the documentation and it's already part ot OpenCATS org! :)

**Comment by mlespiau** [comment]
We must start pointing out all doc sources to readthedocs :)

**Comment by mlespiau** [comment]
Updated all references to installation and documentation with links to readthedocs. Only pending task is to review doc/ folder in the repo, add the info to readthedocs and close this issue :)

**Comment by mlespiau** [comment]
@cptr13 is this something you could take over?

**Comment by cptr13** [comment]
Yes, sorry for the delayed response.  I'll work on this this weekend.

**Comment by cptr13** [comment]
@skrchnavy @RussH @mlespiau 

So, I'll address these one at a time.  The first thing is the [docs subdirectory](https://github.com/opencats/OpenCATS/tree/master/doc).

Here ate my thoughts, I'd like your opinions please.

Change changelog name to initial_changlog_v_0.9.1.  Do we need to include this?  I can see the value, but I'm not sure if all of this information is useful, or if it's obsolete.  Thoughts?

Remove CATS User quick guide (I will double check to see if any information can be used first)

Reformat and update authors and contributors


OpenCATS Installation procedure(Install.md): Take LDAP section from here, add to current documentation (review and expand later), remove OpenCATS Installation Procedure document

Remove Zip-appnote.txt

Remove examples subfolder

Add updated OpenCATS Documentation pdf.

The docs folder would then include: (updated and reformatted) AUTHORS.txt, initial_changlog_v_0.9.1 (If we want to keep this), OpenCATS-documentation.pdf

I can see the value of either breaking apart or duplicating and including a separate installation document for easier reference.

Thoughts?

**Comment by cptr13** [comment]
> No, let's remove this folder and keep all the documentation in the docs repo! Move changelog as CHANGELOG.md to the root and remove all the rest!

I can see the value of either breaking apart or duplicating and including a separate installation document for easier reference.
It's much harder to maintain, let's keep it on the docs repo and just point people there in the README.md.
> 

Ok, I'm not a developer, but there's always some sort of documentation included with software...what should be included?  Just the current documentation pdf?  or maybe a txt file pointing to the documentation repo, or site or whatever?

**Comment by mlespiau** [comment]
> Ok, I'm not a developer, but there's always some sort of documentation included with software...what should be included? Just the current documentation pdf? or maybe a txt file pointing to the documentation repo, or site or whatever?

A link to the docs in the readme is enough

**Comment by cptr13** [comment]
Works for me...thanks!  I'll work on it this weekend.

**Comment by cptr13** [comment]
Quick update:
Doc folder and everything in it removed.
Authors/Contributors added and updated in current documentation
Changelog renamed to Changelog.MD and moved to main dir
Quickguide, examples dir, install.md, opencats-documentation.pdf, zip-appnote all removed

**Comment by cptr13** [comment]
There are still some wiki pages that need cleaning up.  But I'm going to go ahead and close this.  This is all complete.

**Comment by mlespiau** [comment]
Great job @cptr13!!! Really appreciate it :)
