### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS#98]
the intention was always that any new files (or significantly altered original files) would be completely open-source. The existing files are CPL - a modified version of the Mozilla Public License. Therefore it would be simplest to keep new files as MPL;
https://www.mozilla.org/en-US/MPL/headers/

/\* This Source Code Form is subject to the terms of the Mozilla Public
- License, v. 2.0. If a copy of the MPL was not distributed with this
- file, You can obtain one at http://mozilla.org/MPL/2.0/. */

OR

 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.

OR

With 'original' or 'significantly original'  files using;
- The Original Code is "CATS Standard Edition".
  *
- The Initial Developer of the Original Code is Cognizo Technologies, Inc.
- Portions created by the Initial Developer are Copyright (C) 2005 - 2007
- (or from the year in which this file was created to the year 2007) by
- Cognizo Technologies, Inc. All Rights Reserved.
- I'll update the License statement in the root with some words to the effect that;

This application is covered by two licenses.
1) Mozilla Public License 2.0 for all new and significantly altered code
2) The Original Code circa 2007 is "CATS Public License Version 1.1a"  (a modified Mozilla Public License)

**Comment by mlespiau** [comment]
Hi @RussH, any chance we can work on this soon? It would be great to have a clear guideline moving forward and to start applying this to our own project.

Also, is there any chance we could not need to add the licensing code to each file? Some clause like, all the code is under MPL2 unless stated otherwise?

**Comment by skrchnavy** [comment]
Hi. Looks the preamble must be in all new files (see https://www.mozilla.org/en-US/MPL/headers/ _This license must be used for all new code, unless the containing project, module or externally-imported codebase uses a different license..._ )
Also answer to Q4 in this [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) seems requires it.
JAVA developers use [Eclipse copyright generator](https://sourceforge.net/projects/eclipsecopyrigh/) to add comment to multiple files.

**Comment by RussH** [comment]
Further checking, looks like we can dual-license gpl v2 , modified mpl v2. Original work must be available but larger work primarily GPL. https://www.gnu.org/licenses/license-list.en.html   Will check license generator also. If we replace the portal with new code, that piece can be GPL with no footer.

**Comment by RussH** [comment]
Actually as there's no requirement within copyright law for the header to be in every file, then unless (e.g. lib.js) there's some complexity in the license, we will have a single License file in the root of the project;

>  If you can't put a header in the file due to its structure, please put it in a LICENSE file in the same directory.

So License file in the root to be updated to show;

    Mozilla Public License 2.0 for all new and significantly altered code
    The Original Code circa 2007 is "CATS Public License Version 1.1a" (a modified Mozilla Public License)
<insert MPL v2 here>
<insert CPL v1.1 here>

License header only to be retained in files considered unchanged - when 'significantly altered' remove the CPL License header.

**Comment by RussH** [comment]
Closed by commit https://github.com/opencats/OpenCATS/commit/e32c24d2ce942f086dcd5c7906ab2b2697253139
