### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by BentCoder** [opencats/OpenCATS#99]
Hi,

First of all this is not an issue! I just want to find out If I can install this app to Ms Windows 7 and **onwards** versions? Is there a limitation in terms of version?

Thanks

**Comment by skrchnavy** [comment]
We are able to run OpenCATS on Windows 7 and WampServer (https://sourceforge.net/projects/wampserver/) v3.0.4.

**Comment by BentCoder** [comment]
Thank you
